### ISSUE TITLE
Question: Table Detection of sorting change

### ISSUE THREAD

**Issue by alamse** [bootstrap-vue/bootstrap-vue#1026]
i've try`@sort-changed` event, it's working. but i want disable local sorting, so on that event, i can load my endpoint. any advice for that ? thanks

**Comment by tmorehouse** [comment]
If you are using an items provider function (i.e. `items` is a function that returns an array), by default the sorting needs to be handled by the provider function.

**Comment by tmorehouse** [comment]
So rather than provide an array directly to the `items` prop, pass a method which returns your array of data.  When you method is called it will be passed a context object which contain the current state (sortBy, sortDesc, etc).  You can then use this content object o do your own sorting, and then return the sorted items array.  See https://bootstrap-vue.js.org/docs/components/table#using-items-provider-functions

**Comment by alamse** [comment]
> When you method is called it will be passed a context object which contain the current state (sortBy, sortDesc, etc)

ah ok, i will try it.
