### ISSUE TITLE
Allow 'title' property for 'options' of form-radio and form-checkbox

### ISSUE THREAD

**Issue by Alsciende** [bootstrap-vue/bootstrap-vue#1083]
Currently the options of form-checkbox and form-radio are the same as form-select, and they have the properties 'value' and 'text'.

It would be useful to have a 'title' property to set the browser-level tooltips of the buttons when the inputs are displayed in 'button' style.

**Comment by tmorehouse** [comment]
The next release of Bootstrap-Vue has sa major revamp of form-select, form-radio and form-checkbox.

Check out the pending docs at 
- https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/docs/components/form-select/README.md
- https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/docs/components/form-radios/README.md
- https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/docs/components/form-checkboxes/README.md

**Comment by tmorehouse** [comment]
The new version of radio/checkbox are now available.

You can place individual b-form-radio/b-form-checkbox inside a form-radio-group or form-checkbox-group.

Any attributes (that aren't a prop) placed on b-from-radio or b-form-checkbox will be applied to the wrapper element.  So rather than providing a list of options to form-radio-group or form-checkbox-group, just use a v-for loop to generate the individual inputs inside the parent group component.

See the updated docs at: https://bootstrap-vue.js.org/docs/components/form-checkboxes

**Comment by Alsciende** [comment]
That's pretty cool, thanks for detailing the process.
