### ISSUE TITLE
Should modal always be appened to document.body?

### ISSUE THREAD

**Issue by soichih** [bootstrap-vue/bootstrap-vue#1108]
My app consists of various sidebar / menubar with various z-index / position CSS parameters. When I use b-modal inside my component, it tries to render the dialog inside the div where the  child component is located which might be buried under other div / scroll bars, etc.

![brain life](https://user-images.githubusercontent.com/923896/30831681-59e75928-a216-11e7-9463-bf67b2b85910.png)

It looks like I can fix this simply by moving the b-modal to document.body via mounted() hook on the component that's hosting the dialog

```
   mounted() {
        document.body.appendChild(this.$refs.modal.$el);
    },
```

My app now looks like this.

![brain life 1](https://user-images.githubusercontent.com/923896/30831721-909ff8bc-a216-11e7-844c-27f9d9a549cf.png)

My question is, shouldn't the modal always be moved to the body for it to be rendered as designed? (Or at least moved to body by default while allowing user to not move it if they so choose via b-modal option?)

**Comment by tmorehouse** [comment]
Modal always get placed into the document where you place the b-modal component.

Moving Vue generated DOM components to another part of the document i tricky, and in many cases can make Vue throw errors, specifically if the parent container goes out of scope and the DOM elements are left hanging with event handlers still bound,  causing memory leaks and errors in your project at run-time.

You need to make sure you move that DOM back before the component gets destroyed, or before a route changes (if using a client side router, etc)..

**Comment by soichih** [comment]
@tmorehouse Thanks for the info.

If I shouldn't move my modal, what is the alternative? I wish Vue had a capability to do opposite of <slot>; to render child content on parent component, but since it doesn't, the only alternative is to move my dialog UI / logics to the parent component; which goes against the philosophy of components, I think.

If moving it manually via mounted() is the next-bad option, I was hoping that, bootstrap-vue could handle the moving to/from document.body so that I don't have to do this.

**Comment by tmorehouse** [comment]
Bootstrap-Vue would have to do the same thing your are doing.  Vue always renders it's DOM elements where you place the component, and it has to reside in the context of the over all app, which usually is a DIV inside the body.

You might be interested in trying [portal-vue](https://github.com/LinusBorg/portal-vue), which is still somewhat experimental.

**Comment by alexsasharegan** [comment]
@soichih, I personally place a couple modals at my root-most container component (I call it my _page-component_). I use one for error displays, one for "are you sure?" interactions, and then one for generic information. You can use events emitted on root, a global event bus, or vuex to trigger the container component to show and properly render these modals.

**Comment by tdbear** [comment]
I can't stress enough how important a clean solution to this is. The practical need to be able to support self-sufficient re-usable vue components trumps all other purity and style concerns IMO.

If re-parenting on mount is going to be a workaround, then why not make it a bit easy? `<b-modal :reparent="true">` 

Maybe the best solution is to make sure that modal is always displayed correctly (uses browser window area) no matter where it is parented via markup and CSS? After all, nobody ever wants to have a modal constrained to just an area of the screen.

**Comment by tmorehouse** [comment]
The issue with re-parenting is stranded markup.

When re-parenting, a lot of extra behind ht scene things must happen, such as:
- Using vue-router and the route changes, but the modal was re-parented outside of the router-view, so there need to be checks to handle route changes (watcher)
- Using keep-alive components... needing to be able to handle when the component is taken out of view (but still alive in memory), and then brought back.
- `v-if` components (similar issues to above)
- Ensuring the content is destroyed properly on destroy, (preferably bringing it back to where it was first placed to keep Vue happy)

Its many things to keep track of, adding complexity to the base modal code.

Things such as `portal-vue` can help with re-locating content, and have been tuned to handle many of the situations.

**Comment by tdbear** [comment]
Re: concerns that you outlined. I'm not a vue expert. I never used a router for example. But I was hoping that vue component lifecycle methods would be enough to cover all possible scenarios of disconnection and destruction. Although I gave it a good look just now and there seems to be no "disconnect" hook.

`portal-vue` breaks the idea of self-sufficient components. Components begin to rely on existence of a magical external "slot" while we know the "slot" is always there: body.

I guess fixing markup/positioning is not an option BS4 documentation is pretty clear about implications of using `position: fixed`.

**Comment by soichih** [comment]
I agree with @tdbear .. I can live with some risk of memory leak under a few special circumstances. I trust that boostrap-vue developer can do way better than my bare minimum hack to get this to work - which I believe most other users would end up doing anyway. 

Another reason for this *fix* should be contained within bootstrap-vue is that, it's really a bootstrap's implementation detail that necessitates the modal to be relocated to the body. What if bootstrap *fixes* this somehow in the future and relocation is not needed anymore? 

I think bootstrap-vue should relocate modal to body by default and provide a flag to not do this if there are users out there who prefer to use `portal-vue` or has other reasons not to move it.

**Comment by tmorehouse** [comment]
There is more than just memory leaks... it is leftover **opened** modals.  If you happen to have a route link inside your modal, and you navigate to that route, but the modal is no longer within your route-view (where originally placed), teh router view changes, the original container for the modal markup is now gone, but you have this stranded opened modal covering your screen.  The handlers to close the modal are now gone (since they were inside the router view and are now taken out of memory/DOM), and your stuck with a non-usable user interface.

**Comment by soichih** [comment]
@tmorehouse "If you happen to have..." < that's my point though. We can never cover 100% of everything that could happen, or user might do... but that shouldn't prevent bootstrap-vue from providing a sensible default behavior that works for bulk of the use cases. For one thing, I don't think most user will have route link inside the modal. You can just state in the documentation not to do that.

Also, I am not married to relocating the modal to fix this problem. You seem to know the inside & out of Vue and bootstrap4. Isn't there a better alternative to relocating the modal that can fix this - contained all within the bootstrap-vue component? Element UI's modal doesn't have this problem so I think there is a way.. I hope.

**Comment by tmorehouse** [comment]
Vue.js really frowns upon relocating DOM outside of a component that it doesn't control (i.e. into the body).

The popover component does this, but it has issue where it randomly leaves a disconnected popover floating in the upper left hand corner of the veiwport.  We have all the hooks in place (activated, deactivated, mounted, beforeDestroy, destroyed, watching for route changes, detecting if a vue-router is used, etc) but the "bug" persists. And the bug is not consistent (depends on browser render times/horsepower, and asset load times/sequence).  So I would be really hesitant to introduce this bug into another component.

As well, it is impossible to relocate DOM when server rendered, and Modal has an option to initially show the modal (i.e. as soon as it is rendered).  Relocating it on the client only would cause SSR rehydration to bail and re-render your entire page, which is not a good end user experience.  For modal there are just way too many "what-ifs" to deal with logically (initially opened/clsoed state, avtivated/deactivated and dealing with initially opened state, router-view changes, etc.  In each of those cases the DOM must be moved back to its original location before being taken out of memory to keep Vue and its virtual DOM layout happy.  And minor thing missed can cause render errors, duplicate content, re-hydration bails, etc.

All this just to handle being placed inside a fixed container in special cases.  

One could create re-usable modal's that are placed at the bottom of the main page view, and use $root events (or event's emitted on a bus, or vuex store states), or function calls to signal a custom component to open the appropriate modal and render the desired data.

I've done the above in a few of my projects, it adds a bit more complexity, but reduces final project asset bloat by not having 500 modal instances hidden away until needed.

**Comment by tdbear** [comment]
Just throwing half-baked ideas out there: what if we always parent/render modals onto the root element of the containing `Vue` instance? This at least solves the issue in most cases, opens possibility of re-use of the markup. Sure people can still place the root element into a static container, but that is way less likely. Not sure if this is technically possible with vue.

**Comment by tmorehouse** [comment]
It solved the issue only if you have a single page.  Many people use vue-router to do push state client side routing.  The main vue component never dies, and new sub components are brought in and out of the page (inside of the root vue component, i.e. via router-view changes content, but the parent vue wrapper stays the same), so that wouldn't work, and doesn't solve the issue in the majority of cases (unless you only have a single page/view, or force a page reload on every link navigation)

**Comment by tmorehouse** [comment]
The issue with fix-positioned parent containers is documented in Bootstrap V4 (and V3)
https://getbootstrap.com/docs/4.0/components/modal/#how-it-works:
>Modals use position: fixed, which can sometimes be a bit particular about its rendering. Whenever possible, place your modal HTML in a top-level position to avoid potential interference from other elements. You’ll likely run into issues when nesting a .modal within another fixed element.

Since Bootstrap-Vue is based on Boostrap V4.beta CSS, it inherits the issues associated with Boostrap V4.beta's CSS.

Basically, place your modal (or `<b-modal>`) component outside of any fixed position containers.

**Comment by tmorehouse** [comment]
@soichih the next release of BootstrapVue (next release after 2.0.0-rc.19) will be using PortalVue to render the modal appended to the `<body>` element, by default (and modals will always be rendered lazily by default).
