### ISSUE TITLE
Checkbox in input group causes input rendering to be too large

### ISSUE THREAD

**Issue by tspink** [bootstrap-vue/bootstrap-vue#1115]
Hello,

When using a checkbox in an input group, the checkbox asserts padding that stretches out the input:

```
<b-input-group>
  <b-form-input type="number" v-model="quote.defaults.discount"></b-form-input>
  <b-input-group-addon>
    <b-form-checkbox title="Apply to all" v-model="quote.defaults.discount_recurse">
    </b-form-checkbox>
  </b-input-group-addon>
</b-input-group>
```
If I replace the b-form-checkbox with a regular unstyled checkbox, the group is rendered correctly sized.

Please see this fiddle: https://jsfiddle.net/9xgcjg3e/

Have I made an error in the mark-up, or is this an issue?

Thanks,
Tom

**Comment by jackmu95** [comment]
What causes this issue is that `bootstrap-vue` creates a custom checkbox inputs by default.
This behavior can be changed by setting the `plain` property to `true`.

This doesn't solve the problem completely, because it generates the default bootstrap checkbox markup, which looks something like this:
```html
<div class="form-check">
  <label class="form-check-label">
    <input type="checkbox" class="form-check-input">
  </label>
</div>
```

The only solution I came up with is to stick with plain checkbox inputs because this is what Bootstrap does in it's [input group docs](https://getbootstrap.com/docs/4.0/components/input-group/#checkboxes-and-radio-addons).

**Comment by tmorehouse** [comment]
That is true.  One must use native checkboxes and radios when placing in input groups.

We'll have to mention this in the documentation, and give a few examples.

**Comment by tspink** [comment]
Thanks for the clarification, I really appreciate it!

Tom

**Comment by tmorehouse** [comment]
The next release will have expanded documentation that covers this.
