### ISSUE TITLE
Drowdown keep dropping on Router Link reload

### ISSUE THREAD

**Issue by congtoanle** [bootstrap-vue/bootstrap-vue#1139]
I use dropdown item on header, when I click on dropdown item to a router link, it load and keeping the Dropdown dropping. How can I fix that? Thank you!

**Comment by tmorehouse** [comment]
Which version of Bootstrap-Vue are you using?

**Comment by congtoanle** [comment]
Lastest version launching 0.20.2, bro

**Comment by tmorehouse** [comment]
0.20.0 is an older version.  For Bootstrap V4.alpha.6 CSS use version 0.23.0, and for Bootstrap V4.beta use 1.0.0-beta-9

**Comment by congtoanle** [comment]
I use npm update. It;s just get version 0.20.2 :(

**Comment by tmorehouse** [comment]
You should be able to specify bootstrap-vue dependancy as `^0.23.0`

**Comment by congtoanle** [comment]
ver 1.0.0-beta.9 remains error. This link on a component call in dropdown menu. When click to this link, page change but dropdown remains. :(

**Comment by tmorehouse** [comment]
Could you provide a sample of your dropdown markup?

**Comment by congtoanle** [comment]
```
<b-nav-item-dropdown class="no_toggle" right>
    <span slot="text"><span class="badge top noti">99+</span>
    <svg></svg>
    </span>
    <div class="drop_content large">
      <div class="tabs friend_re">
        <div class="header">
          <span>Notifications</span>
          <router-link to="/settings/" title="settings"><svg class="pull-right" role="img" viewBox="0 0 54 54"><use xlink:href="#settings_i"></use></svg></router-link>
        </div>
        <div class="tab-content">
          <ItemNotification/>
        </div>
      </div>
        <a href="/" title="Mark as read">
            <div class="drop_below">Mark as read</div>
        </a>
        </div>
  </b-nav-item-dropdown>
```
This is Dropdown Components. It's in header bar. When I click on router-link to="/settings/". It load settings page but remain Dropdown opening.

**Comment by tmorehouse** [comment]
This is because you are using native element, and not the supported dropdown sub-components.

Dropdown's only support the following components (as per the docs https://bootstrap-vue.js.org/docs/components/dropdown/#supported-sub-components):

Sub-component | Description | Aliases
-- | -- | --
`<b-dropdown-item>` | Action items that provide click, link, and <router-link> functionality. renders as an <a> element by default. | `<b-dd-item>`
`<b-dropdown-item-button>` | An alternative to <b-dropdown-item> that renders a menu item using a `<button>` element. | `<b-dropdown-item-btn>`, `<b-dd-item-button>`, `<b-dd-item-btn>`
`<b-dropdown-header>` | A header item, used to help identify a group of dropdown items. | `<b-dd-header>`
`<b-dropdown-divider>` | A divider / spacer which can be used to separate dropdown items. | `<b-dd-divider>`

These sub components have the proper event listeners on them in ortder to close the dropdown menu.

**Comment by congtoanle** [comment]
I got it. Thank you for your support @tmorehouse
