### ISSUE TITLE
Document how to use icon libraries

### ISSUE THREAD

**Issue by gquintana** [bootstrap-vue/bootstrap-vue#1174]
I'd like to have a page describing how to integrate icon libraries described in https://getbootstrap.com/docs/4.0/extend/icons/ (iconic, octicons...) with bootstrap-vue:
* Which tested/recommended NPM package to install (vue-awesome, vue-octicon...) ?
* How to safely integrate with NPM + Webpack +  Vue + Bootstrap?
* How to use icons in b-button... ?

**Comment by kperveen** [comment]
+1

**Comment by tmorehouse** [comment]
Use can use any 3rd party icon system, or even plain font+css based icons.

Since Bootstrap-Vue's goal is to provide Bootstrap-Vue components, icon's are technically out of scope, and we have no preference over which icon lib people should use. Even Bootstrap V4 docs only lists icon libraries and doesn't document how to use them.

Basically the docs from each icon library describe how to use the Icons.

i.e. for `vue-awesome`:
```js
 // import all icons
import 'vue-awesome/icons'
// OR import individual icons
import 'vue-awesome/icons/home'
import 'vue-awesome/icons/star'
// Import the Icon component
import Icon from 'vue-awesome/components/Icon.vue'
// Add the icon component to Vue
Vue.component('icon', Icon)
```
Then use it:
```html
<!-- Use the icon in your markup -->
<icon name="home />
<!-- or in a button or other component -->
<b-button><icon name="home"/> Home</b-button>
```

This above is basically from the `vue-awesome` docs.

**Comment by gabel** [comment]
Stepping into the exact same situation and came up here. Would make sense to have a least a short part with example and links to possible solutions.

**Comment by mosinve** [comment]
I use pure FontAwesome for my projects by `npm install font-awesome`
and importing scss into project's main.js
`import 'font-awesome/scss/font-awesome.scss'`
and set up webpack to handle scss and font files.
here's my [webpack.config.js](https://gist.github.com/mosinve/00d1c2715dd573c6db38e9ac7139c215)
