### ISSUE TITLE
is-nav-bar causes tabs or pills to be vertical?

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#1229]
I copied the example from the top of the documentation Nav page, wrapped it with b-navbar, and added is-nav-bar, as shown in the attached example.  The tabs (or pills) shows up vertically rather than horizontally. And they're not properly formatted.

As an experiment, I deleted "is-nav-bar", and lo-and-behold, it works perfectly.

Conclusion: something is wrong with "is-nav-bar".

(Note: the attachment should be a .vue file, but GitHub won't permit that.)

[example.txt](https://github.com/bootstrap-vue/bootstrap-vue/files/1408728/example.txt)

**Comment by tmorehouse** [comment]
use three backticks followed by the letters html, then paste your code starting on a line below that, then follow that with three backticks on a new line.  That will give you properly pasted/formatted code samples. See https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

`in-nav-bar` switches from using the the  Bootstrap class `.nav` to the class `.navbar-nav` (as per the Bootstrap V4 spec), so that the proper alignment and event handlers are applied (typically `<b-nav is-nav-bar>` is used inside a collapse element).

**Comment by mhldtna** [comment]
Thanks for the explanation how to paste code samples into this system.  I somehow had expected that the "<>" icon above the edit area would do the job.

The behavior that I'm seeing can't be what is intended.  It really looks like a bug.

**Comment by mhldtna** [comment]
Possibly-related:  I added a b-navbar-brand element and all the tabs or pills got positioned on the right-hand side of the navbar.  On a hunch, I added "toggleable" to the b-navbar tag, and the pills now end up immediately to the right of the brand, where they should be.

Then I tried adding "is-nav-bar" to the b-nav line, and it messed-up the colors of the pills.

I hadn't previously put in the toggleable option, and haven't yet tried b-nav-toggle because there's almost no documentation on what these do or how to use them.

**Comment by tmorehouse** [comment]
There is a complete example on the navbar docs which shows the usage of the b-nav-toggle + b-collapse: https://bootstrap-vue.js.org/docs/components/navbar

I would also recommend becoming familiar with the official bootstrap documentation at http://getbootstrap.com/ as Bootstrap-Vue assumes that users will have knowledge of how Bootstrap V4 works, as well as basic Vue understanding.
