### ISSUE TITLE
What does it take to show which tab or pill is active?

### ISSUE THREAD

**Issue by mhldtna** [bootstrap-vue/bootstrap-vue#1244]
I setup a navbar with a nav and a couple nav-items, one of which is active.  I expected that when I click between the tabs or pills, that the color styles would automatically update to show one is active.  But that doesn't happen.

Here's an example, stripped-down from the example at the top of the navbar doc page:

    <b-navbar toggleable="md">
     <b-nav-toggle target="nav_collapse"></b-nav-toggle>
     <b-navbar-brand href="#">NavBar</b-navbar-brand>
      <b-collapse is-nav id="nav_collapse">
       <b-nav is-nav-bar pills>
         <b-nav-item active href="#">Link 1</b-nav-item>
         <b-nav-item href="#">Link 2</b-nav-item>
       </b-nav>
     </b-collapse>
    </b-navbar>

I know that in regular bootstrap, you specify the data-toggle attribute to get the tabs or pills to automatically update on the page. But I don't see an attribute like that in the nav-item description.  So what do I need to do to get the tabs/pills to update? 

I tried adding an @click handler that does "$('#link2').addClass('active');" (where "link2" is an id that I added to the "Link 2" nav-item).  After I took the href off that item, I was able to breakpoint in the click handler and verify that the jquery lookup is returning "[li#link2.nav-item.active]", which might be right.  But adding the "active" class doesn't seem to do anything.

By the way, the component reference on the navbar page lists a whole bunch of attributes for the various navbar components, but there is neither description nor example of how to use them. For example, what's the difference between the "active-class" and "exact-active-class" attributes?

**Comment by tmorehouse** [comment]
Since your navigation is disconnected from what is showing on the page (and URL), you need to manually set the `active` prop on the `<b-nav-item>` (say via your click handler on the `<b-nav-item>`).

In the case of the Bootstrap-Vue docs, the docs are running under [`vue-router`](https://router.vuejs.org), which handles enabling the `active` state based on the browser URL.

Refer to the **Router support** reference section at https://bootstrap-vue.js.org/docs/reference/router-link for what these props refer to.  They are only applicable if you are using `vue-router`, and the prop names are dictated by `vue-router` (read all about vue router at https://router.vuejs.org)

**Comment by tmorehouse** [comment]
Since these "issues" are not bug reports, but rather usage questions, I would suggest asking these types of questions in the Bootstrap-Vue slack community rather than generating bug reports on GitHub.

You can join the slack community by following this link https://bootstrap-vue.now.sh/
