### ISSUE TITLE
Close button is showing strange caracter

### ISSUE THREAD

**Issue by Seb00ch** [bootstrap-vue/bootstrap-vue#1318]
Hi !

I search on the web, in the issues, but I still haven't found any solution. I tested example on jsFiddle, it works, but in my project, the close button of the modal and alert components showing "Ã—". I search in the bootstrap-vue file and I found it at the line 1030. Why it isn't "\&times;" ?

My file is utf-8, my meta charset is on utf-8. Version of bootstrap-vue 1.0.2, vue 2.5.3.
To fix this issue, I replace the "Ã—" by "\&times;"directly in the file, any suggestions ?

Bye

**Comment by tmorehouse** [comment]
We've hard-coded the `&times;` to be the actual UTF-8 character `x` (which `&times renders to) due to innerHTML converting the `&times` to the UTF-8 character on Client Side, which causes a client side SSR mismatch.  See issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/1195 (SSR issue)  and https://github.com/bootstrap-vue/bootstrap-vue/issues/818 (identical issue to yours)

It sounds like your page isn't running in UTF-8 mode (maybe your server is sending a different character set in the HTTP headers), or your meta charset tag is incorrect.

**Comment by Seb00ch** [comment]
Thank you for your quick reply ! The error is coming from the server, because I test both with original bootstrap-vue file and compiled JS with Gulp.... It's strange. I check the issues you mentioned, #818
