### ISSUE TITLE
Form reset event does not update checkbox group values

### ISSUE THREAD

**Issue by garret-gunter** [bootstrap-vue/bootstrap-vue#1343]
**Description**
The form checkbox group component does not reset it's values on form reset.  While the components internal and bound states retain their values prior to the event, the displayed form shows the boxes unchecked.  From what I've tested, the values for both checkbox group and its child checkbox components do not change.  Note, I have not tested this with just checkbox components and no checkbox group component.

Here is a jsfiddle displaying the behavior.
https://jsfiddle.net/o29r1pob/1/

**Possible fix**
Sadly, I don't know enough about Vuejs to come up with a suggested fix.  Maybe the child components are incorrectly or not alerting their parent?

When reporting a bug, include:

- Operating system and version: Ubuntu 17.04 (64-bit)
- Browser and version: Chromium Version 62.0.3202.75 (Official Build)
- Version of Bootstrap-Vue: 1.0.2

**Comment by tmorehouse** [comment]
This is due to the nature of how Vue handle's form elements.  As the data model is the "source of truth" rather than the HTML markup (i.e. `checked` attribute on radios/checkboxes and `value on other input types.

What you would need to do is have a snapshort of your initial form element values.  Then create an `@reset` handler on your form (which `evt.preventDefault()` of the reset event (to stop teh native form reset from happening), and then resets each value in your model to the original value.

**Comment by tmorehouse** [comment]
For reference, see this VueJS issue https://github.com/vuejs/vue/issues/833

**Comment by garret-gunter** [comment]
Ah, I see.  Thanks.  Sorry for reporting it as a bug.

**Comment by mosinve** [comment]
https://jsfiddle.net/cihkem/h3wp0h38/2/

**Comment by shine-on** [comment]
@mosinve, fiddle above is simply killing the reset.

it is a button with custom click handler doing a traverse over form element(s), i.e. completely missing the point what reset was made for (where form itself is a container for default values and reset relying on them).

think of generated forms with dozen of elements each. how do you know [] is the *default* value for "selected"?

**Comment by mosinve** [comment]
1. It's not a button with custom click handler - button is a standart reset button. It's a custom form reset handler. 
2. Task was to add native form reset behavior to vue variable. 
3. Native form reset routine - doesn't respect any default values it just reset values in inputs

**Comment by mosinve** [comment]
if you need a reset, that respect default values, here's the same example refactored:
https://jsfiddle.net/cihkem/ggo9syb0/

**Comment by shine-on** [comment]
1. Having custom reset handler is equal to button text="Reset" click="resetForm"
2. No. You need to walk (traverse) a list of form elements and set some default values. This is why you need selectedDefault (for each element)
3. See 1, form reset.prevent="resetForm"  is NOT native form reset

for the 4, actually otherwise:

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#resetting-a-form

> 4.10.22 Resetting a form
> 
> When a form element form is reset, run these steps:
> 
> Let reset be the result of firing an event named reset at form, with the bubbles and cancelable attributes initialized to true.
> 
> If reset is true, then invoke the reset algorithm of each resettable element whose form owner is form.

Please read, what is "reset algorithm" for INPUT element:

> The reset algorithm for input elements is to ... set the value of the element to the value of the value content attribute

INPUT value specified is the default

Instead of minimizing work to adjust button click events, your approach simply makes all default values on form itself unusable

Native form reset will be broken until re-implemented in javascript (this is basically what both of your examples trying to do)

**Comment by mosinve** [comment]
Offer your solution.

**Comment by shine-on** [comment]
https://jsfiddle.net/mauromadeit/9po4j84o/

See, prop is v-model bound and another guy is trying to mutate prop value directly? Just like in case of native reset mutating form elements' values behind v-model's back.

I spent some hours trying to cook something similar for reset. But, in contrast to example above, element's reset algorithm doesn't fire any per-element event. It is, unfortunately, a parent directly mutating children props using reset algorithm.

**Comment by tmorehouse** [comment]
I would suggest bring up the issue back with Vue.JS to see if they have an appropriate solution, or maybe a feature request for handling form resets.

Since hte form inputs values are controlled by Vue reactivity, the real issue is, what is the default value for a Vue component form?  It is when the vue component is first instantiated? what if the form component (same instantiation) is re-used for other purposes (like editing a value in an array).  Resetting the form - should it go back to the very fist value when it was first instantiated? - or the value set at some point in time via the v-model? it all depends on your use application.

What I do, is place all my form values in data under a single data property (ie. `formFields: { input1: "", input2: [], ...}`), and make a deep copy as defaults in a data property called `formDefaults: { input1: "", input2: [], .. }`.  and then on form reset event, do a deep copy from `formDefaults` to `formFields` (one must do a deep copy in order to prevent passing references over).  Then form inputs are v-modeled to `formFields.input1`, formFields`input2`, etc.

And when I re-use the same form to edit a different record, I just populate the `formFields` object and `formDefaults`.

**Comment by shine-on** [comment]
@tmorehouse, additional data property is obvious but isn't the case here

**Comment by mosinve** [comment]
So.... our example hasn't any reset behavior and template for doggie component contains at least one blunder - you use inputs without form element. Thus this example, like mine hasn't a natural form reset. Futhermore, it hasn't any native form bevahior at all. 
Have you any **working** reset solution what respects default values?
