### ISSUE TITLE
form-checkbox-group button style does not work on BS4

### ISSUE THREAD

**Issue by techxax** [bootstrap-vue/bootstrap-vue#1367]
Example is following
https://jsfiddle.net/mahmutbest/9s5vchh0/

I am using bootstrap on front-end for other styling.
Vue including as Component

I think conflict when using scripts together

**Our slution is**
Your output is
`<label class="btn btn-secondary">`
works when label tag name change as button
`<button class="btn btn-secondary">`

![image](https://user-images.githubusercontent.com/33753635/32993913-107122ba-cd68-11e7-95a5-d8dced2542e2.png)

**Comment by tmorehouse** [comment]
See your other issue.  You have included incorrect Jvascript resources and invalid markup.

**Comment by tmorehouse** [comment]
The button plugin JS from Bootstrap V4 conflicts with the Bootstrap-Vue button (due to the requirement of `data-toggle="button"` to trigger the correct CSS styling.

You would either need to only include the Bootstrap V4 plugin files you need (minus the buttons plugin), or build your button style checkboxes in plain HTML markup (not using the b-checkbox-group component) and bind to the value of the checkbox value in your vue component.
