### ISSUE TITLE
attribute size inside b-form-input being ignored by bootstrap-vue

### ISSUE THREAD

**Issue by tjunussov** [bootstrap-vue/bootstrap-vue#1386]
Bootstrap-Vue latest, try yourself in live update add attribute size anc check it

**Comment by tmorehouse** [comment]
This?:
![image](https://user-images.githubusercontent.com/2781561/33072587-7d146420-ce96-11e7-800f-4a827d62a66f.png)

**Comment by tmorehouse** [comment]
Could you please provide the markup that you are using, as your title doesn't quite explain your issue.

The `size`  prop controls the bootstrap form-control size (i.e. default, `sm` or `lg`), and controls the font size and height of the control: https://bootstrap-vue.js.org/docs/components/form-input#control-sizing

Width of the control is always 100% of the parent container.

**Comment by tjunussov** [comment]
Sorry for late response, and I understood you point, 
but the issue is, HTML input attribute has official dom attribute called size as you know, 
I think here is namespace collision, size="10" ( length of chars ) and size="lg" ( view sizing )

p.s How could we assign normal DOM attributes of Form Inputs to Bootstrap components ?

**Comment by tmorehouse** [comment]
native `size="10"` controls the "width" of the input (based on current font size, in characters).  not the limit of the number of characters.  Bootstrap V4 CSS applies width 100% which overrides any native `size` attribute.

Since the form input, is most cases, are the root element of the components, any attribute that is not a component `prop` will be placed on the rendered root element (i.e. on the native input).  such as `max`, `min`, `maxlength`, `step`, `pattern`, etc.  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by joicenunes** [comment]
@tmorehouse i'm having trouble with pattern in <b-form-input>, i've tried to set it in some component fields, but they're not being rendered in the application. i mean, it's still accepting the characters that "i don't want".
