### ISSUE TITLE
How to programmatically scroll to a specific b-table row

### ISSUE THREAD

**Issue by tpines** [bootstrap-vue/bootstrap-vue#1390]
Is it possible to programmatically scroll to a specific b-table row ?  I don't see it in the docs.

**Comment by tmorehouse** [comment]
Scrolling the viewport so that the particular row is in view?

This is not a built-in feature of `<b-table>`.

You would need to have a reference to an element within the row, and then call the javascript navtive method `element.scrollIntoView()`

See https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by tmorehouse** [comment]
If you are looking to paginate a particular row into the view, you would need to figure out what page the row is on, and set the `current-page` prop to that value.

**Comment by tpines** [comment]
Thank you for the quick response @tmorehouse, I appreciate the info.
