### ISSUE TITLE
Pagination and router

### ISSUE THREAD

**Issue by akaNightmare** [bootstrap-vue/bootstrap-vue#1468]
I want to use vue-router and pagination, for example click on page 2 in footer pagination I want to update url string to ?page=2 and etc.

**Comment by tmorehouse** [comment]
Check out `b-pagination-nav` which is a paginator tailored for navigation, which support router-links:

https://bootstrap-vue.js.org/docs/components/pagination-nav

It supports two callback functions for generating the page links: `page-gen` and `link-gen`.

 `page-gen` is used for changing how the page numbers look in the paginator (they default as 1 to N, if no `page-gen` function is given)

`link-gen` is used to build custom HREF (or router-link TO props.

You'll probably be most interested in the `link-gen` callback.  It is passed a single argument (the page number that is being rendered as a button).  To generate a router link, return a router-link location (to) object. when link-gen returns an object it renders a router-link instead of a regular `<a href="...">`)

**Comment by SupriyaSudhindra** [comment]
how to use b-pagination for b-row with v-for?

**Comment by SupriyaSudhindra** [comment]
can you please provide example for other such components(except b-table) in guide?
