### ISSUE TITLE
textarea: object property value cannot be changed (input works as expected)

### ISSUE THREAD

**Issue by dominicbarnes** [bootstrap-vue/bootstrap-vue#1494]
I have a case where `<b-form-textarea />` works differently from `<b-form-input />` and it's causing issues for me in my app.

I have a component that has multiple inputs that each bind to different object properties. The value in my form is coming from a vuex store, and I'm passing it to my form component as a "computed property". When using a `<b-form-textarea v-model="value.property" />` I am unable to change the value in the `<textarea>`. It looks like the initial value from the object keeps overwriting whatever the user tries to input. (on each "input" event, that is) If I change the input to `<b-form-input />`, things go back to working as expected.

Here's a link to a [JS Bin](https://jsbin.com/xetabeyame/edit?html,js,output) that reproduces the bug. When trying to reproduce the issue, I did discover that not using a "computed property" caused this to behave more as expected, but the difference between input and textarea in this case still has me thinking it's an internal bug.

**Comment by tmorehouse** [comment]
When using a computed property as a v-model, you will need to create the computed prop with both a getter and setter. By default a computed prop is one way (getter only). What you are seeing is probably an artifact on form-input, not form-text area.

**Comment by tmorehouse** [comment]
‎If using a computed property for any two-way value, you should set up a getter and setter in the computed prop.                                                                                                                                                                                                   Normal computed props are one direction only (getter).You are probably seeing a side effect when using it on b-form-input,                                                                                                                                                                                   ‎                              From: Dominic BarnesSent: Tuesday, December 26, 2017 4:12 PMTo: bootstrap-vue/bootstrap-vueReply To: bootstrap-vue/bootstrap-vueCc: SubscribedSubject: [bootstrap-vue/bootstrap-vue] textarea: object property value cannot be changed (input works as expected) (#1494)I have a case where <b-form-textarea /> works differently from <b-form-input /> and it's causing issues for me in my app.
I have a component that has multiple inputs that each bind to different object properties. The value in my form is coming from a vuex store, and I'm passing it to my form component as a "computed property". When using a <b-form-textarea v-model="value.property" /> I am unable to change the value in the <textarea>. It looks like the initial value from the object keeps overwriting whatever the user tries to input. (on each "input" event, that is) If I change the input to <b-form-input />, things go back to working as expected.
Here's a link to a JS Bin that reproduces the bug. When trying to reproduce the issue, I did discover that not using a "computed property" caused this to behave more as expected, but the difference between input and textarea in this case still has me thinking it's an internal bug.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bootstrap-vue/bootstrap-vue","title":"bootstrap-vue/bootstrap-vue","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bootstrap-vue/bootstrap-vue"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"textarea: object property value cannot be changed (input works as expected) (#1494)"}],"action":{"name":"View Issue","url":"https://github.com/bootstrap-vue/bootstrap-vue/issues/1494"}}}

**Comment by dominicbarnes** [comment]
Oh gotcha, so the bug is that this works for `<b-form-input />`?

**Comment by dominicbarnes** [comment]
I don't know if that's the root issue. I updated the JS Bin to use a computed getter/setter, but it makes no difference. There must be something different about how a `<textarea>` tracks it's value internally as opposed to `<input>`.

**Comment by wassansalih** [comment]
I have the same issue did you solve it?

**Comment by dominicbarnes** [comment]
@wassansalih I've had to resort to using a `<b-input />` instead for the time-being :(

(the proposed solution of using a getter/setter computed property did not help me)

**Comment by derekphilipau** [comment]
@dominicbarnes I was having the same issue- other form components can be updated but not textarea.  @tmorehouse approach should work, or you can use a local object copied from the prop object.  In this case you will also need a watcher for that prop.  This works for me, but I'm not sure if it is the best way, as I have heard that watchers are not recommended.  See:
https://stackoverflow.com/questions/44790842/vuejs-right-way-to-edit-prop-without-changing-parent-data

**Comment by mosinve** [comment]
@dominicbarnes, you should review your example, your Vue programming way is not Vue reactivity friendly. It's not about Bootstrap-vue.

**Comment by dominicbarnes** [comment]
@mosinve I believe I demonstrated that this is an issue with bootstrap-vue by showing that `<b-form-input>` and `<b-form-textarea>` work differently. My example was minimal on purpose to demonstrate the problem in as little code as possible, so it's not 100% like my real-life code. (but the bug is the same)

**Comment by mosinve** [comment]
If you look at your example closely, you'll see, that both `b-form-input` and `b-form-textarea` don't set `value.property`. 
Because the whole example is wrong. This is an example of how not to write components. It's not the bug.

**Comment by EnSabanNur** [comment]
I'm having the same issue here. A computed property being provided via vuex is passed to the `b-textarea` as v-model. Editing to the area is not possible (text disappears), and the setter is never called. I get why the text is being removed, I'm not 100% sure why the set isn't being called though.

I'm doing something like this:

```
<b-form-textarea
    v-model="step.text_to_speech"
    ... />

... 

computed: {
  step: {
      get () {
        return this.$store.getters['routingEditor/stepData'](this.$props.stepId)
      },

      set () {
        // this is never called
      }
  }
}
```

**Comment by wassansalih** [comment]
Hi @EnSabanNur @mosinve and all, the solution may be done like this:
<b-form-textarea
    v-model="computedStep"
    ... />
... 
 data () {
   return {
      stepInData = ' '
   }
 },
computed: {
  computedStep: {
      get () {
        return this.$store.getters['routingEditor/stepData'](this.$props.stepId)
      },
      set (newValue) {
        this.stepInData = newValue
      }
  }
}

**Comment by Kuvalda** [comment]
I have the same issue with vuex.
b-form-input works correct value edit correctly and raised change event when press enter or lost focus.
When i change it to b-form-textarea i have problems:

Important issues:
1. When i bind v-bind:value its not editable, any typing in control show typed char then reset all to initial value.
2. When i bind v-model... (its not correctly for vuex because this generate warning on every key press about store mutation outside commit.

3. Also non important issue is.... No change event fired on enter (i known its new line here...) or lost focus, fired only input on each type. I thing it problem for user experience because editing in textarea different with editing input and lost performance because i need synchronize changed value with my backend and update frontend store.
