### ISSUE TITLE
Navbar example is not working on documentation site

### ISSUE THREAD

**Issue by mika76** [bootstrap-vue/bootstrap-vue#150]
It just shows a thin, dark line.

**Comment by pi0** [comment]
Hey @mika76 thanks. i'm working on that :) Docs are under heady changes :)

**Comment by pi0** [comment]
**UPDATE**

NarBar is not working in JSFiddle (And we don't know why!!) 
Workaround: Copy/Paste HTML to BootstrapVue playground and it will work :)

**Comment by christopherburton** [comment]
@pi0 What about testing on [CodePen](https://codepen.io)?

**Comment by pi0** [comment]
@christopherburton CodePen is great too. But i decided sticking with JSFiddle (at least for now) for some reasons. (It is used by officially Vue examples website, Simpler to use, Directly embedding from github, etc) I can't just figure out what is wrong with it on navbars :))

**Comment by mosinve** [comment]
Tried in codepen - same result.
http://codepen.io/cih/pen/vxpojJ

**Comment by mosinve** [comment]
found source of problem 
`<b-nav-toggle target="nav_collapse_1" />`
changing this to classic start/end notation allow to render whole navbar
https://jsfiddle.net/gfqucs0z/13/
http://codepen.io/cih/pen/vxpojJ

**Comment by mosinve** [comment]
Citate from[ Vue.js guide ](https://vuejs.org/v2/guide/components.html)
> If your component isn’t passed content via slot elements, you can even make it self-closing with a / after the name:
`<my-component/>`
Again, this only works within string templates, as self-closing custom elements are not valid HTML and your browser’s native parser will not understand them.

**Comment by mosinve** [comment]
So, if we using self-closing notation inside .vue component - all goes well. 
But if we use HTML page as template for our components - we should avoid using self-closed elements.

**Comment by mosinve** [comment]
By the way, @pi0, why u use `to` attrib inside `<a>` tag instead of `href`?
>     <a class="navbar-brand" style="color:white" to="/">
>       <span>Bootstrap</span>
>     </a>
It's not rendered in the href attribute in the result code... 
Futhermore, if we use href instead of to, Bootstrap's reset stylesheet applies correctly, and we won't need to use inline style="color:white"

`_reboot.scss:179`

>     a:not([href]):not([tabindex]) {
>         color: inherit;
>         text-decoration: none;
> 
>         @include hover-focus {
>             color: inherit;
>             text-decoration: none;
>         }
>         &:focus {
>             outline: 0;
>         }
>     }

**Comment by pi0** [comment]
@mosinve YESS Thanks for finally fixing that problem :D I've just update current navbar example as well. `<a>` and `<div class="dropdown-item">` tags also replaced with `<b-link>` and `<b-dropdown-item>` as well so we don't need that style tag anymore and standard `:to` prop will work now :) 

In depth details about `:to` and `<b-link>`:
If you try navigating in docs website, you will find-out clicking on links don't just changes url, page changes are done by [vue router](https://github.com/vuejs/vue-router) html5 histroy mode. For vue-router, `<router-link :to="Object or String">` tags should be used instead of `<a href="String">`. Here we had two problems : 
- We need to keep bootstrap-vue decoupled from vue-router, if we only use `<router-link>` tags users not using vue-router won't be able to use bootstrap-vue !! So we should somehow test if it is available or not.
- On SSR usages, when page load is not completed yet (ie js is not loaded but page rendered from server side) we also need that `href` tags as well. both for probably displaying with bootstrap as you mentioned and allowing user navigate without need to `js`

Until 0.10.0-alpha this was hard-coded in components like `<b-btn>` and `<nav-item>` (so was not available for brand) Now we have a new component `<b-link>` which tries to solve this problems safely and nice. All other components are either using `<b-link>` or converting themselves to it using vue `:is` prop.
