### ISSUE TITLE
Setting _rowVariant on a click does not update the <b-table> items

### ISSUE THREAD

**Issue by xorbis** [bootstrap-vue/bootstrap-vue#1529]
I've done a lot of research on how one would implement a simple row highlight when using b-table.
After reading about everything in the documentation I understood that _rowVariant is an item property that does just that. So I implemented it like so:

```
<b-table :items="items" @row-click="rowClicked"/>

rowClicked(item, index, event) {
  this.items[index]._rowVariant = "active";
}

```
The row does not get any class update in it's DOM.
So I added some other test like so (to update the name column):

```
rowClicked(item, index, event) {
  this.items[index].name = "Clicked me!";
}

```
Still no update.
So I looked it up more and saw item providers and the refresh() call.
So I tried another test like so:

```
<b-table ref="table" :items="getItems" @row-clicked="rowClicked"/>

getItems() {
  return this.items || [];
},
rowClicked(item, index, event) {
  this.items[index]._rowVariant = "active";
  this.$refs.table.refresh();
}

```
Still no success, am I doing something wrong or could it be a bug?
Using:
		"bootstrap-vue": "^1.4.0",
		"vue": "^2.5.13",

**Comment by xorbis** [comment]
Adding
`this.$forceUpdate();`
Solves the problem.

**Comment by mosinve** [comment]
hi, is this issue resolved? 
While doing a DOM manipulations, you should consider that Vue.js updates real DOM with vDOM changes async, so you should use or `this.$forceUpdate(); ` or `this.$nextTick() `
https://vuejs.org/v2/api/#vm-nextTick

**Comment by gusehr** [comment]
Hi @mosinve 

The `this.$forceUpdate()` is still required when I change the _rowVariant property because it is not a rendered property.
I think this behavior is correct when I change an hidden property of the item.

What do you think we can do about this issue?
- Add some documentation to warn users about "changing _rowVariant on the fly"
- Add a kind of watcher to this property (is this possible?)

Thanks in advance.

**Comment by lmapii** [comment]
IMHO the problem is that you're adding a new key to an object (your row) without telling Vue: `_rowVariant` does initially not exist for your row. It should be possible to update the row without having to call `this.$forceUpdate()`:

```
import Vue from "vue";
/* ... */
    methods: {
        rowClicked(item, index, event) {
            Vue.set(item, "_rowVariant", "info");
       }
```

This adds the getters and setters that Vue needs in order to watch out for changes. Notice that you can access the element by the methods' parameter `item` instead of using `this.items`.

**Comment by gusehr** [comment]
Hi @lmapii 

I tried the `Vue.set` approach, but it doesn't work neither.
I think I can write the doc about this issue.

How can I contribute?

Open an pull request?
Just write it on this issue?

See ya.

**Comment by lmapii** [comment]
that's very strange .. i can even reproduce it with a simple jsfiddle:
https://jsfiddle.net/ouxzag5j/6/

for contributing - don't know. the issue is closed already since the force-update should do the trick too (but forces re-rendering)

**Comment by gusehr** [comment]
Hey @lmapii 

You are right... your fiddle works like a charm.
I will check it again on my codebase. I think it is something about Vue ou Bootstrap-Vue versions which I'm using.

Thank you

**Comment by HiloCoder** [comment]
@gusehr 
Did you get it to work using Vue.set()?  I'm experiencing the same issue where Vue.set() doesn't trigger an update.  I'm using the latest vue and bootstrap-vue versions.
