### ISSUE TITLE
b-table filters are interpreted as a RegExp even if the value is a String

### ISSUE THREAD

**Issue by xorbis** [bootstrap-vue/bootstrap-vue#1544]
With this component (written on the fly):
```
<template>
  <b-input v-model="filter"/>
  <b-table :filter="filter"/>
<template>

<script>
  export default Vue.extend({
    name: "my-component",
    data() {
      return {
        filter: ""
      };
    }
  });
</script>
```
If I type * in the input field, I get this console error:
`[Vue warn]: Error in render: "SyntaxError: Invalid regular expression: /.**.*/: Nothing to repeat"`

**Comment by FrancoPinoC** [comment]
A possible workaround while this is still an issue is to apply this `.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')` ([thanks SO person](https://stackoverflow.com/a/3561711/4192226)) to your filters, for example, instead of passing `filter` directly to the table, pass a computed property that applies that `.replace` to it... make sure to account for cases where `filter` might be `null` and such too I suppose. Not sure doing that is the best way to solve the issue in the b-table code, but mentioning it just in case other people end up here and find a temporary workaround useful.

**Comment by xorbis** [comment]
So basically when a user enters anything in the filter input field having a v-model mapped to the b-table filter, the filter is interpreted as a regex even if the type of the source v-model is set to String.

**Comment by xorbis** [comment]
Fixed it like this using "escape-string-regexp": "^1.0.5",

```
		<b-input v-model="filter_input"/>
		<b-table :filter="filter">

		watch: {
			filter_input: {
				handler(val, old) {
					this.filter = EscapeStringRegExp(val);
					this.page = 0;
				}
			},
```
