### ISSUE TITLE
b-img-lazy: no images until scroll

### ISSUE THREAD

**Issue by KonradDeskiewicz** [bootstrap-vue/bootstrap-vue#1619]
There should be initial check of "visibility" for lazy images.

Got list of products on the page but can't see images (that are in fact visible) until scroll even 1px.

**Comment by KonradDeskiewicz** [comment]
It looks that this is my rendering fault. Closing.

**Comment by victorhramos** [comment]
@KonradDeskiewicz im with this trouble. How you fixed it?

**Comment by emanuelmutschlechner** [comment]
There is an initial check which is executed when `<b-img-lazy>` is `mounted` and `activated` but due to the missing `getBoundingClientRect` of the html element nothing happens.

I would like to improve this component because it is very useful. Currently lazy loading does only work when the page scrolls. Not optimal when you have dynamic content and want to lazy load, but there is not enough content for the page to scroll. See my codesandbox below.
https://codesandbox.io/s/z5pkrx89m

In addition it would be nice to have state classes like `<router-link>` has, e.g. 
- `img-lazy-blank` when `blank` image is shown. Could be used to apply opacity or other css filters 
- `img-lazy-src` when `src` image is shown.

And a last improvement that comes to my mind is async loading of `src` images e.g.
```js
const prefetchImage = src => new Promise((resolve, reject) => {
    const img = new Image();
    eventOn(img, 'load', () => {
        resolve();
    });
    eventOn(img, 'error', () => {
        reject();
    });
    img.src = src;
});
```
