### ISSUE TITLE
Composing b-table and using template out of it

### ISSUE THREAD

**Issue by waldenermonteiro** [bootstrap-vue/bootstrap-vue#1700]
Hello, I'm composing the b-table, through this code:
```
<b-table :items="items" :fields="fields" small striped hover show-empty :current-page="currentPage" :per-page="perPageCustom" :filter="filter" :sort-by="sortByCustom" :sort-desc.sync="sortDesc" @filtered="onFiltered" :emptyFilteredText="emptyText">
      <slot></slot>
    </b-table>
```
And I'm trying to use this template but the table is not recognizing:
```
      <table-custom :items="parceiros" :sortBy="cnpj" :perPage="perPage">
        <template slot="acoes" slot-scope="linha">

          <b-button size="sm" variant="danger" class="float-right" title="Excluir Parceiro" @click="deleteParceiro(linha.item)">
            <icon name="trash" scale="1.0"></icon>
          </b-button>

          <b-button size="sm" variant="primary" title="Editar Parceiro" class="float-right" v-b-modal.modalCadastroParceiro @click="alterParceiroo(linha.item)">
            <icon name="pencil" flip="horizontal" scale="1.0"></icon>
          </b-button>
        </template>
      </table-custom>
```

How can I make the table recognize and use this template in the specified place?

**Comment by Diaskhan** [comment]
U composing template on server side or on client side ???

**Comment by waldenermonteiro** [comment]
client side

**Comment by tmorehouse** [comment]
You will need to convert your custom component template (table-custom) to a render function, so that you can pass the scoped/named slots to `b-table` (a child of your custom component).

Normally slots apply only the the parent component, but you need to pass them to the child component (b-table).

Render functions allow you to pass all the children (including any `slot` definitions) to the child component to handle.

See more about render functions at https://vuejs.org/v2/guide/render-function.html
