### ISSUE TITLE
Can't type in b-form-textarea

### ISSUE THREAD

**Issue by rafailml** [bootstrap-vue/bootstrap-vue#1708]
I'm trying to use textarea in my component, but I can't type in text. Sometimes I was able to type one letter but nothing more. The same code but with b-form-input -works. I can type a text there but in textarea - can't

I'm using textarea  in tabs:
```
<b-tab v-for="(item, index) in newItem" :key="item.code" :title="item.name" :active="!index">
<!--Input works-->
    <b-form-input id="InfoInput"
          type="text"
          v-model="item.value.info">
     </b-form-input>

 <!--Text area does not work-->
    <b-form-textarea id="countryInfo"
          v-model="item.value.info"
          :rows="3">
     </b-form-textarea>
</b-tab>
```

OS: Ubuntu 16.4
Browser: Google Chrome
Version of Bootstrap-Vue: 2.0.0-rc.2

**Comment by emanuelmutschlechner** [comment]
@rafailml is `newItem` a `computed` property or defined in `data`? I could reproduce your problem when using a `computed` property. As a temporary workaround define `newItem` in `data`.

This issue might be indirectly related to #1710. Can anyone confirm?

**Comment by rafailml** [comment]
It's array in data:
```
 data() {
        return {
            newItem: [],
...
```

**Comment by soichih** [comment]
I am not sure why this work, but a workaround for me was to initialize the object specified in v-model (in this cacse "info") through Vue.set(). I think the issue is something to do with the vue observability.

**Comment by DavidRueter** [comment]
I have the same problem, and can confirm that the workaround by @soichih works for me.

The behavior of not being able to type into the textarea seems to be that the value is immediately refreshed with the old value (i.e. the control is not read-only, but flickers and overwrites what you type).

This happens if neither :value nor v-model is set (i.e. if the control is not bound to data).  It also happens for me if the control is bound to an associative array where the element was assigned with =.  Changing the assignment to Vue.set() seems to work.

**Comment by SanduRajapakse** [comment]
Also experiencing this issue when using a computed property. Using standard textarea for now until fixed.

**Comment by yujianancy** [comment]
I have exact same issue. Is there any plan for this to be fixed?

**Comment by tmorehouse** [comment]
@yujianancy please open a new issue, and ensure you are using the latest release of BootstrapVue
