### ISSUE TITLE
:min gives an error with type="date"

### ISSUE THREAD

**Issue by HishamRamadan** [bootstrap-vue/bootstrap-vue#1765]
Hello,

I have a data variable called "today" contains the date of today.

I need my date picker disable all dates less than today so I tried to use "min" attribute in the following way: `<b-form-input type="date" :min="today"></b-form-input>`

It works, but with an error in the console: 

> [Vue warn]: Invalid prop: type check failed for prop "min". Expected Number, got String.

**Comment by Diaskhan** [comment]
The min and max directives is for number values not for date value ! Better is use validation of 3 party libraries in yuore case! 

It seems to me there not gonna be implemented in vue boostrap! Because validation rules its more form scpecific functional, not boostrap functional! Please see documentation about validation!

**Comment by HishamRamadan** [comment]
Yes, I know BootstrapVue limits the min & max to be for numbers only, and I made a workaround to handle this case, but I reported the issue so that it may be considered & fixed later.

**Comment by Diaskhan** [comment]
https://bootstrap-vue.js.org/docs/components/form-input/#component-reference
by documentation min and max works for number type !
In other case please read https://bootstrap-vue.js.org/docs/components/form#validation

**Comment by Diaskhan** [comment]
@HishamRamadan  boostrap-vue its not validate library!
Its iplementation of boostap libarby.
Standart boostap 4 doesnt include validation of data! This extensibility u must provide by yourself !

**Comment by emanuelmutschlechner** [comment]
This issue is related to #1751.

Submitted a pull request #1752

**Comment by emanuelmutschlechner** [comment]
But now it seems the commit #1734 should be reverted.

Adding `min`, `max`, `step` etc to `props` with specific types is not suitable for all HTML input elements. It is unnecessary because Vue inherits props. e.g.
```html
<b-form-input min="0" max="100"/>
<!--result-->
<input min="0" max="100">
```
And there is no specific reason to limit their types, as they are not used by the `<b-form-input>` component

**Comment by HishamRamadan** [comment]
@Diaskhan I do know BootstrapVue is not a validation library, but you're overwriting the default behavior so you've to handle all cases. Anyway, Thanks for your replies.

@emanuelmutschlechner Thanks for your reply.
