### ISSUE TITLE
Form Radio Label 'for' attribute not set while using with nuxt

### ISSUE THREAD

**Issue by tarunmangukiya** [bootstrap-vue/bootstrap-vue#1820]
I am using Bootstrap-vue in my Nuxt project.
Bootstrap-vue version: `^2.0.0-rc.9`
Browser: `Chrome`

The Form Radio is produced via for loop using data from backend. Initially I observed some of checkboxes and radio buttons un-clickable. Looking into the html markup of the same, we can identify that the `label` tag is not having `for` attribute that can access the original underlying radio control.

![image](https://user-images.githubusercontent.com/12470086/39944125-f6a4eaa8-5582-11e8-8d1b-6579206bae99.png)

Sample Code:
`

    <div :class="$style.licenses">
      <b-form-radio-group :checked="selectedLicense.id" @change="onChange">
        <b-form-radio
          v-for="license in licenses"
          :key="license.id"
          :value="license.id"
          :class="$style.license"
        >
          <span>{{ license.name }}</span>
          <template
            v-if="license.downloaded_by_user"
          >
            <span
              :class="[$style.price, $style.purchased]"
            >
              Purchased
            </span>
          </template>
          <price
            v-else
            :amount="license.price"
            :class="$style.price"
          ></price>
        </b-form-radio>
      </b-form-radio-group>
    </div>
`

I tried with nuxt in production mode too, but it's acting the same. It doesn't work even if I put a form-radio component without for some components, while it works while hot-reloading of the component.

**Comment by mosinve** [comment]
Strange, as main BV docs site built on Nuxt and radios working perfectly.

**Comment by farnabaz** [comment]
@mosinve examples of BV docs not render server side and they are rendering in browser.
This issue comes from generated `localId_` for component, if I set `id` for `<b-form-input>` it works fine, but without `id` BV tries to generate `localId_` for components one in server-side-render and one on client-side-render
And here is the bug, on server side `localId_` return `null` so `<label>` did not get any attr `for`, but on client side after ssr, `localId_` generate and id for component then `<input>`  update and gets `id` but `<label>` does not update 

finally `<input>` has proper `id` but `<label>` did not get any `for`

I think this issue is related to `<label>` tag behavior, because if I use another tag instead of `<label>` (like `<div>`), attributes will update and `for` attribute appears

**Comment by tarunmangukiya** [comment]
@farnabaz Will you be able to push the changes with correct behavior?

**Comment by tmorehouse** [comment]
ID's cannot be auto-generated on server side render, as it would cause SSR hydration errors.

When the component is Hydrated, a client side ID will be generated on the element

**Comment by tmorehouse** [comment]
PR #2161 should fix this issue, by waiting until after mount to set the safe ID (which can only be set on client side)
