### ISSUE TITLE
Repeating modal's show() and hide() asynchronously, modal is not closed at the last hide().

### ISSUE THREAD

**Issue by 4dn-oss** [bootstrap-vue/bootstrap-vue#1826]
OS: Windows 10 Pro (1709)
Browser: Firefox 60.0, Chrome 66.0.3359.170
Bootstrap-Vue: 2.0.0-rc.9

When you run the following script and press the 'start' button, modal will remain open.

```
<template>
  <div class="test">
    <b-button @click="start">start</b-button>
    <b-modal v-model="busy">{{api}}: calling...</b-modal>
  </div>
</template>

<script>
export default {
  name: 'Test',
  data () {
    return {
      API_DELAY: 100,
      WAIT: 1,
      api: null,
      busy: false
    }
  },
  methods: {
    callApi (api) {
      this.api = api
      const begin = () => {
        console.log(this.api + ': begin')
        this.busy = true
      }
      const end = () => {
        console.log(api + ': end')
        this.busy = false
      }
      begin()
      return new Promise((resolve, reject) => {
        setTimeout(resolve, this.API_DELAY)
      })
        .then(end)
    },
    wait () {
      return new Promise((resolve, reject) => {
        setTimeout(resolve, this.WAIT)
      })
    },
    api1 () {
      return this.callApi('API1')
    },
    api2 () {
      return this.callApi('API2')
    },
    start () {
      console.log('start')
      this.api1()
        .then(this.wait)
        .then(this.api2)
    }
  }
}
</script>
```

Setting `API_DELAY` to 500 and `WAIT` to 100 will result in expected behavior. That is, modal opens and "API1: calling ..." is displayed, modal closes, modal opens and "API 2: calling ..." is displayed, and modal closes.

Setting `API_DELAY` to short period, and `WAIT` to very short period, will result the modal which displays "API 2: calling ..." remains open.

The reason is that when `hide()`, `show()`, `hide()` is executed very quickly, the second `hide()` is ignored.

First, the second `show()` begins before the first `hide()`'s transition processing is over, but since the `modal-open` class added in the first `show()` still remains, execution of `doShow()` is delayed until the `hidden` event comes. Therefore, `is_visible` will remain `false` at this point.

When the second `hide()` starts at this time, `is_visible` is false so `hide()` skip processing and do nothing.

Eventually the first `hide()`'s transition process is completed. Modal is closed, a `hidden` event occurs, the delayed `doShow()` is executed and modal opens. However, since the second `hide()` has already ended, modal will remain open.

I got the expected behavior with the following patch.

https://github.com/4dn-oss/bootstrap-vue/commit/6cb97774b6fe0760393cd797b5d6490de2b95755

**Comment by emanuelmutschlechner** [comment]
Can confirm that `<b-modal>` isn't shown the second time when `v-model` changes within 1 to 350ms. 

IMHO the modal should be shown only once. This improves UX and simplifies chained promises handling. Show the modal before the first api request is made, hide it when something goes wrong with `catch` and hide it `finally` when all requests are done. Make sure to set `WAIT` large enough, so that `API_DELAY + WAIT` takes more time than the modal animation. 
https://codesandbox.io/s/9jm02plxyw

**Comment by emanuelmutschlechner** [comment]
Or else if you really want to show/hide modals without limitations (within 50ms), then disable the fade animation with `no-fade` prop

https://codesandbox.io/s/pppj5lzp0m

**Comment by Diaskhan** [comment]
ппппппп14.05.2018, 17:38, "Emanuel Mutschlechner" <notifications@github.com>:Can confirm that <b-modal> isn't shown the second time when v-model changes within 1 to 350ms.
IMHO the modal should be shown only once. This improves UX and simplifies chained promises handling. Show the modal before the first api request is made, hide it when something goes wrong with catch and hide it finally when all requests are done. Make sure to set WAIT large enough, so that API_DELAY + WAIT takes more time than the modal animation.
https://codesandbox.io/s/9jm02plxyw

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  





 -------------------------------Best regardsDiaskhan Imanberdiev

**Comment by 4dn-oss** [comment]
In my sample above, `api1` and `api2` represent asynchronous processing caused by arbitary user operation (or event). We can't know in advance which api is called in what order and at what timing. So, it is difficult to implement to show modal only once.

Setting the `no-fade` prop can mitigate the above phenomenon, but it seems not complete. When `API_DELAY` is set to 10, the same phenomenon occurred.

And, the UX I expect is that modal will not be seen if the time of api call is short enough, modal will only be visible if the time of api call is long enough. Setting no-fade prop makes it undesirable since the screen becomes flickering everytime, because modal is displayed no matter how long the time of api call is short.

**Comment by emanuelmutschlechner** [comment]
Instead of using `v-model` you could use lodash to solve this problem. Throttle the modal's `show()` function for e.g. 500ms to aviod these timing problems
https://lodash.com/docs/4.17.10#throttle

**Comment by 4dn-oss** [comment]
There are workarounds in individual cases. However, I think that this issue is a bug.

The current modal implementation has a process of deferring `doShow ()` until the modal closes completely if `show ()` is called during `hide ()`.

https://github.com/bootstrap-vue/bootstrap-vue/blob/b02a6ee376681a16f898170d387c99d0af1291b3/src/components/modal/modal.js#L504

So, I think that the modal specification does not tolerate the phenomenon that the modal which is set to visible remains hidden depending on timing. If so, maybe we should not tolerate the phenomenon that the modal which is set to invisible remains shown depending on the timing.

**Comment by tmorehouse** [comment]
Latest `dev` branch has changed modal behaviour
