### ISSUE TITLE
Table row detail collapse support

### ISSUE THREAD

**Issue by k8n** [bootstrap-vue/bootstrap-vue#1829]
It would be great if b-table would support b-collapse / animation for row detail.

I tried to hack around but found no way to make the components work together as they are.

Here is a jsfiddle based on the examples from the docs: https://jsfiddle.net/82jjt2me/1/

If anyone could give a hint on how to modify bootstrap-vue to support this feature, I'll craft a PR.

Thanks!

**Comment by tmorehouse** [comment]
You could just use a collapse inside the details slot, and then when details is opened use a next tick to open the collapse.

**Comment by bmarkovic** [comment]
> You could just use a collapse inside the details slot, and then when details is opened use a next tick to open the collapse.

This works with a visible and quite irritating delay tho so a solution that would optionally allow us keep hidden rows in the DOM and work directly with the b-collapse or CSS transitions directly (i.e. changing just some class on the details row based on hidden state) would greatly improve the feature.

For large tables where having this much DOM would be an issue this could then simply be opted out.

**Comment by tmorehouse** [comment]
collapsing requires conversion to `display: block`, computing the height, and then transitioning the height, so its not as simple as class that transitions the height unfortunately.

For example, see the original Bootstrap collapse code: https://github.com/twbs/bootstrap/blob/master/js/src/collapse.js#L133-L220

**Comment by bmarkovic** [comment]
All b-table would need to do is:

1. Keep details rows in DOM (ie not destroy them when not shown) 
2. Add a class to the details row depending on whether or not it's shown. You ship custom CSS anyhow and could toggle the CSS visibility of the row based on this. 

Everything else could then already be handled in CSS or by b-collapse by the user. 

The fact is b-collapse in details slot already works because the table row will stretch to the block element inside it's td child, but because the details row doesn't exist in DOM prior to the collapse condition is changed, the transition isn't animated.

Your workaround with `vm.$nextTick` works because it causes the change to happen when the details row is now in DOM. But it causes a noticeable delay that affects the UX in a horrible way. Note that `setImmediate` also works (and for the same reason) but introduces the same delay. 

Keeping the row in the DOM would mitigate this completely. 

I'm not advocating for this behavior to be default (for obvious reasons). It could be controllable from a boolean prop and default to existing behavior and the users can then make the choice. The documentation could communicate the tradeoffs of each solution.

**Comment by tmorehouse** [comment]
An alternative to `$nextTick()` would be `requestAnimationFrame()` which can execute a bit earlier than nextTick, although maybe not as fast as setImmediate (if the browser supports setImmediate)

**Comment by tmorehouse** [comment]
You could also make your details slot content a custom component, that executes the collapse show in the `mounted()` hook. Which will get around the delay.

**Comment by renaudpawlak** [comment]
> You could also make your details slot content a custom component, that executes the collapse show in the `mounted()` hook. Which will get around the delay.

It works indeed, but it is quite tricky and I find the solution pretty much complicated. So I share it here for further reference or discussions.

Additional custom row details components:

```javascript
Vue.component('custom-row-details', {
    template: `
        <b-collapse v-model="visible" @hidden="row.toggleDetails()">
            <div class="p-2">
                [...] <!-- content goes here -->
            </div>
        </b-collapse>
    `,
    props: ['row'],
    data: function() {
        return {
            visible: false
        };
    },
    mounted: function () {
        this.visible = true;
    },
    methods: {
        hide() {
            this.visible = false;
        }
    }
});
```

And, to use it in your b-table:

```html
<b-table [...] details-td-class="p-0">
     <template #cell(show_details)="row">
           <b-icon :icon="row.detailsShowing ? 'chevron-down' : 'chevron-right'" 
               @click="row.detailsShowing ? $refs['row-details-' + row.index].hide() : row.toggleDetails()" 
                style="cursor: pointer"
           />
     </template>
     [...] (other cell templates)
     <template #row-details="row">
           <custom-row-details :ref="'row-details-' + row.index" :row="row"/>
     </template>
 </b-table>
```

Note that this solution provides fluid animation, because the details' ``td`` (cell) is initialized with no padding (``details-td-class`` prop), and that the cell padding is actually defined in the collapse itself. So, when the cell becomes visible right before the collapse animation, or before it disappears right after the collapse retract, there is no empty space taken by the cell.

I'm not very happy with having to call a ``hide`` function in the custom component accessed with ``$refs['row-details-' + row.index].hide()``. I tried to find a more implicit solution but it is quite tricky because the details need to be hidden after the collapse animation.
