### ISSUE TITLE
Validation state visible on page load

### ISSUE THREAD

**Issue by connorb09** [bootstrap-vue/bootstrap-vue#1835]
I am running bootstrap-vue-rc.9, making use of the form-input validation states,

```
<b-form>
     <b-form-input 
          :state="validatePostcode"
          name="postcode" 
          id="policyPostcode" 
          v-model.trim="postcode"
     />
</b-form>
```
 This results in the input having the invalid/valid styles when the form has first loaded. If i'm not mistaken, the states should only be visible when the form element has the `was-validated` class.

It seems that when using the `state` prop, the `is-invalid` or `is-valid` class is added to the input, however, unlike the pseudo classes `:invalid` and `:valid` the bootstrap 4 css does not scope `form-control.is-invalid` and `form-control.is-valid` to a parent `was-validated` class. Hence the state styles are always visible.

I know that if the `state` prop is initially set to null then the input will show no validation, but Im not sure how I can have the `state` as null initially but then use a method after an attempted from submit.

**Comment by ejwaibel** [comment]
@connorb09 the way I got around this was by adding a `touched` property and setting it once the variable attached to `v-model` has changed, so in your example you could add the following:
```
data: function() {
    return {
        ...,
        touched: false,
    };
},
watch: {
    postcode: function() {
        this.touched = true;
    }
}
```

Then in your `state` function, you would just test `this.touched`

**Comment by moderatas** [comment]
I can confirm this still happens on v2.0.0-rc.11.

Besides the solution from @connorb09 , is there any other around this setting state to null at first?

**Comment by tmorehouse** [comment]
The `state` props is a tri-state prop that accepts `null`, `true` or `false`.

You will need to track the "dirty" state of the form yourself, as the inputs cannot determine if they are dirty or not, as components can be re-used, or have their values set after mount (rather than during create), or could have various constraints placed on them outside of normal HTML 5 validation.

Your app's data should be treated as the source of truth for validation, or you can use native HTML browser validation and place your controls inside a form element with `novalidate` set, and then on submit, add the `was-validated` class to the form (or use `<b-form>` to take advantage of convenience props.

`Dirty` tracking is not on the roadmap

**Comment by jeriveromartinez** [comment]
I had the same problem with the attribute :state, the question is that the class that ".was-validated. form-control:valid" has more priority than the class "form-control is-invalid", a reasonable way to solve That problem is using the pattern attribute, the only problem is that the latter is for regex expressions.
