### ISSUE TITLE
BootstrapVue Playground Crash

### ISSUE THREAD

**Issue by piboistudios** [bootstrap-vue/bootstrap-vue#1843]
I'm not sure what happened, but some code I was testing in the playground caused a crash. Crash reoccurs every time I visit the page because of session logging (and it crashes as soon as it loads the page because it immediately tries to run the bad code).

Wasn't sure where to talk about this at (workaround was using Chrome's incognito mode, cookie deletion does not work)

I imagine that the demo somehow reloaded in the midst of me typing some code and kicked off an infinite loop somehow.

**Comment by piboistudios** [comment]
This is the code in case you're wondering what I did:
![image](https://user-images.githubusercontent.com/21025122/40245404-35ac169c-5a8b-11e8-8772-654c689f669b.png)

**Comment by emanuelmutschlechner** [comment]
This happened to me too. When copy pasting code, compilation fails due to some error (e.g. reference yet undefined data variable in template) and makes playground unresponsive. CPU load increases to 100+ in Chrome Task Manager

Template and JS are persisted to Local Storage.

### How to fix
If you are using Chrome, this will help:

1. Open Chrome Dev Tools
1. Select tab `Application` 
1. Click `Clear storage` in sidebar
1. Finally click the button `Clear site data`, kill the tab and reload

### How to reproduce
Change `name` in Template to some undefined variable like `name2`.
![image](https://user-images.githubusercontent.com/27734375/40258748-e434f4f6-5af2-11e8-8e9e-71c867999629.png)

**Comment by emanuelmutschlechner** [comment]
As an alternative I recommend using [codesandbox.io](//codesandbox.io). I created a [BootstrapVue starter template](https://codesandbox.io/s/github/gonoware/bootstrap-vue-empty-sandbox). btw you can install node packages too!
