### ISSUE TITLE
b-table custom formatter escapes HTML

### ISSUE THREAD

**Issue by edtownend** [bootstrap-vue/bootstrap-vue#1875]
The docs suggest that basic HTML output is supported from a custom field formatter, but when I try the HTML gets converted to entities. 

Have I misunderstood the use, or is there a switch to disable the escaping?

This fiddle, adapted from the docs, demonstrates the problem:
https://jsfiddle.net/y7ntha1w/

Thanks!

**Comment by mosinve** [comment]
1. your example has error's
2. it's not formatter, this (hilighted by ****) will forever be escaped:
```js
<a :href="`#${data.value.replace(/[^a-z]+/i,'-').toLowerCase()}`">
        **{{data.value}}**
      </a>
```
3. you could try to use v-html in `a` element, but it's not very good :)

**Comment by andrewpros** [comment]
I don't see it answered, so not sure why it is tagged as so, i have the same issue, formatter output is escaped so cant return any HTML.
And i cant use any template as my table can be super big and fields, headers are generated on the fly depending on time range chosen, there could be like 100 columns so i would need to add 100 templates exactly the same but with different slot name, this is counterproductive.

So how can the formatter and formatter only return html so that it works?

**Comment by mosinve** [comment]
It's not a formatter escaped HTML, but Vue itself

**Comment by mosinve** [comment]
Please read VueJs documentations about rendering raw HTML https://vuejs.org/v2/guide/syntax.html#Raw-HTML

**Comment by mosinve** [comment]
@andrewpros just use `v-html` directive in case you need to render raw html

**Comment by andrewpros** [comment]
so no workaround?

**Comment by andrewpros** [comment]
@mapio Well i didnt get any better solution to this, my script is php so i just made a function to dynamically generate the needed templates slot just to get HTML in cells. Sad there is such workaround needed but it works.

**Comment by mapio** [comment]
Here is the change https://github.com/bootstrap-vue/bootstrap-vue/commit/63d80975539f4e338d3fc0fea4f22cfdee1290ee#diff-b43a022573f0b8d8be38c1f0e8f43351 introducing the escaping — or, to be more precise, allowing Vue to do the escaping (instead of injecting into `innerHTML`.

What about @mosinve allowing the formatter to return not just a string, but an object (containing the HTML in a suitable property)? I will write it, if you don't exclude to be willing to merge the change.

**Comment by mapio** [comment]
I've found a "workaround" that completely satisfies me, and will probably work also for @andrewpros. I realized just now that one can generate named template slots with a `v-for`. 

One can add a list (say named `formatted`) of fields to be formatted (for every different formatter) to the component `data`, and then add a `formatter` function (returning HTML) to the component `methods`.

Then the `b-table` can generate a `template` for every listed field and use a `span` with `v-html` to obtain the desired result.

A full example is at https://codepen.io/mapio/pen/ejJdqr the relevant code being

```
  <b-table striped hover :items="items">
    <template v-for='field in formatted' :slot='field' slot-scope='row'>
      <span v-html='formatter(row.value)'></span>
    </template>
  </b-table>
```
and
 
``` 
{
 ...
  data: {
    items: items,
    formatted: ['first_name', 'last_name']
  },
  methods: {
    formatter: function(data) {
      return '<b>' + data + '</b>';
    }
}
``` 

This solves the question for me.

**Comment by andrewpros** [comment]
Well yeah, its basically the same, u just dont generate those templates from server, i could have from 5 to even 100 columns or more so i didn't want to type them manually, my table is completely dynamic, headers are also generated, this workaround is good if don't need to type a lot names in that formatted array.

**Comment by edtownend** [comment]
Thanks, @mapio, that did the trick nicely for me.

**Comment by tmorehouse** [comment]
PR https://github.com/bootstrap-vue/bootstrap-vue/pull/2129updates the table documentation to remove reference of HTML from a formatter function.
