### ISSUE TITLE
Keyboard Navigation for Pagination Nav breaks when going to buttons not on initial render.

### ISSUE THREAD

**Issue by octoxan** [bootstrap-vue/bootstrap-vue#1891]
Running into a bit of an issue with the pagination-nav, that I didn't have with regular pagination.

When using keyboard navigation, all works as expected, until I get to the right so far that the button was not there during render.

I'm using router-link method of linkGen. Can keyboard nav up to page 4 without stopping and then I have to manually select 5 once it shows up. Anyone else ever ran into this?

I'm on version 2.0.0-rc.11

**Comment by octoxan** [comment]
Issue seems to only be when going up in numbers, not down.

Also, space works for regular pagination, but only enter for pagination nav.

Attached gif demoing issue.
 
![pagination](https://user-images.githubusercontent.com/4382195/41437292-05fe06cc-6ff2-11e8-8a44-8aabb05941ad.gif)

**Comment by octoxan** [comment]
Also just noticed that if I start from 1 and click the "Last Page" link which goes to 6, I can't click the "First Page" link unless I unfocus from the pagination-nav first. Every so often the first and last page buttons need roughly 3 clicks to work if the nav hasn't lost focus. No javascript errors in console.
![three-clicks](https://user-images.githubusercontent.com/4382195/41468678-cd41a3d4-7078-11e8-8bef-571eb4c04917.gif)

**Comment by xbold** [comment]
Having this issue also.

**Comment by octoxan** [comment]
Anyone find a solution to this? It looks like my route is actually changing, but it doesn't refilter the data and the pagination nav doesn't update. I've only noticed this with the first and last page buttons.

**Comment by octoxan** [comment]
```
<b-pagination-nav align="center" :link-gen="linkGen" :number-of-pages="trainers.last_page" v-model="currentTrainerPage" :use-router="true" v-if="trainers.last_page"></b-pagination-nav>

linkGen(pageNum) {
                return {
                    path: '/trainers/page/' + pageNum
                }
            },
```

This is all I'm doing, nothing fancy.

**Comment by octoxan** [comment]
![page-nav-events](https://user-images.githubusercontent.com/4382195/43587107-66c172bc-9637-11e8-9a03-2f79d1ff6051.gif)
Here is the dev tools. The first event fired is my first initial click on the pagination nav last button. It did update the url in the address bar but nothing else. On second click you can see that 3 events were fired instead of one.

**Comment by tmorehouse** [comment]
What is happening with Pagination Nav, is that navigation is occurring (i.e. clicking a link), which would normally load a new page,  In your case the page is not reloading, but we don't force focus the current page (as we assume the page will be re-rendered with a new page), as we don't want to steal focus (especially if the pagination is at the bottom of the page, or if there are two duplicate pagination-navs on the page ... which one should get focus)?

What we should really be doing is clearing the focus on pagination-nav when a new link is clicked. Basically `blur()` the component so that the document becomes the active element with focus, as regular link navigation does.

**Comment by tmorehouse** [comment]
PR #2299 addresses this by making pagination-nav behave like regular link page navigation by bluring the paginator and returning focus to the document.
