### ISSUE TITLE
Focus input on modal show

### ISSUE THREAD

**Issue by gabrielbuzziv** [bootstrap-vue/bootstrap-vue#19]
Hello, this is not a issue but a doubt

How can i focus the 1st input when modal show, i tried to do something on event show::modal is emitted but this way i need to check the modal is openning and i don't think this is the right way.

Sorry for the spam of questions

**Comment by mathlet0x** [comment]
For my part, i have an issue to open the modal : `Uncaught TypeError: $root.$emmit is not a function(…)

**Comment by riker09** [comment]
I'm not sure what you mean by "this way I need to check the modal is opening" but I solved this issue this way:

```javascript
  mounted: function () {
    let self = this
    this.$root.$on('shown::modal', function () {
      self.$refs.itemname.$el.focus()
    })
  }
```
I've assigned a ref attribute with value `itemname` to the first input field of my form so that I have a reference in `this.$refs`. Please note: I'm still new to Vue.js and haven't figured out a way how to traverse in vue components and their children.

**Comment by pi0** [comment]
I'm closing this issue as seems to be inactive. Please feel free to reopen if was needed :)
