### ISSUE TITLE
B-collapse accordion with shown and hidden events tiggers differently

### ISSUE THREAD

**Issue by kwame101** [bootstrap-vue/bootstrap-vue#1909]
I'm using this b-collapse accordion component with shown and hidden events. When I click the next sibling (siblings right onwards) events are triggered in @hidden then @shown but when i click previous siblings (siblings left onwards) events are triggered in @shown then @hidden. Is there any keep the events triggered in the same order. 

If anyone can help me, its kind of urgent for a project fix. Thanks

### Reproduction link here
[https://jsfiddle.net/o820kLwn/10/](https://jsfiddle.net/o820kLwn/10/)

**Comment by JBtje** [comment]
Interesting...

With a quick look in the code, I could not find the problem. However it has to do with the time it takes for the element to collapse. You are using "hidden" and "show". In total there are 4 events that are emitted [See here](https://github.com/bootstrap-vue/bootstrap-vue/blob/74df54ed2468d71cbf3ed789cef9b8001f15876e/src/components/collapse/collapse.js#L102-L129):

show
shown
hide
hidden

If you subscribe to show and "hide" instead of "hidden", the "hide" will *always* emit first.

See example:
https://jsfiddle.net/o820kLwn/15/
