### ISSUE TITLE
Basic form textarea isn't preserving typed text

### ISSUE THREAD

**Issue by kalvenschraut** [bootstrap-vue/bootstrap-vue#1915]
Issue is the same in chrome version 66.0.3359.117 and firefox 59.0.2. haven't tried any other versions.
Noticed the issue with the latest 2.0.0-rc.11 release but not sure if it occured before this release.
Using a Linux based OS though doubt that matters a whole lot.

Example: https://jsfiddle.net/kalvens/spm03avL/

**Comment by mikeaag** [comment]
I'm pretty new to Bootstrap Vue, but I believe this is happening because you need to put v-model on the textarea.

I've updated your example: https://jsfiddle.net/spm03avL/16/

**Comment by kalvenschraut** [comment]
v-model is no possible in my application as I am dynamically creating components with a render function. Instead I have to resort to events and and binding a variable to a value. A v-model should work the same exact way as a @input and :value on the component but it doesn't in https://jsfiddle.net/spm03avL/19/

**Comment by mosinve** [comment]
But, why you just don't use pure textarea?))

**Comment by kalvenschraut** [comment]
I mean I could, but this behavior doesn't seem intentional and I thought I would report it.

**Comment by Morpheu5** [comment]
I'm having the same issue (and probably a very similar use-case as @kalvenschraut's). It turns out this is a deliberate choice, as other `b-form` components seem to behave in the same way.

This is OK if one only uses `v-model`, but I need to use the input event to bubble the changes up through a hierarchy of components and update a data structure that is bound to a parent component. Think of a tree with each node managed by a component. Now, if child-to-parent flow was allows in Vue, this would be fine, but since this is not allowed, one needs to do this manually, somehow. I'm open to alternative suggestions.

Secondly, this contrasts with how plain html form controls behave. If I make a plain old `<textarea :value="myData" @input="myDataChanged" class="form-component" />`, I get the regular behaviour, and the bootstrap styling. This is not my preferred solution, though.
