### ISSUE TITLE
When a title is defined for the popover, content can not be longer than 10 characters

### ISSUE THREAD

**Issue by risc12** [bootstrap-vue/bootstrap-vue#193]
For some reason, when I use the popover and give it both the title and content attributes the popover acts really strange when the content contains more than 10 characters.

The popover gets a lenght till the top of the page and is completely white in this case.

**Comment by SirLamer** [comment]
I get this glitch too when I stress test it, though I don't think the limit is 10-characters. That is probably specific to your case. For instance, a longer title might limit you to shorter content.

I haven't been able to figure out what is causing it, I think it has more to do with Tether than bootstrap-vue.

**Comment by SirLamer** [comment]
So... I have experimented with this, I think that this is on Tether's side. Basically, the Tether popups are positioned with the style methods 'absoluteX' and 'absoluteY'. When we are dynamically editing the content and firing Tether's "reposition" method, these style values are being updated. Eventually, once the content field becomes full enough, it flips out and 'absoluteY' is changed to a negative values which sends it off the top of the viewport. This happens only if the Popover is exposed and visible while the content is being changed. If you feed it a large input set, or if you edit it dynamically only while it is not shown, the Tether behaves as expected.

We are commanding the reposition to occur on "next tick" per VueJS's reactivity model to avoid any issues related to the DOM having not rendered before commanding the reposition. I stressed this hard by experimentally switching to a "setTimeout"-induced delay to make sure the reposition is commanded several frames after the DOM refresh, but the effect is the same.

I will also look in to Bootstrap 4's CSS, to see if their CSS styling (which we're using) includes a bug which is inducing this but is only exposed during real-time reactive usage, which would be very rare with their jQuery implementation. However, I don't think that's the issue, not to mention that in any scenario it seems undesired for Tether to punt the element off the page like this anyway.

**Comment by pi0** [comment]
@SirLamer wow thanks for deep inspecting of problem. Just a suggestion, what if we observe popover's content all the time is visible? It may help us to 1- detect any changes in popover itself and resize tether 2- we may remove that event listeners and hide it when for any reason child is hidden.

**Comment by SirLamer** [comment]
Check the recent PR I submitted, which isn't meant to address this but changes how reactivity is implemented so is relevant (https://github.com/bootstrap-vue/bootstrap-vue/pull/230)

I am calling for the reposition every time the "updated()" lifecycle event is triggered. This makes it responsive to every damned thing that happens - not just content, but if the anchor show/hides, or if the anchor flies all over the screen because it's fun, or whatever. It's just a universal catch-all. Using 'updated()' means that it only fires when a change occurs. If we put it on a timer or something, which WOULD work I think, then it is just rapid firing and wasting CPU resources (which, in the modern world, really means wasting battery power). Not to mention, this would require an assumption about the client machine's frame rate which will sometimes be wrong (mine is 144 fps!) I personally and am not willing to just keep rapid-firing reposition() on a timer or on every frame to accommodate this edge case. I'd rather fix it.

If we do NOT call reposition, the Popover boxes resizes gracefully to accommodate the new content, however the position does not change so it will pull away from its anchor location, which is kinda worse.

**Comment by SirLamer** [comment]
One reason I suspect CSS is because it seems to occur only when there are four lines of text or greater. It seems like it is occuring when the display area exceed a specific height. This is very speculative at this time, though.

**Comment by pi0** [comment]
@SirLamer Is this problem exists anymore? I can't even reproduce it! If not, I think it is safe enough to close this issue.

**Comment by pi0** [comment]
Please Reopen if bug exists with steps to reproduce it.

**Comment by SirLamer** [comment]
It still exists, I cannot figure it out. I think the real issue is Tether, I have been trying to find a work-around. Tether development has stalled and Issues/PR are not getting attention.

**Comment by tmorehouse** [comment]
Would using the observe dom util help to detect changes in the content?

**Comment by tmorehouse** [comment]
No longer applicable in v1.0.0.beta.6
