### ISSUE TITLE
Script tag is not escaped when using :option="" in form-select

### ISSUE THREAD

**Issue by MerrySean** [bootstrap-vue/bootstrap-vue#1974]
I was trying to do some XSS in my project and I got some un-shown text. Which I found out that it was the cause of the script tag that was not escaped.. So I tried doing a v-for loop inside an `<option> `tag and use 
`{{  }}` (Double brackets) to escaped the script tag. I would like to make a pull request sadly bootstrap_vue is using a render less components (I don't really know but it's using render function) which I don't have much knowledge about. So I just submitted an Issue here.

by the way you can replicate the problem using the Live documentation on Bootstrap_vue site.

My browser: Opera
Operating System: Fedora LXDE

**Comment by Remigius2011** [comment]
same here - browser is chrome.

**Comment by Remigius2011** [comment]
this occurs in `b-form-radio-group` as well as in `b-form-select`. please note that this is a severe security problem!

**Comment by tmorehouse** [comment]
Could you provide an example bit of code or a JS Fiddle with a test case?

**Comment by Remigius2011** [comment]
Oh, this is quite easy - it even works interactively in the online documentation when you change the first option line in https://bootstrap-vue.js.org/docs/components/form-radio to the following:

>         { text: '\'"><img/src=x onerror="alert(1)">', value: 'first' },

or respectively in https://bootstrap-vue.js.org/docs/components/form-select :

>        { value: null, text: '\'"><img/src=x onerror="alert(1)">' },

(don't forget the backslash to escape the single quote). This shows a dialog box, which is harmless. Obviously, this should not happen, it should show the text, which is quite useless unless it is treated as executable code.

**Comment by Remigius2011** [comment]
@tmorehouse have you been able to reproduce the problem or do you need additional assistence?

**Comment by Remigius2011** [comment]
@tmorehouse I have had a look at the source code of `form-select`. I think, the problem is in line 24 of `b-form-select.js`, which is currently:

`
        domProps: { innerHTML: option.text, value: option.value }
`

this means, the (untrusted) data contained in `option.text` is directly used as innerHTML, which allows to inject JavaScript code using the payload I have supplied above. Assuming the text is fed from a database that contains user entries, a malicious user is able to insert code that is executed in another user's browser. The line should imho be something like:

`
        domProps: { textContent: option.text, value: option.value }
`

 see also https://github.com/vuejs/vue/blob/master/src/platforms/web/server/modules/dom-props.js.

The same applies to `form-radio`, see line 35 of `form-radio-group.js`:

`
  [h('span', { domProps: { innerHTML: option.text } })]
`

should imho be:

`
  [h('span', { domProps: { textContent: option.text } })]
`

I havent checked whether other components are affected, too, but any use of `innerHTML` is suspicious - only trusted content should go in there at any rate.

**Comment by Remigius2011** [comment]
imho: _**nope!**_ app developers would then end up doubling their code for sanitizing all texts...

Seriously, see e.g. the description of v-html in the vuejs doc: https://vuejs.org/v2/guide/syntax.html#Raw-HTML

If you have a property called `options.text` you are alluding this is interpreted as text and hence passed to a text-like property (`domProps.textContent` in this case). Otherwise it should be called `options.html` (which could exist simultaneously and be passed into `innerHTML`. Otherwise, this should be clearly documented to avoid security risks (I assume more than 90% of app developers who pass in user input will **not** sanitize it and have a security vulnerability in their app). Please feel free to consult resources of the security folklore to make an informed decision - but at least add some documentation that the property `options.text` is not secure (i.e. treated as HTML - similar to the remarks for `v-html`) and explicit options should be used instead if the content is untrusted (e.g. `select` controls filled from database content and/or user input).

**Comment by PhilippeWCS** [comment]
I confirm this behavior, i test with this options.text `<iframe id="inlineFrameExample" src="https://www.free.fr"></iframe>` and the website is called when the page is displayed.

**Comment by Remigius2011** [comment]
@PhilippeWCS , effectively you can have any javscript code executed on behalf of an innocent user - including but not limited to executing XHR requests - without this being noticed (just leave out the `alert`).

See also here (link to the documentation of vue-i18n that warns about using `v-html`): https://kazupon.github.io/vue-i18n/guide/formatting.html

In contrast, vue-bootstrap just treats text as html without even warning the developers.

**Comment by CAR7OGRAPH3R** [comment]
Hi @tmorehouse 

Apologies for commenting on an issue that has already been closed - please let me know if you would prefer a new issue be raised instead.

An XSS vulnerability was recently found in one of our applications that uses a `b-form-select` element populated from user supplied data ( as mentioned above ). 

I have simplified and replicated the scenario ( that does not use `<script>` tags ) [here](https://jsfiddle.net/k3rtjdyv). 

When speaking with the developers ( who admit the validation of this data can and will be improved ), their understanding was that the data would only ever be treated as text, not markup.

OWASP [recommend](https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet#GUIDELINE_.234_-_Avoid_sending_untrusted_data_into_HTML_rendering_methods) never providing untrusted data to `innerHTML`, and to use `textContent` [instead](https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet#RULE_.236_-_Populate_the_DOM_using_safe_JavaScript_functions_or_properties) - would this be possible?

**Comment by Remigius2011** [comment]
@CAR7OGRAPH3R  see conversation above - this was exactly my suggestion - unfortunately to no avail. the work-around is to use `<b-form-select>{{ my content goes here }}</b-form-select>`.

note also that other controls may be affected, too, which has been established for `b-form-radio-group`, but there may be others, which have not been investigated yet. therefore it is imho strongly advisable to perform a thourough vulnerability testing whern uising this lib.

imho sanitizing html is a difficult task to say the least. there are many ways to circumvent sanitizing, some of which are easy to be found, like:

https://support.portswigger.net/customer/portal/articles/2590821-xss-beating-html-sanitizing-filters
https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

but there are numerous others. it is not only necessary to handle each in the sanitizing code, but also (recurrently!) in testing, which is a big effort and also error prone. therefore i prefer the easy and deterministic method of not treating untrusted content as html. period.

there are sources on handling untrusted content (with some hints on esacping html), like:

https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by jpicton** [comment]
@tmorehouse as outlined above, the merged "fix" for this issue is insufficient for preventing XSS. This issue has caught us out and introduced a security flaw in our application that was only just recently identified.

Has anybody thought to report this vulnerability to the NPM security advisory yet? It would aid others who are unwittingly using a vulnerable version of bootstrap-vue.

**Comment by pi0** [comment]
Other than [clearification letter](https://gist.github.com/pi0/674d49d5f1c2ccfe20d3b1e29ae7b497) I've create two PRs (Hotfix + Fix for next RC). Still talking with the team that if it makes sense to avoid using HTML everywhere or not. For inputs and forms, this makes sense. But for areas like modal, it is more convenient for users passing HTML.

**Comment by Remigius2011** [comment]
@pi0 imho the solution could be to support both text *and* html, but to avoid developers to use html inadvertently. vue itself follows this approach by providing both `v-text` and `v-html` properties and a warning not to pass untrusted content into `v-html` (see one of my comments above). in a similar way, when passing an `options` array, if passing items as:

    { value: 'a', text: 'This is First option' }

the text should be treated as text (i.e. passed the dom as `domProps: { textContent: option.text, value: option.value }`) whereas html could be provided like:

    { value: 'a', html: 'This is First <b>HTML</b> option' }

and passed to the dom as `domProps: { innerHTML: option.text, value: option.value }`. even for people who don't read warnings, there is at least a chance for them to be aware that they are passing html into the control if the property is named `html`.

**Comment by pi0** [comment]
@Remigius2011 We are going to advise users using slots if need passing HTML. Does it look good to you?

**Comment by Remigius2011** [comment]
@pi0 i have already changed my code to use slots after discovering the vulnerabilities in my app. so actually it is up to you and the team to decide on whether to minimize changes in `bootstrap-vue` or the likelyhood of other developers to introduce vulnerabilities in her/his app (i would opt for the latter if i were to decide).

i agree with your point in the clarification letter that separating trusted from untrusted input is not (and cannot be) the task of `bootstrap-vue` (and hence any html sanitization - including removal of `<script>` tags, which is neither necessary nor sufficient - can be dropped), but ***providing separate channels*** for trusted (html) and untrusted (text) data is important, and it vould avoid confusion and wrong expectations if the respective properties were named and documented accordingly. but clearly, the two channels are already there: the `text` property for *trusted html* and the slot for *untrusted text*.
