### ISSUE TITLE
b-table and filtered event fired when no filter

### ISSUE THREAD

**Issue by ghenry** [bootstrap-vue/bootstrap-vue#1991]
Hi all,

Here's the first load of a b-table component with events. With filter set to null as per the docs example, why is it fired?

Thanks.
![screenshot from 2018-08-08 20-28-47](https://user-images.githubusercontent.com/159608/43860171-c37edcfc-9b4a-11e8-950d-dd252eeb381f.png)

**Comment by ghenry** [comment]
Any ideas?

**Comment by tmorehouse** [comment]
b-table keeps a copy of the items that are filtered (to check reactivity), and watches for changes in that copy in order to trigger the filtered event.

that variable changes on the first render of the table (as items are not known until rendering starts).  This triggers the extra filtered event at the beginning.

**Comment by ghenry** [comment]
Thanks.
