### ISSUE TITLE
[Table component] Cannot use special character for table field

### ISSUE THREAD

**Issue by kristijan97** [bootstrap-vue/bootstrap-vue#2049]
I cannot use a special character in table header field. Here is the very simple code:

```
<b-table :fields="tableFields" :items="data"></b-table>
...
data: () => ({
        data: [],
        tableFields: [ '#', 'column1', 'column2' ]
    }),
```

This code will not display first column (it will be displayed, but without text)

**Comment by tmorehouse** [comment]
the `#`  character is an illegal character when used as a property key in JavaScript.

![image](https://user-images.githubusercontent.com/2781561/47545454-b400b380-d8c2-11e8-995b-111dd72c5627.png)

You will need to pre-massage your data to change the key to a supported string, and then use the array of objects format for defining your field names so that you can specify the '#' as the column heading,
