### ISSUE TITLE
Doc Feature Update Vue-CLI v3

### ISSUE THREAD

**Issue by BenHayat** [bootstrap-vue/bootstrap-vue#2096]
Hello Team;

Could you please update your Installation doc related to using Vue CLI Version 3 and anything related to CLI V3?
Currently it shows V2 and I want to make sure BS-Vue works properly with CLI 3

Thanks!

**Comment by fadedbee** [comment]
I'm just starting to use Vue (vue-cli v3) and would like to use bootstrap-vue, but can't because of this issue.

Do I actually need bootstrap-vue to use bootstrap with Vue?

How can I use it with vue-cli v3 if I need it?

Or should I use vue-cli v2 and follow those instructions instead.  (The generated project looks to have an entirely different structure, from my tests.)

**Comment by tedberg** [comment]
I am using vue-cli 3 with vue-bootstrap rc.11 without issue.  Only thing I found missing in docs was regarding importing individual components instead of the whole lib.  The docs:  [https://bootstrap-vue.js.org/docs/](https://bootstrap-vue.js.org/docs/) show how to modify a webpack config, but don't mention vue.config.js.  I found the necessary fix here:  [https://github.com/Justineo/vue-awesome#importing-the-souce-version](https://github.com/Justineo/vue-awesome#importing-the-souce-version).

Needed is a block like:
`
module.exports = {
  transpileDependencies: [
    /bootstrap-vue/
  ]
}`

**Comment by tmorehouse** [comment]
We're looking for someone to help out adding a Vue CLI v3 section to the getting started page, and maybe reference section.

**Comment by TitanFighter** [comment]
Also with `vue-cli v3` it would be useful to use `tree shaking` feature. In this case no need to import individual components from `bootstrap-vue`, so just 
```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
Vue.use(BootstrapVue);


```

 as Webpack can do it itself.

In `vue.config.js`:
```
const path = require('path');

module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          include: path.resolve('node_modules', 'bootstrap-vue'),
          sideEffects: ["*.css"],  // means false, except *.css files
        }
      ]
    }
  }
};
```
