### ISSUE TITLE
b-modal preventDefault() in sweetalert callback

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#2141]
When using the `@hide="action"` callback in combination with Sweetalert I cannot get the modal to stay active after clicking "Nee".
Here's the code in the `action` method.

```
async action(event) {
                console.log(event);

                if (event && event.isOK !== 'ok') {
                    await this.$swal({
                        title:              'Bevestig verwijderen bewerkingen',
                        text:               'Weet je zeker dat je de bewerkte relatie niet op wilt slaan?',
                        type:               'warning',
                        showCancelButton:   true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor:  '#d33',
                        confirmButtonText:  'Ja',
                        cancelButtonText:   'Nee',
                    }).then((result) => {
                        if (result && result.dismiss !== 'cancel') {
                            event.preventDefault();
                        }
                    });
                }
            },
```

Any idea on how I can keep the modal active while using Sweetalert?

**Comment by tmorehouse** [comment]
I'm not familliar with sweetalert.

But maybe you should check for `event.trigger === 'ok'` istead of `.isOK` (I think that is a Boolean, not a string)

Also, BvEvent doesn't keep track of listeners (unlike native events objects), so it assumes it will be called synchronously rather than async.  You may want to use your own ok button and handle click directly, and if it needs to be cancelled don't run the .hide('ok') method.

**Comment by CrixuAMG** [comment]
Thank you for your response.

`event.isOK` is actually a string, having the same value as the trigger, which I'll switch to.
I'll give the custom buttons a try, and then hide the modal by emitting `hide`.
