### ISSUE TITLE
Updating existing rows.

### ISSUE THREAD

**Issue by hifall** [bootstrap-vue/bootstrap-vue#2144]
I have a b-table, inside each of whose rows there is a field called "age" indicating how long ago the record was created. Obviously, this changes as time elapses. Is it possible to update these rows periodically, so that they show the correct age for each record?

For example, say I create a record on "1pm", and after 10 minutes, I'd like to update the age field to 10 mins; and after 20 minutes, update it to 20 mins.

Thanks!

**Comment by tmorehouse** [comment]
You would need to use a `setTimeout` or `setInterval` to periodically update refresh your data (i.e. running a new fetch, or running a loop through your data array to adjust the age column).

The other option, still using a `setTimeout` or `setInterval` to force b-table to update.  Get a reference to your `b-table` (by setting a `ref-"somename"`, and then use the Vue built in instance method `this.$refrs.somename.$forceUpdate()` which will force the `b-table` component to re-render the table. See https://vuejs.org/v2/api/#vm-forceUpdate

**Comment by tmorehouse** [comment]
Vue's reactivity only goes so deep when it comes to objects or arrays (or arrays of objects).

If you have your items in, say `this.items` (an array of objects), changes to the objects within that array may not be detected by Vue's reactivity (observation) system.  You may need to use this.$set(...)` to update a nested object value.

If you are using a field formatter function  or soped slot to convert a date value (or date serial) to a "relative" value (i.e a "few seconds ago", "10 minutes ado", "one day ago", etc), and want taht relative value to update, you need to find something hat can trigger a refresh/change in the reactive data (or computed property).

You need something to trigger Vue so that it knows that the data has changed and needs to re-render the data.  I.e. the date function is not reactive, even if you place it in a computed property.

Maybe store the current time in a data variable, and then use a `setInterval ` to periodically update taht value with the current time.  And then in your scoped slot, do your relative date function compared to not Date.now(), but to that data objecting containing the value set by the `setInterval` routine.  Vue will detect that the date value stored in data has updated, and will hen force all the scoped slots to re-compute, without causing the table to refresh.

See https://vuejs.org/v2/guide/reactivity.html for details on how Vue track reactive changes and what things it cannot react to.

**Comment by hifall** [comment]
Thank you so much for this detailed explanation! I guess I don't really understand Vue's reactivity. Will follow your suggestion and dive into that later.

**Comment by tmorehouse** [comment]
And I wouldn't set your interval too low (too fast), as that would cause many updates to happen to the table, although vue is pretty good at only updating the parts of the rendered DOM(patching).  But in order to do so it has to re-render the virtual shadow DOM (called vNodes), and then compare that to the rendered table DOM elements, and "patch" the elements as needed.

500 to 1000ms is probably fast enough.

**Comment by tmorehouse** [comment]
start the setInterval timer in the `mounted()` hook. Keep a reference to the timer ID returned by `setInterval` in data(), so that you can cancel the timer in the `beforeDestroy()` hook.

**Comment by PhilWaldmann** [comment]
Why not use [vue-timeago](https://github.com/egoist/vue-timeago) inside a custom data renderer?

**Comment by tmorehouse** [comment]
There are several timer addons/plugins that could be used as well.

**Comment by hifall** [comment]
@PhilWaldmann, thanks for mentioning that. It saves me a lot of headache!

**Comment by slidenerd** [comment]
Highly related to this question, how do I update the table rows from a websocket, essentially I am trying to build a website like coinmarketcap that displays coin prices and I have the array of rows with me but with each tick the prices change. Going by your above statement that Vue reactivity only goes so far, can I maintain the rows as objects because it will be much easier to update "BTC" than to search its index in an array and then update it. The updates are supposed to happen every 1s or even faster in some cases, some direction would be super appreciated
