### ISSUE TITLE
Tab title slot is not reactive

### ISSUE THREAD

**Issue by jackmu95** [bootstrap-vue/bootstrap-vue#2148]
**DISCLAIMER:**
This issue is a duplicate but meant to be the one place to go to find all information about this bug and a possible workaround until it gets fixed.

As @emanuelmutschlechner mentioned:
> Currently the reactivity of tabs is limited to changes on the element `<b-tab>`.
> Observation of the DOM does not include subtree changes:

https://github.com/bootstrap-vue/bootstrap-vue/blob/ac7dfbfdd5c48fef44f3018bf101276f76dd226c/src/components/tabs/tabs.js#L413-L419

> A current workaround is to set a prop on <b-tab>. This will trigger updateTabs and rerender the tab title slot.

**See this example for a live demo of the issue and the workaround:**
https://codesandbox.io/s/l9qp2xowkz

Replaces: #1397, #1677, #1830, #1871, #2065

**Comment by tmorehouse** [comment]
I'm working on something that _may_ make the tab title reactive, and make the coding/communication a bit better inside between the b-tabs and b-tab (i.e notifying when a tab has been inserted or has become invisible, etc)

Doing a few proof of concept mock-ups just to work the bugs out (and make sure everything is reactive in the right places)

**Comment by jackmu95** [comment]
@tmorehouse Added missing reference to #1871.

**Comment by tmorehouse** [comment]
I've been working on making popovers/tooltips "better", (currently we use DOM re-targetting/moves to bring reactive content into another element, which goes against Vue's philosophy) And on how to render reactive content into another document location.  With render functions, and dynamic components that can be mounted anywhere in the document, we can take advantage of this feature in render functions to render and mount content in other areas of the document, rather than inside the component it exists in. It is nifty stuff, and not-so-obvious (not until a thorough reading of Vue's source code)

**Comment by jackmu95** [comment]
@tmorehouse Sounds promising. Looking forward to see your changes.

I've learned a lot about Vue by following this project evolve.

**Comment by emanuelmutschlechner** [comment]
@tmorehouse do you know [portal-vue](https://github.com/LinusBorg/portal-vue)? If pulling it in as a dependency isn't an option, you could take a look at the source code. Hope it helps

**Comment by tmorehouse** [comment]
Yeah, I've peeked at it before (its coded by a guy from the Vue team).  He's doing a bit more funky stuff with source and destination components, and I don't think we need to go that deep.  But he does have some nifty things going on in there.
