### ISSUE TITLE
[b-radio-input] [v-model] Cannot get data from input

### ISSUE THREAD

**Issue by kawazoe** [bootstrap-vue/bootstrap-vue#2181]
# Component
```
<template>
  <table>
    <tr>
      <td><b-form-radio :value="42" name="foo" v-model="radio"></b-form-radio></td>
      <td>...</td>
    </tr>
  </table>
</template>

<script>
export default {
  name: 'test',
  computed: {
    radio: {
      get() {
        console.log('radio get');
        return 42;
      },
      set(value) {
        console.log('radio set', value);
      },
    },
  },
};
</script>
```

# Description
Some times, like when layouting radio buttons in a `table`, we cannot use `b-form-radio-button-group` to manage a group of radios for us. This is because using `<tr is="b-form-radio-button-group" ...>` will render out as a `div` instead of a `tr`. No matter if this is a limitation/bug in the group component or not, I think we can all agree that having multiple options is great. In these cases, it is very useful to be able to bind a model directly to a named `b-form-radio`.

In this code sample, the setter for the `radio` computed property will *never* get called and fail silently even though the model property is defined and specifies that the `change` event should trigger `v-model`.

# Theory
From my understanding, `v-model` essentially rewrites the bindings to be `:value="radio" @event="e => radio = e.target.value"`. In your case, because of your model property, `value` would be `checked` and `event` would be `changed` which is correct.

Where I think this code breaks is because `v-model` assumes that the change event will be an `Event` object. Binding directly to `:change="log($event)"` shows that the `$event` is instead the value of the radio input. In my sample, that would be `42`.

# Additional Info
- Operating System: Windows 10 (1803)
- Browser: Chrome (69)
- Bootstrap-Vue version: 4.1.3

**Comment by tmorehouse** [comment]
currently radios are only supoorted inside radio groups, but i think we should be able to account for this... but also note that all the radios bound to the same v-model would need to have the same name attribute so that users of assistive tecnologies know that they control one value.

**Comment by tmorehouse** [comment]
The v-model actually uses the `input` event for `b-form-radio` and `b-form-checkbox` to update the v-model, while the change event is fired when the input changes state due to user interaction.

Both custom events receive one argument which is the new value of the v-model.

When listening on change for a single checkbox, it sends the checked (or unchecked/null) value of the checkbox (where as the input event sends the entire v-model of any multiple bound checkboxes, i.e. array).

Remember that checkboxes and radios are a custom component (with wrapper elements, etc), and do not send native versions of the `input` or `change` events, unlike binding change/input to a native checkbox/radio element.

The current `dev` branch has updated versions of radios/checkboxes, and you should not have any issues binding multiple `<b-form-radio>` components to a single v-model, as long as each radio has a unique `value` (without the need for a `b-form-radio-group`)
