### ISSUE TITLE
<b-popover>: button\link must be clicked once (instead of twice) to close popover which is opened inside mounted()

### ISSUE THREAD

**Issue by TitanFighter** [bootstrap-vue/bootstrap-vue#2187]
In order to close popover which is opened by the code:
```
  mounted() {
    this.$nextTick(function() {
      this.$root.$emit("bv::show::popover", "popoverBtn");
      this.$root.$emit("bv::show::popover", "popoverLink");
    });
  }
```

right now it is necessary to click a button/link twice, however popover should be closed just on a single click. All the rest subsequent open/close clicks work as expected.

OS: Ubuntu 18.04 64;
Browsers: Chrome 70.0.3538.102 (Official Build) (64-bit) + Firefox 63.0 (64-bit)
Bootstrap-vue: v2.0.0-rc.11

[DEMO](https://codesandbox.io/s/my3lx04o4x)

**Comment by psimyn** [comment]
Triggering the popover programatically uses [`doShow`](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/tooltip.class.js#L776) which doesn't set activeTrigger.

The activeTrigger _is_ set in the [toggle](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/tooltip.class.js#L247) function triggered by the click

We can't add triggers when emitting the event, as we don't know which trigger they'll use to close the popper if it has more than just `click`.

Possibly need some kind of flag to indicate the popper has been shown/hidden programatically.

**Comment by tmorehouse** [comment]
in bootstrap V4 native code, if a popover or tooltip is opened programmatically,  it is called a manual trigger, and is stored in the active triggers object. and in order to close the popover or tooltip, *all* active triggers have to be cleared (i.e. click, focus, hover, as well as manual). bootstrap-vue is similar, but we allow manual triggers to be ignored (allowing the user to close it, although they need to trigger the element first to activate their trigger, and then they clear it with the next trigger (we don't store the manual trigger in the active triggers object)

it might be possible for us to first check to see of the tip is opened and there are no triggers in the trigger object, then we just close the tip.

**Comment by tmorehouse** [comment]
but that might break the always showing (non closable) tip or popover.

**Comment by tmorehouse** [comment]
Another option, which might be a compromise is when the tooltip or popover is initially shown on mount (or manually triggered via events or the show prop) would be to set the _first_ listed trigger in the `triggers` as active.

i.e. if the triggers are `click hover` and the tooltip is triggered manually, then we would set `click` as the active trigger, and the user would need to click the tooltip to close it.

If the triggers were specified as `hover click` then the user would need to hover over and out to close the tooltip.

This might be a breaking change for some that want the tooltip to stay open until closed, but they could set the `disabled` prop to true once the tip has opened, which would prevent it from closing until disabled is false.

**Comment by tmorehouse** [comment]
Since this would be quite the breaking change, and rub against the grain of Bootstrap v4 behaviour, I think we should close this issue until Bootstrap V5 is released
