### ISSUE TITLE
Navbar: navbar-expand{-sm|-md|-lg|-xl}

### ISSUE THREAD

**Issue by jchiotaka** [bootstrap-vue/bootstrap-vue#2209]
There is an issue with parameter `toggleable` in navbar.js

More specifically:
`['navbar-expand-${breakpoint}']: props.toggleable !== false,`

This removes completely the `navbar-expand` class from the element when `togglable === false` *but*, according to Bootstrap documentation it should be `navbar-expand` (no breakpoint) in order for the navbar to be expanded always.

I solve it for now by adding `class="navbar-expand"` at the <b-navbar /> element

**Comment by tmorehouse** [comment]
I think I may habe a solution for this (I.e. if `toggleable===true`, then always collapse).

we also have, in the works,  an option to auto-detect the collapse and toggler button inside the navbar so that one doesnt need to set an id on the collapse and target on the toggler, nor needing to set the `is-nav flag on to collapse.
