### ISSUE TITLE
[b-table] unexpected input event triggered by reactive data used in triggered method

### ISSUE THREAD

**Issue by ryleyb** [bootstrap-vue/bootstrap-vue#2231]
I'm seeing a case where the `@input` event is being triggered by reactive data in the method that is called.  I attach `@input="myMethod"` to a b-table.  In `myMethod()` I reference a piece of data in my app.  Now, if **my** data changes, the `@input` event is triggered.  I expect that `@input` should trigger when the data changes in the b-table.  Not in any other case, regardless of what my method does.

See: https://jsfiddle.net/vbeyfhjr/

This is the expected behaviour, https://jsfiddle.net/bLmr4zuo/  you'll have to watch the console as you click the "Remove Item" button to see that it triggers once per change to the actual table data.

**Comment by tmorehouse** [comment]
Whenever b-table render function is called, it sends out an input event to update the v-model.

I suspect we'll have to do a `looseEquals` check before emitting the input event.

**Comment by tmorehouse** [comment]
What is happening is that any time the parent component of b-table is updated (even if the props for b-table haven't changed), is that Vue calls the render function of b-table (and compares the generated vDom to the actual dom in document to see if the dom needs patching).  Since the v-model is updated during render, This is why you are seeing the `input` event trigger, even when data/props are not changed.

One of two things we could do to change this:
- use a `looseEqual` watcher (which can be computationally intensive if nothing changes) on `computedItems` (the array that b-table renders)
- cache the rendered vDom and only re-render if any of the b-table props change (basically watching all props), and if any prop changes, create a new cached vDom, although vue may complain that we are re-using the same rendered vNodes).  This could also improve general performance ot b-table, but make the implementation more complex

**Comment by ryleyb** [comment]
What's the connection between touching data in the called method from the `input` event and b-table getting re-rendered?  I can change the parent component of b-table a whole bunch and it doesn't emit an `input` event until I add something in there that uses my data.

**Comment by tmorehouse** [comment]
What happens is that Vue doesn;t know if you are using methods (as compared to data or computed props) inside a render function or not.  so it re-renders the vDom and compares to the actual dom before making any patches.

Inside be table, we run several methods that cant be easily converted to cacheable computed props (i.e. for pulling style/formatters out for custom cell rendering).

Whenever a parent component "updates" state, it causes all children to re-render the vDom.  If the vDom is based on cached computed props or data, then the render will be fast.  Then vue compares all vNodes returned with the actual dom, and only updates those elements that need updating.

Render functions (what we use internally, and what Vue compiles templates into) are just pure functions, which vue calls each time the component needs updating.  See https://vuejs.org/v2/guide/render-function.html#Template-Compilation

```html
<table>
  <tr v-for="(row, RowIdx) in rows" :key="rowIdx">
    <td v-for="(cell, cellIdx) in row" :key="cellIdx">
      {{ cell }}
    </td>
  </tr>
</table>
```
becomes

```js
function render() {
  return this._c(
    'table',
    this._l(
      this.rows,
      function(row, RowIdx){
        return this._c(
          'tr',
          { key: rowIdx },
          this._l(
            row,
            function(cell, cellIdx){
              return this._c(
                'td',
                { key: cellIdx },
                [ this._v(String(cell)) ]
              )
            }
          )
        )
      }
    )
  )
}
```

One would think that Vue would know not to re-run the render function of the props feeding a component don't change, but what if a prop references external data or a store?  It doesn't have an easy way to register reactivity in those cases.  So the end result is render in child components is called every time a parent updates its state. the rendered dom elements don't necessarily update, but the vDom is thrown out each time and re generated.

I'm sure we can alter how the v-model `input` event is emitted, rather than running it withinside the computed prop that generates the data.

I am curious of your use case of listening to the `input` event, which was only originally intended for ensuring the v-model is in sync with the displayed rows.

**Comment by ryleyb** [comment]
Thanks for the detailed reply, very enlightening!

I don't think I'm using the `input` event in a valid way, but here it is in two parts (two different uses):

A year or so ago I was looking for a marker to tell me when the table was "ready".  I'm using infinite scroll rather than pagination, i.e when they scroll to the bottom of the table I trigger the first request for new data.  Once the new data arrives, it gets added to the table's data component, but there's a gap where technically I could tell the infinite-scroll component that the data is loaded and we're ready for the next scroll, but because b-table hasn't actually updated the DOM, it will instantly trigger another infinite-scroll event.  I had to find some sort of marker in b-table to tell me when it's done rendering the data, and `input` was the best I could find at the time.

More recently, I needed to attach a 2nd header row to a b-table.  See this SO for details: https://stackoverflow.com/q/51504745/312208

That's what actually got me wondering about `input` being triggered multiple times - I was fixing an aspect of the header row and was surprised that it was getting called when some reactive data I started using in the `tableLoaded` function changed.

**Comment by tmorehouse** [comment]
I think I can add in a deep watcher on the computed items (the computed prop that generates the values for display), which could then trigger the input event (update the v-model), so the event would fire only on changes to the resultant displayed values (including any unshown field from those rows), rather than whenever the table re-renders.  I'm not sure how fast deep watchers are to react, but it would definitely reduce the number of emits occuring.

**Comment by tmorehouse** [comment]
For the second header option, we currently offer a fixed top row slot, which is rendered at the top of `tbody`, but I had been contemplating adding  an option to render that as a second row in `thead` instead (or adding another slot for that, basically like the current scoped slots for `HEAD_*`, but maybe `HEAD2_*`.  I know some users would like to be able to have a row for adding either selects or text inputs for filtering per column, rather than embedding that control into the header row.  It could be feild scoped, or an empty `TR` without any `TH`s

**Comment by ryleyb** [comment]
Interesting on both accounts!  

For the second case, I need the `tr` **above** the standard head rows.  It's used to identify groups of columns in the built-in head rows (i.e. I'm using `colspan`s).  I realize this is probably too niche to deserve a spot in the component.

**Comment by tmorehouse** [comment]
Hmm.. it would only be a few lines of code checking for an additional scoped slot and rendering a an empty `<TR>` in the head with the contents of the scoped lot (it would be up the user to ensure there are enough `td`/`th` elements to span across the number of fields (this is basically what we do for the fixed top row slot), and could make one for below the normal header row (so two choices). Or we just provide a slot that doesn't render any TR, and leave it up to the user to render as many TRs in the head as they want.. Although if the user is not careful they could break the layout.

Another option, which might be flexible with more control, would be to allow fields array to be nested...

I.e. an array of objects where the key of a "column" points to an array of sub columns instead of a string name, and the fields in htat sub array would be rendered underneath as sub-columns (i.e. the parent field def becomes the colspan def with span based on the number of fields it contains.  Fields without nested subfields would be rendered with a row-span equal to the depth.  If someone wants a column to have tow headings and not be spanned, they would just return an array of one field def.  Sorting features would only ever be applied to the lowest "leaf" field.

I kind of like that last idea better.  It adds a bit more complexity at calculating the header, but that information could be pre processed in a computedProp (like fields is today) to cache the results.

Generating the scoped slots for it might be a bit convoluted, but slot names can have characters like `[` and `]` which would be used to denote the position in the header (i,.e. in array notation, or using a unique key on all levels for "field" names `HEAD[colspanA][age]`).  It would require deprecating the `HEAD_*` naming convention (but we could easily fallback to that if the fields array is not nested).

**Comment by tmorehouse** [comment]
But for now, I'm just going to fix how the v-model `input` event is fired.

**Comment by tmorehouse** [comment]
Something like this for the fields definition, supporting multiple header rows, cols pans and row spans:
```js
fields = [
  { key: 'age', label: 'Age' }, // spans 2 rows, 1 column, data rendered for key 'age'
  {
    key: 'name',  // spans 2 cols, 1 row, no data rows for this `key`
    label: 'Name'
    fields: [
      // becomes two columns under "Name"
      // data rows rendered for keys 'first_name' and last name'
      { key: 'first_anme', label: 'First' },
      { key: 'last_name', label: 'Last' }
    ]
  },
  {
     key: 'foo'  // spans 1 row, 1 col, no data rendered for key 'foo'
     label: 'Foo'
     fields: [
      // spans 1 col 1 row beneath key 'foo', renders data for fields 'bar'
      { key: 'bar', label: 'Bar' }
     ]
]
```

Scoped header slots would be referenced in _array_ notation named slots:
- `HEAD[age]`
- `HEAD[name][first]`
- `HEAD[name][last]`
- `HEAD[bar]`

Or we could forgo the colspan keys, assuming all keys are unique regardless of depth.  We would just have to scan the key defs and barf out an error when duplicate keys are found.   I do like the slot naming convention of `HEAD[key]` compared to our current `HEAD_key` notation.

**Comment by tmorehouse** [comment]
What is nice, is that we could auto generate the colspan/rowspan structure if no fields array is provided, and the data has nested values (object or array)

**Comment by ryleyb** [comment]
That does seem quite reasonable, and I think the naming is indeed much
clearer.

Will sorting cause any issues here?  It's not entirely clear to me what
will happen if a top level header is sortable.

**Comment by ryleyb** [comment]
Oh sorry, you got that earlier - sorting only on leaf nodes.

**Comment by tmorehouse** [comment]
Yeah, it would be too complex to sort on keys that are not leaf keys (although not impossible)... But I would leave that for a future consideration.

**Comment by ryleyb** [comment]
Hey, thanks for looking into this and taking the time to explain it to me.  Much appreciated!
