### ISSUE TITLE
Roadmap for new components (not an issue)

### ISSUE THREAD

**Issue by milenon** [bootstrap-vue/bootstrap-vue#224]
First I want to thank you for your work!

...and then to ask you do you have some roadmap about new components/features, where will be visible what's cooking now and what's to come? I'm asking because I'm particularly interested in date/time pickers and switches and if you have no plans implementing them I want to look for alternatives.

In your current roadmap( https://github.com/bootstrap-vue/bootstrap-vue/projects/1 ) there are mostly bugs.

**Comment by pi0** [comment]
@milenon Hi. thanks for your interest in feature of this project. Actually I (and other devs) think that maybe it could be better to keep `bootstrap-vue` as minimal as possible and try to have best quality standard bootstrap components. This is for keeping dists as clean and small as possible. Anyway i'm okay with add some *extra* components bundled in a different js. (Specially about data/time pickets and a more feature rich table component) So we can for example include `bootstrap-vue/dist/bootstrap-vue.ex` to have more components like `<b-date-picker>` :)) 

cc @bootstrap-vue/dev What's your idea?

**Comment by SirLamer** [comment]
Milenon, if I may suggest, export to spreadsheet is best handled server-side and so is external to the function of this client-side package. It can be a big job and you have to assume that your user is connecting on their free crappy cell phone.

For my project, one trick I use is that I maintain two separate table templates for each table - one meant for rendering, one meant for spreadsheet export. Though inefficient from a design perspective, I chose this way because there are often subtle differences in what you want to present in each case. I am using this Package in Laravel, using the Blade templating engine:
https://github.com/PHPOffice/PHPExcel

So, you can just shovel a HTML table in to this package and it will produce a spreadsheet, which makes templating easy but isn't the most efficient programatically. It also allows you to just feed it a PHP array or other techniques if you want to get fancy. For me, I wanted quick changes which look similar to the web app rendering, so I am using HTML tables to spreadsheet.

**Comment by SirLamer** [comment]
The package should just do Bootstrap things but in Vue. It should not exceed Bootstrap's functionality except for where it makes sense because of the marginal resource/effort cost on account of the introduction of Vue. The main example here is providing reactivity to property inputs, which doesn't happen quite as magically with Bootstrap and jQuery. Extra fun things could be in a separate package which pulls this in as a dependency.

The key concept here is _separation of concerns_. If this package tries to do everything well, then it will do nothing well. And it will be bloated.

My own little toy project is an example of this, which depends on Popover.
https://github.com/SirLamer/click-confirm

I use this package for a date picker in my project:
https://github.com/vuwe/vue-flatpickr

**Comment by mosinve** [comment]
Fully agree with @SirLamer. Main purpose of this project is to extend Bootstrap 4 components with reactivity) Additional features can take a place,  but in separate project).

**Comment by pi0** [comment]
Reasonable! I Agree Too :))
