### ISSUE TITLE
Export table data functionality

### ISSUE THREAD

**Issue by coderabsolute** [bootstrap-vue/bootstrap-vue#225]
Am requesting to add the functionality to the table component to export to pdf, excel, csv if possible....

**Comment by pi0** [comment]
@coderabsolute Sorry but we can't extend table functionality anymore. It is meant to keep to base bootstrap. You may use special libraries for that like https://github.com/ratiw/vue-table

**Comment by pi0** [comment]
Related to #224 :)

**Comment by SirLamer** [comment]
Milenon, if I may suggest, export to spreadsheet is best handled server-side and so is external to the function of this client-side package. It can be a big job and you have to assume that your user is connecting on their free crappy cell phone.

For my project, one trick I use is that I maintain two separate table templates for each table - one meant for rendering, one meant for spreadsheet export. Though inefficient from a design perspective, I chose this way because there are often subtle differences in what you want to present in each case. I am using this Package in Laravel, using the Blade templating engine:
https://github.com/PHPOffice/PHPExcel

So, you can just shovel a HTML table in to this package and it will produce a spreadsheet, which makes templating easy but isn't the most efficient programatically. It also allows you to just feed it a PHP array or other techniques if you want to get fancy. For me, I wanted quick changes which look similar to the web app rendering, so I am using HTML tables to spreadsheet.

**Comment by coderabsolute** [comment]
@pi0 Noted with thanks.
@SirLamer Thanks for the explanation.
