### ISSUE TITLE
Multiple b-modal overlay

### ISSUE THREAD

**Issue by HuanVo** [bootstrap-vue/bootstrap-vue#2334]
how to add multiple b-modal? it's same in picture. thank all 
![capture](https://user-images.githubusercontent.com/25062070/50268193-72246180-045c-11e9-9077-fd6d6ba7bda9.PNG)

**Comment by tmorehouse** [comment]
Multiple open modals (stacked) is currently only available in the `dev` branch, and will be available in the next release.

**Comment by polyestercupcake** [comment]
@tmorehouse is there a way to add multiple b-overlay's in a single component? I have a products page that has many items available to add to cart and I want a b-overlay to display over that specific button when it is clicked. Since I have multiple b-overlays currently all with the same :show="busy", it activates them all when 1 is clicked. I tried passing the :show a unique id, but it didn't take it.
Worst case scenario I will just place an overlay over the whole page instead of specific buttons. 

Thanks in advance! Your forum comments have helped me immensely in this project I have worked on over the past couple months. It has made learning Vue and BootstrapVue a much better experience!

**Comment by tmorehouse** [comment]
if using `<b-overlay>`, you should be able to wrap the element in  multiple "layers" of overlays:

```html
<b-overlay ...>
  <b-overlay ...>
    <some-component></some-component>
  </b-overlay>
</b-overlay>
```

The outer-b-overlay will cover the inner b-overlay, so work from your way outwards when triggering the overlays.

Or if using the no wrap on a position-relative element:

```html
<b-card>
  Hello World
  <b-overlay no-wrap ...>
    first overlay
  </b-overlay>
  <b-overlay no-wrap ...>
     This will overlay the first overlay
      because it appears after the first overlay
  </b-overlay>
</b-card>
```
