### ISSUE TITLE
The model is not updated in the custom checkbox component

### ISSUE THREAD

**Issue by Kvilios** [bootstrap-vue/bootstrap-vue#2354]
It's the custom compoinent:
![image](https://user-images.githubusercontent.com/30824788/50420940-4681ec80-084b-11e9-80bb-626705385e47.png)

When I add it to the main page, v-model is not updated:
![image](https://user-images.githubusercontent.com/30824788/50421001-dd4ea900-084b-11e9-94f3-49252fbb6677.png)

But I added all of props here:
![image](https://user-images.githubusercontent.com/30824788/50421023-0707d000-084c-11e9-8eaf-fa0966f9b723.png)

I did the same with other components and everything works, including components with v-model (e.g. b-form-input or textarea)

**Comment by tmorehouse** [comment]
`b-form-checkbox` uses the `input` event to update its model (and change is only emitted on user interaction that causes the v-model to change).

You may need to also set  your wrapper component to `inheritAttrs: false` and then use `v-bind:$attrs` instead of `$props`  as `$props` assumes you have defined all the props in your wrapper component.
