### ISSUE TITLE
[question] Touch/drag support

### ISSUE THREAD

**Issue by lianee** [bootstrap-vue/bootstrap-vue#2358]
As Bootstrap started (as of 4.2) to support user interaction for carousel, I guess that Bootstrap-Vue will need to catch up sooner or later.

Since I'm thinking/working on implementing some "draggable" for the table component, I'd like to know if Bootstrap-vue would prefer to implement its own solution, or rely on some existing third-party.

**Comment by tmorehouse** [comment]
We'll be investigating adding touch interaction for carousel (as it is an interactive component with moving parts).

But we have no plans on adding drag/move to table, and will leave that for people to use 3rd party wrapper components/directives.

Table is already way over engineered and bloated at the moment, and really should be left as a presentational element rather than an an interactive tool/widget. Currently table is not tree shakable if people just want a simple tabular display.  Adding more code to it increases code base with no way to tree shake any unused code based on what the user is doing with table.

Using 3rd party directives or HOC wrappers is the best solution (and just add bootstrap classes where needed for presentation)
