### ISSUE TITLE
B-Table: Filter resulted in incorrect component

### ISSUE THREAD

**Issue by jippy89** [bootstrap-vue/bootstrap-vue#2410]
Link to reproduced code in JSFiddle 
https://jsfiddle.net/irfandyjip89/vrcdgp7q/

**What's the problem?**
Result ended up with the wrong component. Actually there are two more. Sometimes tooltip is flickering and components being _re-created_ after being filtered. But let that aside first. If it was supposed to happen then it's okay.

**How to reproduce error:**
From the looks of it, when I started searching it only shows the first row component only. And after I emptied my search input, the "Company" that I was looking for had different values. 

**P.S.** For example, try to search Bing, which has true value. After that delete the search input. And Bing will return false. I also found out that when I search "Google" right after filtering "Bing", the value came back.

**What I wanted**
On search data filtered with the right component.

If you need more info, feel free to ask me. Thanks.

**Operating System:** Windows 10, 64 bit
**Tested on Browser:** Chrome Version 71.0.3578.98 (Official Build) (64-bit)
**Bootstrap Vue Version:** On Fiddle @latest | On my own 2.0.0-rc11 but both resulted in same errors!
**Bootstrap Version:** Both 4.1.3

**Comment by tmorehouse** [comment]
For the flickering of the tooltip, Try using the `boundary` config option to window or viewport:

```html
<b-btn  v-b-tooltip="{ boundary: 'window' }" title="Sometimes this thing flicks!"
		class="badge badge-alert" variant="danger">
```

The built in search routine serializes the content of the item record as a string (all field values - even fields that are not shown, are stringified and lower-cased, and joined by space).  Things like `true` and `false` will be converted into strings `'true'` and `'false'` respectively.  so if you were to search for `t` or `u`, you would get back more items than you expect because `true` appears in all of your records.

**Comment by jippy89** [comment]
Thanks @tmorehouse for the solution of flickering tooltip.

> The built in search routine serializes the content of the item record as a string (all field values - even fields that are not shown, are stringified and lower-cased, and joined by space). Things like true and false will be converted into strings 'true' and 'false' respectively. so if you were to search for t or u, you would get back more items than you expect because true appears in all of your records.

That's not what I meant, what I meant was..
Let's say I want to look for "Bing" in the search input.
1. I wrote 'b' it returns in
```
Bing | False  // Should stay true
BMW | True // Should stay false
```
2. I wrote 'bi' resulted in
```
Bing | False
```
3. I emptied my search input.
```
Audi | False
Bing | False // Got replaced(?)
BMW | False
Google | True
```
**Another weird thing,** after I done above, and I searched "Google" all the values came back like where it should be.

**Comment by tmorehouse** [comment]
Strange... when I tried your fiddle on Google Chrome (v60), the above scenarios work for me.

You might need to add a unique `key` attribute to your custom component (as Vue may be trying to re-use the vnodes):

```html
<template slot="isDataCompany" slot-scope="data" :tdClass="'justify-content-center'">
  <vue-connect-badge :item="data.item"
                     :type="'isDataCompany'"
                     :key="data.item.companyName"
  ></vue-connect-badge>
</template>
```

**Comment by jippy89** [comment]
Providing `key` fix it. 

Just one more question, does rows usually gets re-created upon filter? I actually had this other components (same like above) except that it makes an AJAX request to check wheter this website is available or not in `created` hooks and after I searched **_anything,_** it makes requests again. If it supposed to do that, then I'll figure something else.

**Comment by tmorehouse** [comment]
The following will trigger a provider refresh:
- filter change
- sort column change
- sort direction change
- pagination

It assumes that the provider function will be handling the filtering, sorting, and pagination.

You can disabled each one of those via the following props:
- no-provider-filtering
- no-provider-sorting
- no-provider-pagination

These are covered in the docs under the items provider section.

Anytime anything changes that _may_ cause the table contents to update, the table re-renders. This is based on Vue's reactivity, and even changes in the parent component or a child component can cause a re-render.  Vue tries to minimize changes to the DOM by comparing the result of the render function and the actual DOM and only patches what it determines needs updating.

Note in the latest `dev` branch (not yet released), we have optimized/cached some of the computed values, ti minimize render time and changes to the DOM.

**Comment by jippy89** [comment]
I'm sorry, I don't get it. But is this what you mean?
https://jsfiddle.net/irfandyjip89/23nqobsr/

I forked my fiddle, and made a small changes. 
1. Added a column that has AJAX, just to check a website.
2. And added this props in b-table
```
<b-table
	 hover small bordered no-sort-reset
         no-provider-filtering
         no-provider-sorting
         no-provider-pagination
	:items="company.data"
	:fields="company.fields"
	:filter="searchLocation"
	:sort-by.sync="company.sortBy"
	:sort-asc.sync="company.sortAsc"
>	
```
But it stills refreshes.

**Comment by tmorehouse** [comment]
That is correct.  filtering will cause the table to re-render (as will sorting, data changes, pagination, etc).
And since b-table doesnt know if the provider will always return the same data, it will call the provider function.

If you just want to request your data once, and let b-table handle the sorting/filtering/pagination, then it is better to move your async get outside of b-table and then pass b-table an array of records via the `items` prop.  This way filtering/sorting/pagination/etc won't trigger your async function.  YOu can then use an external control to refresh that data and pass a new array to b-table.

**Comment by tmorehouse** [comment]
We've made a few changes (forthcoming in release 2.0.0-rc.14), in which case you will need to set a primary-key column (via the `primary-key` prop) in order for each row to have a guaranteed unique `:key` applied to it (otherwise we revert back to the displayed `tr` index number within the `tbody`).

The initial solution was to use the item's values serialized into a string, which introduced new issues when item data was being modified in-place, causing the entire row to be re-rendered (which introduced issues with cursor jumps on text-like inputs).
