### ISSUE TITLE
Offset in popovers does not accept negative value

### ISSUE THREAD

**Issue by paglias** [bootstrap-vue/bootstrap-vue#249]
```
b-popover(
  offset="-6 0",
)
```

applies the correct negative offset but it also shows a validation error

```
[Vue warn]: Invalid prop: custom validator check failed for prop "offset". 
(found in <BPopover> at /Users/matteo/dev/habitrpg/habitrpg/node_modules/bootstrap-vue/lib/components/popover.vue)
```

Thanks for this library!

**Comment by SirLamer** [comment]
You are right, in fact I think I am performing entirely too much validation on that field. I will fix.

If you compile for "production", validation tests are usually not include in most bundling solutions, so your end-users should not get that validation warning. It's just a console warning and otherwise it will work as expected in the short-term.

See: http://tether.io/#offset

**Comment by SirLamer** [comment]
This will be fixed in the next release.

**Comment by paglias** [comment]
Thanks!
