### ISSUE TITLE
[QUESTION] Customizing class names

### ISSUE THREAD

**Issue by zek** [bootstrap-vue/bootstrap-vue#2534]
Hey I am using bootstrap based theme ( https://keenthemes.com/metronic/preview/?demo=demo4 )

But the problem is all of the class names are different. 

For example instead of "nav" they use "m-nav" or "m-dropdown".  What do you suggest to me for making this library compatible with metronic theme?

Also some components has wrappers or extra divs. As I see you use render function to generate template which is something new for me :)

**Comment by tmorehouse** [comment]
BootstrapVue is based on default Bootstrap SCSS/CSS, and expects the default classnames to be used. Themes are generatated by changing the contents of the default classnames (by changing the values of the Bootstrap V4.x SASS variables), not by changing the names of the classnames).

It appears that Metronic customizes the CSS completely (including replacing all the classnames), which is more of a fork rather than a true Bootstrap V4 theme.
