### ISSUE TITLE
Can't use input with v-model within b-table

### ISSUE THREAD

**Issue by stolfgang** [bootstrap-vue/bootstrap-vue#2580]
Hi!

With rc12 it's not possible to use input with v-model within b-table anymore.
The example from https://github.com/bootstrap-vue/bootstrap-vue/issues/1575 (https://jsfiddle.net/cihkem/rv21gkju/) worked fine in older versions. But, now it looses the focus after each key input (seems to reload the whole table)
I was able to build a workaround with v-model.lazy, but would be great to get this working again.

**Comment by tmorehouse** [comment]
Is the v-model of the input tied to value in the items data?

BootstrapVue now generates a `:key` value on the rendered `<tr>` which is a serialized value of the items data (concatenated with the row number), mainly for use with transitions.  Since the row's data is changing, the key is changing as well... which would cause that `<tr>` to re-render.

We may need to revert back to just the row number (visible row number).

**Comment by tmorehouse** [comment]
Hmmm
actually that unique key that was generated using serialized data was to fix another issue:

> Create a unique key based on the record content, to ensure that sub components are
> re-rendered rather than re-used, which can cause issues. If a primary key is not provided
> we concatinate the row number and stringified record (in case there are duplicate records).

See: https://github.com/bootstrap-vue/bootstrap-vue/issues/2410

**Comment by tmorehouse** [comment]
The workaround would be the `blur` or `change` event on the `b-form-input`, or to not directly modify the underlying table data (_which will **always** cause a re-render of the table_), and use a local variable as the `v-model`, and then update the table data source (i.e. via a button click or blur/change event).

> ### `v-model` modifiers
> Vue does not officially support `.lazy`, `.trim`, and `.number` modifiers on the `v-model` of custom component based inputs, and may generate a bad user experience. Avoid using Vue's native modifiers.
> To get around this, `<b-form-input>` and `<b-for-textarea>` have two boolean props trim and number which emulate the native Vue v-model modifiers .trim and .number respectively. Emulation of the `.lazy` modifier is not supported (listen for `change` or `blur` events instead).

**Comment by tmorehouse** [comment]
If you have a unique value column in your data (i.e. a primary key), you can specify the `primary-key` prop to point to that field that contains this unique value.  This will be used as the `<tr>` unique Vue `:key` value instead of the serialized row data. which will prevent a change in the underlying data forcing a re-render of the row.

The primary key column does not need to be rendered as part of the fields array.  It just needs to exist in the items data.

**Comment by tmorehouse** [comment]
I'll update the docs for b-table for the `primary-key` section (https://bootstrap-vue.js.org/docs/components/table/#primary-key) mentioning about in-place changing of table items data.

**Comment by stolfgang** [comment]
Thanks a lot!
