### ISSUE TITLE
Delete Table Row

### ISSUE THREAD

**Issue by abhi-cognitivo** [bootstrap-vue/bootstrap-vue#2581]
How would I got about deleting or eliminating a table row? 
I am not able to get an index out of the data.item object.

Any help would be greatly appreciated

**Comment by tmorehouse** [comment]
Since table rows are generated from the underlying model of the items array, you would need to remove the row from the items array.

Just like any Database, in order to manipulate the rows (i.e. deleting one), you would need something that uniquely identifies the row to be removed from the items array (i.e. a primary key or similar).

Before passing your array to the table, you could massage the data and provide a unique key (i.e. using an increment counter) which can be later used to modify/remove the row data.

**Comment by abhi-cognitivo** [comment]
Thanks!


Abhishek Shah
*COGNITIVO*
Roque Centurion Miranda, Edf. Studio Park. Off. 608
Asunción, Paraguay
*Tel: *(021) 328-8271
