### ISSUE TITLE
Error message in <b-input-group> is breaking style

### ISSUE THREAD

**Issue by sowinski** [bootstrap-vue/bootstrap-vue#2670]
Hi,

if I use prepend and append in an <b-input-group> and try to show an error message then the style is not displayed correctly.

Please find here the sample code:
```
<b-form>
  <b-form-group>
    <b-input-group
      prepend="prepend"
      append="append"
    >
      <b-form-input
        :state="false"
      />
        <b-form-invalid-feedback>
          ERROR MESSAGE2
        </b-form-invalid-feedback>
    </b-input-group>
  </b-form-group>
</b-form>
```
And add it here:
https://bootstrap-vue.js.org/play/

**Comment by tmorehouse** [comment]
This is a known issue with how feedback is placed/nested inside input groups.

Use the form-group feedback limitations (see https://bootstrap-vue.js.org/docs/components/form-group#feedback-limitations), and sync you state of the input to the feedback and/or form-group.

Basically move your feedback after the input group, and then use the `state` prop on the feedback component so that it has the same `state` as the input.

See the examples in the documentation: https://bootstrap-vue.js.org/docs/components/form#feedback-helpers
