### ISSUE TITLE
Required attribute not working on b-form-checkbox since rc12?

### ISSUE THREAD

**Issue by jchm** [bootstrap-vue/bootstrap-vue#2718]
It looks like the required attribute stopped working since the rc12 release on the b-form-checkbox component. 

**Broken test case on rc12:**
https://codesandbox.io/s/3ymk10x416
When submitting the form, the first checkbox should show a default validation message but doesn't. When wrapped in a b-form-checkbox-group it does trigger the default validation message.

**Working test case on rc11:**
https://codesandbox.io/s/rk382201o
When submitting the form, the first checkbox shows the default validation message. When wrapped in a b-form-checkbox-group it also shows the default validation message.

**Comment by tmorehouse** [comment]
Actually this is intended behaviour.  You are missing a name associated with the standalone checkbox.  input name is is required for the required prop to work.  This is for assistive technologies (i.e. screen readers, keyboard only users), if no name is provided, then the AT screen reader doesn't know if the checkbox is part of a group or not.

simply add a `name="unique-name"` on your checkbox and the required prop will start working.

**Comment by tmorehouse** [comment]
See this updated Sandbox for working fix: https://codesandbox.io/s/ym065pl2nz

**Comment by tmorehouse** [comment]
We'll need to update teh docs to mention that when not using the checkbox group, the checkbox will need to have a name in order for the `required` prop to work.

In general, all form inputs should have a name associated to them for keyboard navigation and screen reader support... otherwise these users will get confused as to which inputs are linked together (specifically radios and checkboxes).

**Comment by jchm** [comment]
Aha, thanks for the explanation and quick replies!
