### ISSUE TITLE
Bootstrap Vue Radio/ Checkbox buttons - no longer possible to have HTML in text

### ISSUE THREAD

**Issue by DM2489** [bootstrap-vue/bootstrap-vue#2758]
In RC12, it was possible to place HTML elements inside an options array for a radio or buttons group, like so:

![image](https://user-images.githubusercontent.com/40390596/53700537-77524500-3deb-11e9-9189-7c217fd3b22a.png)

This would allow icons to be added and would render them out:

![image](https://user-images.githubusercontent.com/40390596/53700559-9c46b800-3deb-11e9-9637-52b196f03527.png)

However, in RC13, this is completely impossible - it seems to strip out any HTML and therefore doesn't get rendered.

**Comment by tmorehouse** [comment]
You need to use the `html` property instead of `text` property in your options array:

```js
options = [
  {
    value: 1,
    html: '<b>Option1</b>`
  },
  {
    value: 2,
    html: 'Option <b>2</b>'
]
```

The change was needed due to `XSS` concerns when options were supplied via user content. You must now explicitly use the new `html` property in options if you want to render HTML, and use the `text` property if you only need text content (or are using user supplied content for the options).

The forthcoming `2.0.0-rc.14` release has updated documentation to reflect these changes.

**Comment by DM2489** [comment]
Ah! Cheers @tmorehouse. I did check the documentation but this prop isn't referenced - I'm glad that it will be updated for rc14.
