### ISSUE TITLE
Default b_UIDs for components

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#281]
Should all components have a default `b_UID` on the parent container (if no ID provided)?

And if so, should IDs be "dynamic/reactive" or static once set?

Something like this?

```js
  data() {
    return {
      thisId: this.id || ('b_' + this._uid )
    };
  },
  props: {
    id: { 
      type: String,
      default: null
    }
  }
```

And if IDs are required for other elements within the component they can be based on `thisId`:

```html
<template>
  <div :id="thisId">
     <span :id="thisId + '_myspan'">Some element</span>
     <div :id="thisId + '_mydiiv'">Some other element</div>
     <div>This one doesn't need ID</div>
  </div>
</template>
```

**Comment by SirLamer** [comment]
I would make the ID field a prop with default 'b_' + this._uid. Any events should be broadcast with the ID included in the data package. And yes it should be responsive. If the programmer wants to do screwy stuff with that then that's fine.

**Comment by SirLamer** [comment]
In a way, the ID field is already an option as adding an ID to a component should be respected and added to the top-level element for the rendered component as a normal HTML spec-compliant ID. What the Vue-managed ID prop does is allow to attach an identifier to broadcast events.

**Comment by tmorehouse** [comment]
I can see a use for it when adding in `aria-labeledby` and aria-describedby` attributes, and when `<labels>` have a `for`target for accessibility reasons, especially since some of these attributes are buried deep into  component.

**Comment by SirLamer** [comment]
Maybe the default IDs should identify the component type? I am just suggesting this because native Bootstrap does something similar

So 'popover' + this._uid

**Comment by tmorehouse** [comment]
Thats an idea too :)

**Comment by SirLamer** [comment]
Yeah, or "b_popover" and "b_modal" and so on, the point is just to allow for string filters and stuff.

Is the _uid value generated in a deterministic way such that server-side rendering will work?

**Comment by tmorehouse** [comment]
Good question.  It is sequential, based on when the app/component are initialized.

**Comment by SirLamer** [comment]
Okay, so if it is tied to a clock then no? Unless the client-side render event is somehow handed the server-side timestamp? I just don't know much about this.

**Comment by tmorehouse** [comment]
The `_uid` numbers are based on a counter in `Vue`, and not time based.

**Comment by SirLamer** [comment]
Yeah but what sets the initial state of the counter when using SSR? This is what we need to find out first.

**Comment by tmorehouse** [comment]
When Vue is loaded it initializes its counter at 1.

**Comment by SirLamer** [comment]
AWESOME so then it should be deterministic and thus not change with a proper SSR setup.

**Comment by tmorehouse** [comment]
I'll go look at the Vue 2.x code and see where it initializes the counter.

**Comment by SirLamer** [comment]
I was doing the same, you're right, it starts at 1.

https://github.com/vuejs/vue/blob/3b7cfc71cbf13e91e3cb69278f5411642e817199/src/core/instance/init.js#L13

**Comment by tmorehouse** [comment]
From https://github.com/vuejs/vue/blob/dev/src/core/instance/init.js#L13

```js
let uid = 0

export function initMixin (Vue: Class<Component>) {
  Vue.prototype._init = function (options?: Object) {
    const vm: Component = this
    // a uid
    vm._uid = uid++

```

**Comment by tmorehouse** [comment]
But the `let uid = 0` is part of the init.js code, but outside the `export` statement.

So not sure if this gets reset on each SSR page render or not.

**Comment by SirLamer** [comment]
Yeah because "new Vue()" on each page render implies a new instance. The con of doing this is if someone gets silly and runs multiple parallel Vue instances it'll generate the same ID numbers, but the pro is that it should work with SSR setups.

SSR just renders the page on a Node server before serving it to the client so that they get the rendered initial instance of the page for the couple seconds before Javascript loads client-side. I am not using SSR right now but we don't want to make it harder for others.

I have written a few components which use Math.random() to get IDs but I will be switch them to the _uid feature.

**Comment by tmorehouse** [comment]
Yeah, and just in case the instance `_uid` starting value gets reset on client side, we could use the `$isServer` to alter the ID name slightly so that any new components don't get conflicting default IDs. (i.e. any server side rendered IDs and then some new client side rendered IDs shouldn't conflict)

**Comment by tmorehouse** [comment]
The default ID could be done as a mixin that is included in all components, to keep the code generation in a single spot and easy to update if needed. And I think we can get the component name from the `vm` instance too.

**Comment by SirLamer** [comment]
After the client session is handling rendering, it no longer matters what happens to _uid. We only need to care about the instance where the server-side rendered DOM is handed off to the client which is, like, 2 seconds in. And even within Vue itself it shouldn't matter, but there could be other processes (ie. jQuery) which load first and hook on those ID values. So we're talking about some really serious edge cases here but it's still worth considering. I just wouldn't want all of the IDs to flip to new values once the client environment assumes rendering.

**Comment by SirLamer** [comment]
Yeah I agree the approach for bootstrap-vue should involve a mixin whch enforces the ID generation as common across the project. To that end, there is a property "vm.$options.name" which provides the component's registered name and could be used as the prefix for default ID generation.

**Comment by tmorehouse** [comment]
The component VM has the property `this.$options._componentTag`, which for the Bootstrap-Vue navbar is set to `b-navbar`.

So the default ID generation could be the following:
```js
props: {
  id: {
    type: String,
    default: (this.$isServer ? 's_' : '') + this.$options._componentTag + '_' + this._uid
  }
}
```
the ID would start with `s_` if it was rendered on the server side: `s_b-navbar_###`

And if rendered on the client side it would be: `b-navbar_###`

**Comment by tmorehouse** [comment]
`vm.$options.name` isn't always set though. http://vuejs.org/v2/api/#name

**Comment by tmorehouse** [comment]
So, depending on how the component was instantiated (either globally, or within another component), the `vm.$options.name` value isn't the 'tag', but looks something like `bNavBar`, so yeah, it might be a good source for part of the ID.

```js
props: {
  id: {
    type: String,
    default: (this.$isServer ? 's_' : '') + this.$options.name + '_' + this._uid
  }
}
```

**Comment by SirLamer** [comment]
I don't think we want the server-side render to have a different prefix, they should match. We can expect the IDs to generate in the same sequence and thus all be the same.

**Comment by tmorehouse** [comment]
But I am not sure if `uid` counter is reset on each page render Server Side or not.

And I think there could be a potential ID clash situation if it does/doesn't reset.  But this server side ID prefix could be something kept in our back pocket until we are sure.

**Comment by SirLamer** [comment]
It has to be, everything is run from scratch on page refresh.

**Comment by SirLamer** [comment]
Besides, prefixing the IDs with a special feature for the server-side instance breaks any intent of making them match.

**Comment by tmorehouse** [comment]
When the client instantiates the element, wouldn't Vue pull the ID's from the rendered HTML?

**Comment by tmorehouse** [comment]
How about this:
https://github.com/tmorehouse/bootstrap-vue/blob/b_UID-mixin/lib/mixins/ids.js

**Comment by SirLamer** [comment]
It won't pull the IDs from the rendered HTML. What server-side rendering does is feed the client a bland HTML page 1992-style, pre-rendered so that it doesn't need to run any Javascript. In the meantime, the client is downloading the Javascript package (if not buffered) then it spends some time hydrating the client session with the Javascript package. When Vue is instantiated, it starts rendering its HTML payload, and when its done it pushes it to the DOM. At that time, whatever HTML content is within the Vue's app scope is swapped out and replaced with its own computed version. It does not care what was there before. This last step applies in all cases, it just happens that with server-side rendering it is wiping out something which is already fairly pretty. What can do, though, is expect server-side and client-side to do the same thing in all respects except for floating point-based mathematics as well as time-sensitive actions such as pseudo-random number generators.

Another solution for dealing with the rendering time is to use the "v-cloak" feature however this can be very punitive on a slow connection or on a low performance device.

**Comment by SirLamer** [comment]
Your mixin works but the validation type "Boolean" is wrong, I submitted a PR to your blob.

**Comment by tmorehouse** [comment]
Oops... Copy and paste issue on my end ;-)

**Comment by tmorehouse** [comment]
Based on what I read on SSR, Vue only re-renders DOM elements that have changed (if the HTML doesn't match the client rendered version.)  So not sure how it deals with props that remain as rendered HTML tags.  I know that the 'server-rendered="true"` will be placed on the app root DOM tag.

https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#client-side-hydration

> In server-rendered output, the root element will have the server-rendered="true" attribute. On the client, when you mount a Vue instance to an element with this attribute, it will attempt to "hydrate" the existing DOM instead

**Comment by tmorehouse** [comment]
Of course, I've never used SSR yet (but will soon hopefully), so I'm not rally sure how it "reacts".  I'll have to set up a play server and see what it does.

**Comment by pi0** [comment]
About sequential `uuids` we can't just trust them as a deterministic source, using client-side routers like `vue-router` they are not re-initializing Vue instance for each page. (See [Simple Routing From Scratch](https://vuejs.org/v2/guide/routing.html#Simple-Routing-From-Scratch) to get idea how they are basically working)

Besides of that adding self generated `id` to each component breakes [props down, events up](https://vuejs.org/v2/guide/components.html#Composing-Components) pattern. Components specially ones coming from a library should be as pure as possible and not deriving state from global.

In normal use cases it is better to pass events/references instead of auto generated ids and this also applies to modals too. We only may need such hack in special cases when explicit `for` and `aria` attributes are needed and it would be SSR safe enough if only added after `mounted()` hook.

**Comment by pi0** [comment]
Locking as it is a final decision. Please feel free for discussions in slack channel.
