### ISSUE TITLE
dropdown inside a scollable modal

### ISSUE THREAD

**Issue by Grollicus** [bootstrap-vue/bootstrap-vue#2831]
I'm trying to use a `<b-dropdown>` inside a small scrollable `<b-modal>`. This breaks because the menu does not scroll with the modal-body. Check out this fiddle for an Example: https://jsfiddle.net/xt1ukr0y/

Setting the `boundary` property (eg. to `viewport`) improves the situation a bit, but the modal still stays too small. Ideal for me would be if the menu popup would pop out of the modal.

I've managed to kind-of get this working by hacking [portal-vue](https://github.com/LinusBorg/portal-vue) into the dropdown: 
```js
menu = h('portal', {attrs:{'to':'menuthingy'}}, [menu]);
```
But I don't think that's a long-term solution. How would you solve this? Any advice?

Btw, not that it helps me (as it doesn't set the parent element for the menu) but could you allow `HTMLElement` values for the `boundary` param of `b-dropdown`, analogous to #2229?

**Comment by tmorehouse** [comment]
Have you tried `boundary="window"` ?

**Comment by tmorehouse** [comment]
Could you also create a JSFiddle with a mock up?  You can use the playground to create an example, and then export it to JSFIddle.

**Comment by tmorehouse** [comment]
@Grollicus I have found a partial solution: adding the class `position-static` to the modal body via `body-class` prop.

There is one other issue, when the open dropdown is larger than than the modal, which is due to the `overlow: hidden` style from bootstrap SCSS:

``` css
.modal-dialog-scrollable .modal-content {
  overflow: hidden
}
```

By changing this to `overflow: initial`, along with the above body class and changing the boundary on the dropdown, all works fine.

I'm not sure the reasoning why they added overflow:hidden on the modal-content when in scrollable mode, as it works without that style being there.

But this appears to be an upstream issue with Bootstrap V4.3.x SCSS

**Comment by tmorehouse** [comment]
I would suggest creating an issue at https://github.com/twbs/bootstrap/issues and then cross-refrence this issue.

**Comment by tmorehouse** [comment]
I have created issue https://github.com/twbs/bootstrap/issues/28513 with native bootstrap examples of the issue and workaround.

**Comment by tmorehouse** [comment]
Closing as an upstream issue, plus workaround available.
