### ISSUE TITLE
4 events fired on collapse event

### ISSUE THREAD

**Issue by stickeerehan** [bootstrap-vue/bootstrap-vue#2923]
Operating system and version: Ubuntu 18.04.2 LTS
Browser and version: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Version of BootstrapVue that you are using: 2.0.0-rc.15
Example: https://jsfiddle.net/vzotdshw/1/

When listening for the bv::collapse::state event, looks like it's being fired off 4 times (see console). This I believe is a bug as I would expect it to trigger only once.

**Comment by tmorehouse** [comment]
This was put in place because of https://github.com/bootstrap-vue/bootstrap-vue/issues/1798 (and PR https://github.com/bootstrap-vue/bootstrap-vue/pull/2102)

The state class is emitted whenever the collapse is updated (in the updated hook) to ensure the `collapse` persists on the toggle button due to component updating.
