### ISSUE TITLE
b-img-lazy very slow loading

### ISSUE THREAD

**Issue by amoralesdesign** [bootstrap-vue/bootstrap-vue#3013]
I'm using the <b-img-lazy> component to load images from my website with lazyload.

These images are loaded too late. The users scroll quickly on mobile and when they arrive at the product box scrolling...the image has not been loaded yet!, being quite uncomfortable this slowness for the UX.

Is there any way to display images faster?

Here's an example, scroll on mobile:
https://regalospersonales.com/tazas-personalizadas

**Comment by jackmu95** [comment]
@amoralesdesign Take a look at the [Usage](https://bootstrap-vue.js.org/docs/components/image#usage) section of the `<b-img-lazy>` component for tipps to improve your current implementation.

**Comment by tmorehouse** [comment]
`b-img-lazy` monitors scrolling to determine if the image should be loaded or not, and scrolling events (on some browsers) fire at a rapid rate (sometimes even for every single pixel of scroll).  We throttle/debounce the scroll event in order to minimize the amount of computations performed at each scroll event (which if we didn't would cause scrolling to be very laggy/unresponsive for some users).

So it is possible for someone to scroll over a lazy loaded image very rapidly and the image not load (because of the throttle period), but will load when the scroll back to that image.

There are several options for controlling when the image gets loaded, i.e. how far away from the view port does it need to be before it get's loaded via the `offset` prop (defaults to 360 pixels from the viewport), and the number of milliseconds the scroll event is throttled via the `throttle` prop (defaults to 100ms).

You could increase the `offset` to a larger value (such as 1000 pixels) and/or decrease the `throttle` to a small value (such as 10 or 25 ms).

**Comment by tmorehouse** [comment]
If you need to images to be there when the user scrolls really fast (and you can't control the network latency or speed), then maybe not using Lazy images might be your best solution.
