### ISSUE TITLE
Default state of control for b-collapse does not heed 'visible'

### ISSUE THREAD

**Issue by kgb-financial-com** [bootstrap-vue/bootstrap-vue#3020]
When using a construction like this:
`<b-btn v-b-toggle="collapseId">...</b-btn>`
`<b-collapse visible :id="collapseId">...</b-collapse>`
plus some additional circumstances which are unfortunately yet unknown to me, the Button will, a few milliseonds after being initially displayed correctly, get the class `collapsed` added, and thus be displayed incorrectly (as if no `visible` tag had been added to the `b-collapse`).

This happens with release 2.0.0.rc16. It does not happen with 2.0.0.rc15. I believe the problem to have been introduced with commit https://github.com/bootstrap-vue/bootstrap-vue/commit/6f899fc , where a comment states
`// state is initially collapsed until we receive a state event`
which is not the case due to `visible`.

- Operating system and version: Windows 10
- Browser and version: Chrome 73.0.3683.86
- BootstrapVue 2.0.0.rc16

I have not been able to reproduce this with a minimal setup. We observe this problem on a large page with several collapse instances. All instances are affected, and it is 100% reproducible on that large page.

**Comment by tmorehouse** [comment]
That line you are referring to only happens when the directive is first bound to the element, and the listens for $root events happen after that point in time, which should then first synchronize the state to match that of `b-collapse`.

What has changed is that the state event used be emitted whenever the b-collapse changed (for any reason) via the `udpated()` hook (even if the collapse state didn't change), but we found that people were actually using that event to trigger other stuff (the event was supposed to be a private internal only event to ensure the toggle's state was up to date with the collapse).

We may need to introduce a private non-documented internal event to handle the `updated()` hook, which gets emitted when anything changes.

Is it collapses that are in navbars, or just in the document?

Are you using `<keep-alive>` around any of the collapses or toggle buttons?

**Comment by kgb-financial-com** [comment]
Thank you for looking into this, I will test your changes with our code as soon as they are finished.

The collapses are in the document. We do have a navbar, but the collapses are elsewhere. We do not use <keep-alive> (performed full-text search on our project).

**Comment by kgb-financial-com** [comment]
I confirm that this fix solves our problem. Thanks a lot!
