### ISSUE TITLE
Bug with modal closing after mouseup outside modal

### ISSUE THREAD

**Issue by speedblizzz** [bootstrap-vue/bootstrap-vue#3025]
When I select text in modal, continue to move mouse outside the modal, then do mouse up and the modal will close.

I expecte that modal will not close after mouse up outside modal.

There was the same issue with react-bootstrap [https://github.com/react-bootstrap/react-bootstrap/issues/3373](https://github.com/react-bootstrap/react-bootstrap/issues/3373) but it already fixed.

I have this bug in Chrome, Edge, Opera.

It works fine in Firefox and IE11 .

I use latest bootstrap-vue version.

Also it works good (modal doesn't close) on official Bootstrap 4 Docs page [https://getbootstrap.com/docs/4.1/components/modal/](https://getbootstrap.com/docs/4.1/components/modal/)

**Comment by tmorehouse** [comment]
Ah, that is because some browsers do trigger a click event on mouse up when doing a text selection.  we had a similar issue with tables and text selection triggering a row clicked event.

We might be able to add a check for an active text selection in the modal backdrop click handler.

A quick workaround would be to disable close on backdrop click by setting the prop `no-close-on-backdrop` on `<b-modal>`.
