### ISSUE TITLE
<b-textarea> with `max-rows` property adds `overflow-y: scroll`

### ISSUE THREAD

**Issue by ozguruysal** [bootstrap-vue/bootstrap-vue#3077]
The "problem" is already visible on the first example on the [documentation page](https://bootstrap-vue.js.org/docs/components/form-textarea/).

Before v2.0.0-rc.17 a text area with `max-rows` prop would look like this:

![image](https://user-images.githubusercontent.com/53624/55870488-5a9af100-5b91-11e9-923a-4880cd566c97.png)

However now `overflow-y:scroll` is injeted as inline style which makes it look like this (note the vertical scroll):

![image](https://user-images.githubusercontent.com/53624/55870819-13613000-5b92-11e9-9511-ea1508c770bd.png)

Not sure why the change but in my opinion we should get the default Bootstrap styles/results as this is unexpected and breaks current styles.

**Comment by tmorehouse** [comment]
This is working as expected.  This is due to how the calculations are peformed to get the height.

Without the vertical scroll, the height computations produce erroneous results when the number of lines in the text area are close to the minimum height.  Without the scrollbar in place the inner width of the textarea is wider, until a scrollbar is needed, causing the lines to jump by one, or produce an extra blank line when the scrollbar is removed.

**Comment by tmorehouse** [comment]
Putting `overflow-y` back to `auto`  from `scroll` would re-introduce a bug that it is there to fix. #3012

**Comment by ozguruysal** [comment]
Thanks for the quick response and explanation.

**Comment by tmorehouse** [comment]
The only other way we might be able to hanlde this it to dynamically measure the scrollbar width and add it to the right padding of the textarea when max-height has not been reached, and remove it when the textarea starts to overflow.

It would be a bit more work/calculations to do (which happen on every keystroke, so it could impact performance)
