### ISSUE TITLE
[vee-validate] Interface 'Table' incorrectly extends interface 'Vue'

### ISSUE THREAD

**Issue by austinstudio** [bootstrap-vue/bootstrap-vue#3099]
This item has not been resolved even though it was marked as completed.

https://github.com/bootstrap-vue/bootstrap-vue/issues/3041#issue-430339573

See the following thread on Stackoverflow.   I am getting the same errors as these folks.

https://stackoverflow.com/questions/55627320/bootstrap-vue-not-compiling-multiple-type-x-is-not-assignable-to-type-y

**Comment by andruu** [comment]
I'm having thee same issue.

**Comment by briandhill** [comment]
@austinstudio The problem isn't with Vue-Bootstrap. It's with another library we're using, vee-validate. 

Bootstrap-Vue recently added TypeScript definitions to their Table component, and with that, the error surfaced due to vee-validate setting a type definition directly on the `fields` property of the Vue instance. Bootstrap-Vue did it correctly in my mind with extending the Vue instance and then defining the type for the `fields` property.

I've been trying to come up with a way to ignore that specific definition file inside the vee-validate library using the tsconfig.json, but nothing has worked thus far. The real fix would be for vee-validate to not set type definitions directly on the properties of the Vue instance. I did comment on that commit where they added that definition ([link](https://github.com/baianat/vee-validate/commit/9450a5618c92d69019f8d97033ce4206a9450485#diff-fbf414ec0ed230cce681d1bb2c9b2d5d)), but I haven't received a response yet.

**Comment by briandhill** [comment]
Yeah, bootstrap-vue@2.0.0-rc.16 compiles without the error. I noticed someone had a similar conflict with vee-validate and another Vue package as well [1983](https://github.com/baianat/vee-validate/issues/1983).

**Comment by aleksanderd** [comment]
a workaround to override vee-typings locally:
https://stackoverflow.com/a/55734147/3499604

**Comment by tmorehouse** [comment]
And here:  https://stackoverflow.com/a/50794250

Vee-validate should be prefixing its property injections into components like most other libraries do, and using the prefixed names in the types definition file.

**Comment by jackmu95** [comment]
Can someone please confirm that VeeValidate v2.2.4 fixed this issue so we can close that over here.

**Comment by tmorehouse** [comment]
@austinstudio @andruu @briandhill
Could you verify that the latest VeeValidate v2.2.4 fixed this issue?

**Comment by briandhill** [comment]
Using `vee-validate 2.2.4` and `bootstrap-vue 2.0.0-rc.18`, it did not. Looking at `vee-validate 2.2.4`, no changes were made to address the root problem which is the `FieldFlagsBag` type being set and required on the `fields` property on the Vue instance. The `FieldFlagsBag` is requiring certain properties to be set, such as `untouched`, `touched`, `dirty`, `pristine` and a couple more. Therefore, any other library trying to set the `fields` property to a type that doesn't meet that requirement will throw an error during compilation.

```
149:20 Interface 'Table' incorrectly extends interface 'Vue'.
  Types of property 'fields' are incompatible.
    Type 'TableFieldObject | (string | ({ key: string; } & TableField))[]' is not assignable to type 'FieldFlagsBag'.
      Type 'TableFieldObject' is not assignable to type 'FieldFlagsBag'.
        Index signatures are incompatible.
          Type 'TableField' is missing the following properties from type 'FieldFlags': untouched, touched, dirty, pristine, and 3 more.
    147 |   }
    148 |   export interface Progress extends Vue {}
  > 149 |   export interface Table extends Vue {
        |                    ^
    150 |     refresh: () => void
    151 |     fields?: TableFieldObject | TableFieldArray
    152 |   }
```

**Comment by jackmu95** [comment]
@austinstudio @andruu @briandhill:
Maybe someone with decent TypeScript knowledge can submit a PR over at VeeValidate to fix the issue in the typings.

**Comment by briandhill** [comment]
@jackmu95 I was going to take a swing at it once I had some free time. It could be good practice for someone who wants to learn TypeScript as well.

**Comment by tmorehouse** [comment]
@jackmu95 @briandhill PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3209 is a first attempt (if you can call it that, as I have no TypeScript experience) at adding more complete types for BootstrapVue.

Any input / assistance / pointers would be greatly appreciated.

**Comment by logaretm** [comment]
I have removed the Typing for those properties as of https://github.com/baianat/vee-validate/commit/fedea704e01aaa64749c04c891b74c1be6d70c12, You can cast them to `ErrorBag` and `FieldFlagsBag` as a workaround for future releases.

I don't think `bootstrap-vue` or any other library need to fix this on their side, as vee-validate is the offender here.

Prefixing the properties is a huge breaking change for a lot of people, so I don't think it will be done anytime soon in the v2 releases.

Furthermore, I don't think there is a way to dynamically Type those properties since they are a runtime thing, also they are misleading since they do not exist on every Vue component. I have addressed the issue entirely in the v3 branch and it should have much better TS support since I have re-wrote everything in TypeScript.

Sorry for causing trouble everyone.

**Comment by tmorehouse** [comment]
@logaretm thanks!

We'll keep this issue open until the vee-validate commit is released.

**Comment by logaretm** [comment]
@tmorehouse I released `2.2.6` with this commit.

**Comment by tmorehouse** [comment]
@logaretm Thanks again!

**Comment by tmorehouse** [comment]
SOLUTION: Please upgrade Vee-Validate to ^2.2.5

**Comment by briandhill** [comment]
Thanks @logaretm!
