### ISSUE TITLE
<b-form-group>: `description` display alternative

### ISSUE THREAD

**Issue by fancydev18** [bootstrap-vue/bootstrap-vue#3100]
b-form-group has a description property, which is very useful:
https://bootstrap-vue.js.org/docs/components/form-group/#comp-ref-b-form-group

To make forms more compact for users already familiar with some interface, please have another property, eg description_display, which can specify an alternative display.

For example, this would hide description by default, and show it only on an user action:
description_display="tooltip" would change the default current display to showing an underline under label (dashed style, not to be confused with links). 
On desktop mouse hover, it would show the description as a tooltip, by setting the description to "title" property of the element. Browser will show title automatically on hover.
On mobile, clicking on the label would show description just like it does now.

You might want to set label HTML element "title" property property to description value by default, regardless of description_display.

**Comment by tmorehouse** [comment]
Since the form-group is just a convenience wrapper to place around inputs (and other content), you could leave the "description" field empty, and apply a tool-tip directly to an input (triggered on focus), or listen for the focus and blur events on the input and populate the form-group's description value (so that it is only shown when the input has focus).
