### ISSUE TITLE
<b-modal> does not emit `close` event when closing on backdrop or on esc

### ISSUE THREAD

**Issue by jakobbraun** [bootstrap-vue/bootstrap-vue#3164]
The @close event is not fired when the modal is closed by esc or backdrop. This is not intuitive, because it is called close-on-esc.

**Comment by tmorehouse** [comment]
Close event is only emitted when the modal header `x`  close button is clicked, as per the docs.

Modal backdrop fires the `hide` event with evt.trigger set to `backdrop`

**Comment by tmorehouse** [comment]
The named convenience events (`cancel`, `ok`, `close`) are used for the internal built in buttons (`Cancel`, `OK`, and `X` close buttons).

**Comment by m-demydiuk** [comment]
Hi guys, are you going to add event for backdrop click?

**Comment by tmorehouse** [comment]
Use the `hide` event. and inspect the `BvModalEvent.trigger` value for the type of hide event 9it will be `esc`, `backdrop` etc.

`ok` and `cancel` are just convenience events that inspect that value.

You can also disable close on esc and close on backdrop click via props `no-close-on-esc` and `no-close-on-backdrop` respectively.

https://bootstrap-vue.js.org/docs/components/modal#component-reference

**Comment by peterjcole** [comment]
@tmorehouse Is there a particular reason we don't at least have an `@esc` event? Having to use `@hide` makes the code unnecessarily complex and difficult to read, particularly if you're controlling the visibility with `:visible`, since the `@hide` will be emitted again once the prop changes.

You have to implement something like this, which is much more confusing and open to introducing bugs than simply being able to provide an event for `@esc`, in my opinion. What do you think?

```
    hideModal (event) {
      const triggeredByPropChange = !event.trigger;

      if (triggeredByPropChange) {
        // do the stuff to reset the component's state
      } else {
        event.preventDefault();

        if (['esc', 'cancel'].includes(event.trigger)) {
          // do the thing which changes the visibility
        }
      }
    }
```
