### ISSUE TITLE
b-form-select clears text values on select

### ISSUE THREAD

**Issue by flashybits** [bootstrap-vue/bootstrap-vue#3217]
I'm new to Vue so forgive me if I'm missing something...

I've re created the issue below at jsfiddle.

### Steps to reproduce the bug

Enter text into Title 1 & Title 2
make a selection from either dropdown or multi select and the text input fields data clears

### Expected behavior

Text input in the text fields should not be cleared when a select field is changed

### Versions

**Libraries:**

- BootstrapVue: https://unpkg.com/bootstrap-vue@2.0.0-rc.19/dist/bootstrap-vue.min.js
- Bootstrap: https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css
- Vue.js v2.6.10

**Environment:**

- Device: Mac
-  macOS Mojave
- Browser: Chrome]
- Version 73.0.3683.103 (Official Build) (64-bit)

### Demo link

https://jsfiddle.net/thatWebDude/bnzjwx50/11/

### Additional context

Add any other context about the bug here.

**Comment by tmorehouse** [comment]
First thing, switch to the latest Bootstrap CSS:

https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css

Second, you are not using `v-model` on the text inputs, so the value of hte text input is never saved into data.

Whenever you change the data, it is causing the app to re-render, and it sets the `<input>` `:value` back to what was in the original data fields array (which is nothing/undefined).  That is why you are seeing the text inputs reset when you change the select.

See updated working fiddle: https://jsfiddle.net/07mzguLr/

I've switched the inputs to use `v-model="field.value"` instead of `:value="field.value"`, and also defined `value` in the fields array for the text input entries (the value property has to exist when the app is initialize in order for the value to be reactive.

**Comment by flashybits** [comment]
Thanks for the fast reply, Updated in my project code and working a treat...
