### ISSUE TITLE
Modal lazy prop doesn't work as expected since rc.17

### ISSUE THREAD

**Issue by jojoob** [bootstrap-vue/bootstrap-vue#3251]
A modal with lazy prop will not be destroyed on hide since boostrap-vue version 2.0.0-rc.17. Before rc.17 the modal component was destroyed and removed from the DOM on hide with the lazy prop set.

Simple test:
```
<b-button v-b-modal.foo>Open Modal</b-button>
<b-modal id="foo" lazy>
  <b-form-checkbox>test</b-form-checkbox>
</b-modal>
```

1. Open the modal by clicking the button
2. check the checkbox
3. close the modal
4. reopen the modal

Expected: The checkbox should not be checked (initial state)
Since rc.17: The checkbox keeps its state because the modal is not destroyed

[Example with bootstrap-vue 2.0.0-rc.16](https://jsfiddle.net/Lk0adrmw/)

[Example with bootstrap-vue 2.0.0-rc.19](https://jsfiddle.net/6ugob34w/1/)

**Comment by tmorehouse** [comment]
This will be fixed in 2.0.0-rc.20 (which should be released this week), as all modals will be lazily rendered (except when the new `static` prop is used)

You can see a preview at https://deploy-preview-3168--bootstrap-vue.netlify.com/docs/components/modal/#lazy-loading-and-static-modals

And you can paste your modal HTML example above into the playground and see it work (with no need for the `lazy` prop, as it is ignored if the modal is not in `static` mode).

**Comment by jojoob** [comment]
@tmorehouse Thanks for the information and the quick response. :)
Off-topic, just a note on versioning: The pre-release label 'release candidate' (rc) suggests a nearly stable API to me. I would find "beta" or similar as the pre-release label more appropriate.

**Comment by tmorehouse** [comment]
v2.0.0-rc.20 has been released.
