### ISSUE TITLE
B-button disable fails

### ISSUE THREAD

**Issue by frbuceta** [bootstrap-vue/bootstrap-vue#3290]
### Describe the bug

B-button disable fails when there is a span inside.

```
<nuxt-link to="/route">
   <b-button disabled>
      A<span class="bc">BC</span>!
   </b-button>
</nuxt-link>
```

### Versions

**Libraries:**

- BootstrapVue: last
- Bootstrap: last
- Nuxt: 2.7.0

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: last

**Comment by tmorehouse** [comment]
`b-button` support links/router-link/nuxt-link

Try this:

```html
   <b-button disabled to="/route">
      A<span class="bc">BC</span>!
   </b-button>
```

`b-button` will auto-detect taht you are running under `nuxt` and will render a `<nuxt-link>` styled as a button.

**Comment by tmorehouse** [comment]
The following but of CSS wil also rectify the issue:

```css
.btn > *,
button > *,
a > * {
  pointer-events: none;
}
```

Which will ensure that the click event only ever originates from the `<button>` (or `<a>`) and not the inner content of the button. And since the button is disabled, it will not bubble any inner click events up the DOM tree.  See https://css-tricks.com/slightly-careful-sub-elements-clickable-things/
