### ISSUE TITLE
tabindex setter for dropdowns

### ISSUE THREAD

**Issue by luckylooke** [bootstrap-vue/bootstrap-vue#3299]
### Is your feature request related to a problem? Please describe...

When using input group with dropdown I want to have input autofocused and previous selectable by shift+tab I want to activate the dropdown, but I am not able to set tabindex on the button wrapped inside dropdown :/

### Describe the solution you'd like

I would like tabindex attribute to be forwarded from component to native button element inside dropdown

### Describe alternatives you've considered

Did not come to my mind any alternative

### Additional context

```html
   <b-input-group>
        <b-dropdown class="phone-prefix" :text="phonePrefix" slot="prepend" tabindex="1">
          <b-dropdown-item
            v-for="(prefix, index) in phonePrefixes"
            :key="index"
            @click="phonePrefix = prefix"
          >{{ prefix }}</b-dropdown-item>
        </b-dropdown>
        <b-form-input
          v-model="phone"
          class="phone-input"
          :placeholder="$t('phone-placeholder')"
          name="phone"
          autofocus
          autocomplete="phone"
          tabindex="2"
        />
      </b-input-group>
```
Thank you very much for your great work!
Happy coding :)

**Comment by tmorehouse** [comment]
Dropdown's appear in the normal document tab sequence (i.e. has the browser built in default of `tabindex="0"`)  Using tab indexes `> 0` is discouraged by WAIA ARIA as it can make it difficult for screen reader users.

Since the dropdown appears in the DOM before the input, they would naturally have the tab order of what you expect (shift tabbing from the input would focus the dropdown trigger button).

Setting a tab index of `1` or greater would place the controls at the very last of the page (i.e. after all navigation, links, buttons, etc that are in your document).

Note `autofocus` attribute doesn't always work as expected, especially if the control is added to the document *after* initial page load/render (i.e. because of route change, opening n a modal, etc)

**Comment by tmorehouse** [comment]
What you may be asking for is auto-opening of the dropdown when teh trigger button receives focus.  That currently is not supported (dropdowns will only open on click for accessibility reasons)

**Comment by luckylooke** [comment]
Ok, thank you for your response, I have rethinked tabindex usage, and in some cases it would be better to control tab order, because some controls between are for edge cases like "did you forget username" or "get help".. etc.. but I can manage it by script maybe. Will think about it later.
Thanks anyway for your time! 
Happy coding :)
