### ISSUE TITLE
`<b-pagination>` Should not go to the first page when page numbers change

### ISSUE THREAD

**Issue by lovanwubing** [bootstrap-vue/bootstrap-vue#3372]
I found the code in paginator.js
`watch: {
    numberOfPages(newVal) {
      if (newVal === this.localNumPages) {
        /* istanbul ignore next */
        return
      }
      this.localNumPages = newVal
      this.currentPage = 1
    }
  },`

Why you change currentPage to 1 when the numberOfPages is changed ?

Our use case is: delete all of data in current page, then I go to last page and fetch data again. The currentPage should keep the same as value model.

**Comment by tmorehouse** [comment]
It handles the cases where sorting has changed, the current page is now out of range, filtering changed, or the page size has changed (we have a similar check for changes in page size). This also handles when pagination is tied to a component such as b-table (i.e. filtering changes the number of items/rows, sorting was changed (etc).

There was actually a previous issue that we had to implement this in order to fix. I can't recall the issue number off hand, but it was related to controlling b-table, and similar custom components that implemented filtering, paging, etc.

**Comment by tmorehouse** [comment]
Typically the number of pages would change due to a data set change (not an infinite scroll type behaviour, which is what you are looking for).

In your case, before you fetch your data, store the page size, and current page, and once you have updated your data set set the values on b-pagination.

**Comment by tmorehouse** [comment]
Issue where we needed to reset the page number: https://github.com/bootstrap-vue/bootstrap-vue/issues/2987

**Comment by stefandesu** [comment]
One problem with this is that even when you keep your internal data structure on the correct page, the display of the pagination switches to page 1. What we were doing is to "deny" the page change (by using the @change event only and ignoring the @input event), but even though the data for the correct page was shown, the pagination displayed page 1. The only workaround I could find was to change the page to page 1 and on the next tick, change it back to the previous page so that b-pagination would reevaluate and show the correct page again.

Is there maybe a better way around this?

**Comment by arenddeboer** [comment]
I'm also fighting b-pagination from resetting my page number to 1.
Should not the user be responsible for this ?

**Comment by luchomatic** [comment]
Same problem

> I'm also fighting b-pagination from resetting my page number to 1.
> Should not the user be responsible for this ?

**Comment by tmorehouse** [comment]
@luchomatic which version are you using of BootstrapVue? b-pagination-nav will adjust the selected page number based on the current route or page URL. b-pagination will change to the first page under certain circumstances (i.e. the current page is greater than the number of pages, etc)

**Comment by luchomatic** [comment]
> @luchomatic which version are you using of BootstrapVue? b-pagination-nav will adjust the selected page number based on the current route or page URL. b-pagination will change to the first page under certain circumstances (i.e. the current page is greater than the number of pages, etc)

I was able to fix it, my problem was that I loaded the elements to paginate using ajax.

So when my content loaded, it would trigger a pagination pagesCount change, and then it will move the pointer to the first page. (which was my problem and the subject of this thread).

So to solve it I added a "v-if" condition on the paginator to only load it when the content to paginate is already there.

**Comment by stefandesu** [comment]
> So when my content loaded, it would trigger a pagination pagesCount change, and then it will move the pointer to the first page. (which was my problem and the subject of this thread).

The problem we are having is that the data which is used is constantly reloaded (let's say every 15 seconds) and the number of pages can change if entries were added or removed in the meantime. So if you only load your data once, you can "fix" it by using v-if on the paginator, but unfortunately, that doesn't fix my issue.

I would still like a way to disable this functionality so that I don't need my hacky workaround anymore (which I described in [my previous comment](https://github.com/bootstrap-vue/bootstrap-vue/issues/3372#issuecomment-497589331)).

**Comment by hktr92** [comment]
on the other hand, i'm working on a project where the client wants to reset the page to 1 when filters has changed. i'd like to have this feature documented somewhere, e.g. to let the user control the page change on various events (I'm already using [items provider](https://bootstrap-vue.org/docs/components/table#using-items-provider-functions) for loading server-side paged content).

my current "hack" is to register an `@input / @change` event to control this.
