### ISSUE TITLE
<b-modal> bv::hide::modal / $bvModal.hide  does not work if no id was explicitly set

### ISSUE THREAD

**Issue by Moorhuhnfreak** [bootstrap-vue/bootstrap-vue#3389]
### Describe the bug

If no id is set for `<b-modal>` neither `this.$root.$emit("bv::hide::modal", modalId);` nor `this.$bvModal.hide(modalId)` hides the modal, when passing the generic id, that was catched with `this.$root.$on("bv::modal::show", (ev, modalId) => {})`

### Steps to reproduce the bug

1. Create `<b-modal>` without id
2. Open modal and listen to the `bv::modal::show`-event to get the modal id
3. Try to close the modal with one of the methods explained before

### Expected behavior

The opened modal should hide, because we have a unique id that refers to the currently opened modal.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0.rc21
- Bootstrap: 4.#.#
- Vue: 2.6.10

### Demo link

[Demo](https://codesandbox.io/s/r8m3x)

**Comment by tmorehouse** [comment]
The auto-ID that is generated on the Modal (and other components like tooltips, popovers/tabs, dropdowns, etc) are mainly there for ARIA accessibility reasons, and may change throughout the lifecycle of the component.

Workaround: explicitly assign an ID to the Modal

**Comment by Moorhuhnfreak** [comment]
Adding an unique id to every modal can be quite cumbersome, especially, if you only need it for automatically closing the modal. So it would be nice, to use the generated id. I looked into the Id mixin and I think the id should keep constant while the modal is visible, as long as no id is passed to the modal id property.

Can't this easily be fixed by changing the hide handler in `components/modal/modal.js` from
```
  hideHandler(id) {
      if (id === this.id) {
        this.hide('event')
      }
    }
```
to
```
  hideHandler(id) {
      if (id === this.safeId()) {
        this.hide('event')
      }
    }
```
? Or do I miss something? Wouldn't that also be more consistent? Because it's a bit strange, that the safeId() is published via the show-event, but can't be used later on.

**Comment by tmorehouse** [comment]
The ID generated by `safeId()` might change....

We could add it, but cannot guarantee (in some situations) that it will be the same ID that is emitted by the show event by the time you get to the hide stage, unless you explicitly provide an ID.

safeID() returns `null` on the server side, and not until one nextTick _after_ mount (since we have to prevent SSR re-hydration errors) that an ID is created.  ID anything causes the component instance to be destroyed and re-rendered, the auto ID generated by `safeId` will change.
