### ISSUE TITLE
bootstrap-vue/nuxt - SyntaxError Unexpected identifier

### ISSUE THREAD

**Issue by ciarlystreet** [bootstrap-vue/bootstrap-vue#3397]
### Describe the bug

When i install a simple app with `npx create-nuxt-app` using bootstrap and start `npm run dev` command showing the error "SyntaxError - Unexpected identifier"

### Steps to reproduce the bug

1. `npx create-nuxt-app test`
2. **Use a custom server framework:** none
3. **Choose features to install:** all you wont or nothing
4. **Use a custom UI framework:** bootstrap
5. **Use a custom test framework:** none
6. **Choose rendering mode:** Universal
7. **Choose a package manager:** npm
8. `cd test/`
9. `npm run dev`
10. Go to http://localhost:3000/

### Expected behavior
I expected to see the Nuxt.js index page.

### Versions

**Libraries:**

- BootstrapVue: ^2.0.0-rc.11
- Bootstrap: ^4.1.3
- Nuxt: ^2.4.0
- cross-env: ^5.2.0
- nodemon: ^1.18.9

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome

**Comment by tmorehouse** [comment]
Try upgrading to:
- BootstrapVue version 2.0.0-rc.21
- Bootstrap version 4.3.1
- Nuxt version 2.7.1

**Comment by MateiNenciu** [comment]
I confirm this issue. Running npm run build and then npm run start works. Only npm run dev fails. I have all packages on the latest version.

**Comment by tmorehouse** [comment]
So it is only when running in `dev` mode then?

**Comment by MateiNenciu** [comment]
Yes only on npm run dev. I tried the rc20 version also and still fails. My setup is: Ubuntu 18.04, Google Chrome and Node v8.10.0.

**Comment by tmorehouse** [comment]
Is there any more info with the error (line number and/or filename possibly)?

**Comment by MateiNenciu** [comment]
![Screenshot from 2019-05-27 21-13-26](https://user-images.githubusercontent.com/15947673/58434467-7bc58b80-80c4-11e9-9e11-46b9cec146ad.png)
![Screenshot from 2019-05-27 21-13-52](https://user-images.githubusercontent.com/15947673/58434468-7bc58b80-80c4-11e9-924f-f06c8ae74a95.png)

**Comment by MateiNenciu** [comment]
I tried both adding boostrapvue from nuxt project generator command or adding the boostrap vue after setting up the nuxt and the result is the same. My package.json is: 

{
  "name": "xx-ui",
  "version": "1.0.0",
  "description": "Bla bla",
  "author": "Team",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server/index.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@nuxtjs/pwa": "^2.6.0",
    "bootstrap-vue": "^2.0.0-rc.21",
    "bootstrap": "^4.3.1",
    "consola": "^2.7.1",
    "cross-env": "^5.2.0",
    "express": "^4.17.1",
    "nuxt": "^2.7.1"
  },
  "devDependencies": {
    "nodemon": "^1.19.1",
    "@nuxtjs/eslint-config": "^0.0.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-standard": ">=12.0.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-compat": "^3.1.1",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-vue": "^5.2.2",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-loader": "^2.1.2",
    "@vue/eslint-config-airbnb": "^4.0.0"
  }
}

**Comment by tmorehouse** [comment]
OK we think we have figured out the issue... we are working on a fi now.

**Comment by tmorehouse** [comment]
We should hopefully have RC.22 out later today.

**Comment by tmorehouse** [comment]
Fix will be available in v2.0.0-rc.22 when released.

**Comment by tmorehouse** [comment]
One caveat... when not using the nuxt module, and importing components/plugins from the `es/` directory, the issue will crop back up again in dev mode, due to how Nuxt generates the server build (using `ExternalsPlugin` in the server webpack.config.js). ExternalsPlugin is configured to assume any module not directly listed in a node_module/package package.json (i.e. `main` or `module`) is a commonJS module (faster builds)... in which case the ES build is not (they are true ES6 modules using import/export).  Production mode is OK, as they do not use ExternalsPlugin in prod mode for both client and server (slower builds).

So we are in a bit of a catch 22 situation.  The Nuxt module is fixed, but the `es/` modules (if not importing all of bootstrap) will cause the error to re-occur during the server build (but not client build) when importing individual components or plugins.

Once can specify params to ExternalsPlugin to whitelist some modules and/or module dirs as being true ES6 modules, but unfortunately Nuxt doesn't expose the options for that plugin.

Switching the es modules to be CJS compatible would break tree-shaking (as named exports in CSJ aren't tree-shakable, not without a plugin like https://github.com/indutny/webpack-common-shake.

For users not using Nuxt, importing from the `es/components` modules will work fine.

**Comment by tmorehouse** [comment]
We will probably wait until Tuesday evening to push out the new release.

**Comment by thanosalexander** [comment]
Is there   any chance v22 to be released today?

**Comment by tmorehouse** [comment]
We are doing some comparisons between PR #3404 and #3408 to determine which produces the best tree-shakeability/dead code elimination.

So hopefully Wednesday we should have it ready.

**Comment by thanosalexander** [comment]
nice @tmorehouse ..  i hope nuxt will go on with this change :)

**Comment by tmorehouse** [comment]
Nuxt uses a package's esm build (if available) for client build and common.js for server build, which is what brought the issues around when we were trying to simplify the import of components, directives and plugins, by no longer converting the `es/` build into "mini" commonjs modules (i.e. we wanted to keep the import/export statements instead of converting them to `require` statements (which are not tree-shakeable by Webpack).

With the new PRs, we have brought all named exports to the top-level module (no more need to import form sub-directories).

The new import syntax is `import { ModalPlugin, BButton } from 'bootstrap-vue'` regardless if using common.js build or esm.js build.  We will leave the `es/` build directory there for backwards compatibility (deprecated), but the Nuxt module will be using the new import syntax, so it should benefit quite well with tree-shake (Webpack 4) and dead code elimination (terser/UgligyES).

**Comment by thanosalexander** [comment]
got it..thank you for info!!

**Comment by thanosalexander** [comment]
FYI
if you add it to build->transpile
```
 transpile: ['bootstrap-vue'],
```

problem bypassed

**Comment by tmorehouse** [comment]
@thanosalexander yeah, that is an option, or set `useTranspiled: false` in the `bootstrapVue` nuxt.config.js.

But it is not ideal, as it increases Nuxt's dev build times due to the transpiling of the source code each time.

**Comment by thanosalexander** [comment]
i realised it yes! just for someone who need to use it  , it's an  informal and temp solution!  thanks for adding me.. we hope for v22

**Comment by amdp** [comment]
> Yes only on npm run dev. I tried the rc20 version also and still fails. My setup is: Ubuntu 18.04, Google Chrome and Node v8.10.0.

my nuxt is working fine with rc.20

**Comment by tmorehouse** [comment]
v2.0.0-rc.22 has been released.

**Comment by thanosalexander** [comment]
> v2.0.0-rc.22 has been released.

Issue solved! 
No more undefined and no need to transpile
