### ISSUE TITLE
[b-link] absent href in current link.vue file

### ISSUE THREAD

**Issue by mosinve** [bootstrap-vue/bootstrap-vue#343]
```
<template>
    <a :is="componentType"
       :active-class="activeClass"
       :disabled="disabled"
       :aria-disabled="disabled ? 'true' : 'false'"
       :to="to"
       :exact="exact"
       @click="click"
    >
        <slot></slot>
    </a>
</template>
```
Href is lost somewhere... 
Maybe in vue-router enviroment it is a normal, but without vue-router - this is useless.

**Comment by KuroThing** [comment]
Using version 0.15.2, which should be the latest,
```html
<b-link href="testing">test</b-link>
```
works for me perfectly fine? It generates a url to `localhost/testing` as expected?

**Comment by mosinve** [comment]
a, yeah, true it works... i've got an error with dropdown item, as it depends on b-link and it href property, but b-link hasn't this prop

**Comment by mosinve** [comment]
b-link works b'cause Vue copy params defined at custom tag to resulting tag.

**Comment by KuroThing** [comment]
It was removed from b-link because of #331, which was preventing vue-router from working with objects, the error in #344 would be the fact that it's referencing a non-existent property now, and i would hazard to guess that the fix is as simple as removing `:href="hrefString"` from the dropdown link compontent, allowing the href to be passed manually if desired?

I guess this is a case where tests would have been handy to spot this issue when the changes for #331 were made :(

**Comment by mosinve** [comment]
If remove href from dropdown-item, it will never render as `<a>` in non-vue-router enviroment

**Comment by mosinve** [comment]
but this discussion is better continue at #344 thread :)
