### ISSUE TITLE
Give an example of how to add / remove / edit row / field in table

### ISSUE THREAD

**Issue by yudy-chen** [bootstrap-vue/bootstrap-vue#3517]
It's necessary to have an example of how to modify table content. Right now what I am doing is to shadow copy the array content of the table. Modify it then assign it back to original data binding.
I realize by doing this will not update the filter data. For example if you are currently filter the table with value "zero" and you modify one of your existing data that contain "zero" with "one". The UI will not show the item you just changed, but when you debug it for filtered data, it's still contain the item you changed with old data ("zero"). So actually how to proper change the data of table?

**Comment by tmorehouse** [comment]
All modifications to underlying table data should be performed on the original items array (if using local arrays, not the results of filtering, sorting or pagination. `b-table` caches results of filtering, sorting and pagination (as they are handled by chained computed Props: `items` => `filteredItems` => `sortedItems` => `paginatiedItems` => rendered view).

Usage of primary keys in your items array can greatly help with this (just like when using a database), to identify the original row that you are editing.

You also have to take in consideration of how Vue handles reactive data, epecially arrays (i.e. items) and objects (item row data).  Adding new properties to an object won't trigger Vue's reactivity, and sometimes, depending on how your data is set up, Vue won't be able to track changes to nested objects, which is why Vue has the `this.$set(...)` method (https://vuejs.org/v2/api/#vm-set) and `Vue.set(...)` method (https://vuejs.org/v2/api/#Vue-set).

If you want to ensure reactive changes are detected by Vue, use one of the `set` methods on the item data:

```js
// if `item` is a reference to a row's item data
this.$set(item, 'fieldname', newValue)
```

This will ensure Vue can see that the data has indeed changed and will trigger a re-render of the component.

**Comment by yudy-chen** [comment]
I tried below code to update one item
`that.$set(that.filteredItems[1], "Company", "HSP")`

But it's showing an error `Error: [vuex] Do not mutate vuex store state outside mutation handlers.`

So how actually it works to update the this item?

**Comment by tmorehouse** [comment]
Where is `filteredItems` coming from?  Vuex store / back end? the result of the filtered items from b-table?

If dealing with data in a store, you need to setup mutation handlers for you data.  https://vuex.vuejs.org/guide/mutations.html

If the data is coming from a back end, then you should `post` the data changes to the back end which then triggers a refresh of the items array.

**Comment by yudy-chen** [comment]
It's local data which referred from a function `onFiltered `when `@filtered` is triggered by b-table.

On another question may related with this.

When I debug the` that.$refs.tbSuppliers` and check manually for `filteredItems`, the item is updated.
But when I debug it by using `that.$refs.tbSuppliers.filteredItems` the data is still old one.

**Comment by tmorehouse** [comment]
filtered items is a **copy** of the displayed items, not references to the actual items in the table display.

All mutations should be performed on the **source** of the data, not the results of what the table is showing.

**Comment by tmorehouse** [comment]
What you are seeing is due to Vue's reactivity detection system.

**Comment by yudy-chen** [comment]
So in this case, how can I get real array data from actual display? Since actual display already changed.

**Comment by tmorehouse** [comment]
Without knowing your code or markup, it is hard to determine the best way to assist.

Would you be able to create a JSFiddle or CodePen with a minimal reproduction of your issue? you can get a jsfiddle or codepen template by exporting from the BootstrapVue docs playground.

**Comment by yudy-chen** [comment]
Here is the [https://codepen.io/anon/pen/mZVXPB?editors=1011]
Basically it has a Movie data. 

First when you filter the movie with keyword "Feige", it will shows "Avengers - Endgame"
The you click "Add Movie" it will add another movie "Avengers - Infinity War" with "Kevin Feige" as Producer.

After you add the movie, the UI already changed but in console, you can see before add and after add has the same value which only show End Game (for filtered data).

What I want to know is how to access / modifed the real filtered items from b-table without relying to get the initial data during onFiltered (I know I am doing wrong but I don't know how to do it right).

**Comment by tmorehouse** [comment]
Check out https://codepen.io/anon/pen/YowBGV?editors=1011

I wrapped the second `console.log` in the `addMovie()` method in a nextTick.  and the filtered data is correct.  This allows Vue time to handle all the reactive changes first (i.e. allows the `filtered` event to fire before logging the results.  Remember Javascript is synchronous... and runs the full `addMovie()` method before updating the table and firing the events.

**Comment by yudy-chen** [comment]
Ah, yes it works now. Thank you
