### ISSUE TITLE
theme-colors (sass function) is not working...

### ISSUE THREAD

**Issue by kangchals** [bootstrap-vue/bootstrap-vue#3578]
I want to use sass function theme-color from bootstrap but it is not working.

Can you help me to use it?

Most of bootstrap thing is working well now.

In my component, 

```
<style scoped lang="scss">
.publishing {
  color: theme-color("warning");
}
</style>
```

is not working like below

![image](https://user-images.githubusercontent.com/7294289/60228599-243a5b80-98ce-11e9-93d1-40faf7619788.png)

I include most of bootstrap thing like below

```
$theme-colors: (
  "primary": $customPrimaryColor,
);

@import '~bootstrap/scss/bootstrap.scss';
```

**Comment by tmorehouse** [comment]
In your scoped style, you need to import Bootstrap V4's variables, functions and mixins, otherwise it doesn't know what the function `theme-color` is.

As a simple alternative, you can use their CSS variables to get the colors:

```html
<style scoped lang="scss">
.publishing {
  color: var(--warning);
}
</style>
```

All bootstrap variants will be defined and loaded into the browser as CSS variables:

![image](https://user-images.githubusercontent.com/2781561/60228971-c1fc3f00-986a-11e9-98d1-eb8f43a6f7fe.png)

**Comment by kangchals** [comment]
for me two line are required and I used second way you provided. 
Thank you!!!
```
@import '~bootstrap/scss/_functions.scss';
@import '~bootstrap/scss/_variables.scss';
```
