### ISSUE TITLE
[list-group-item] "to" not working when prop "button" is set

### ISSUE THREAD

**Issue by ggedde** [bootstrap-vue/bootstrap-vue#3594]
When using the list-group-item and setting "button" the "to" method does not work.
It does work when I remove the "button" prop.

I would expect the "to" method to work when setting the list-group-item to button.  Both button and link components support the "to" method so I would expect it to also work regardless of the setting on list-group-item.

- BootstrapVue: 2.0.0-rc.24
- Vue: 2.6.10

MacOS: 10.14.2 (18C54)
Chrome: 75.0.3770.100

**Comment by tmorehouse** [comment]
`b-button` supports generating links (or router-links) that **look** like buttons (but actually render a link tag not a button tag).

In the case of `list-group-item` the `button` prop tells it to render an actual `button` element instead of a `link` (`<a>`) element.  It wouldn't make sense to place a `href` onto a native `button` element.

**Comment by ggedde** [comment]
@tmorehouse, Thanks.
Removing button for native "to" items and leaving button for @click events works.
Maybe some clarification in the docs might be good :)

**Comment by tmorehouse** [comment]
Actually it is documented: https://bootstrap-vue.js.org/docs/components/list-group#actionable-list-group-items

> Or if you prefer `<button>` over links, set the `button` prop to true.

> **Notes:**
> - When the prop `button` is true, all link related props (other than `active`) and the `tag` prop will have no effect.
> - When `href` or `to` are set, the tag prop has no effect.

**Comment by ggedde** [comment]
ok, totally missed that.
Thanks
