### ISSUE TITLE
Tooltips broken on dropdown

### ISSUE THREAD

**Issue by ericuldall** [bootstrap-vue/bootstrap-vue#3703]
### Describe the bug

When trying to add a tooltip to a drop down menu, the tooltip will move behind the menu on click (should dissappear), then move back in front of the menu when you hover over the menu items (should not be displayed).

### Steps to reproduce the bug

```
<b-dropdown variant="link" v-b-tooltip.hover.bottom title="My Dropdown" id="my-dropdown">
    <template slot="button-content">
        My Dropdown
    </template>
    <b-dropdown-item>Item 1</b-dropdown-item>
    <b-dropdown-item>Item 2</b-dropdown-item>
</b-dropdown>
```

### Expected behavior

The expected behavior is that the tooltip should only show when hovering over the dropdown button, not when hovering over the menu items.

![image](https://user-images.githubusercontent.com/3223296/61405663-35ec9e80-a88f-11e9-8465-676d810c511d.png)

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.14
- Bootstrap: 4.3.1
- Vue: 2.6.8

**Environment:**

- Device: Macbook Pro
- OS: Mojave
- Browser: Chrome
- Version: 75.0.3770.100

### Additional context

I think a good fix that will allow better customization of the dropdown could be to allow full access to use a custom button, rather than just a <slot> for the button text. If we could use a custom button, we could simply add the tooltip directive to the button instead of the entire dropdown element.

**Comment by tmorehouse** [comment]
The reason the tooltip moves is because the menu is inside the root wrapper div element.

It wouldn't be easy to allow a custom button, as we need to be able to bind event listeners to the button, and since we wouldn't be controlling the button (or even know if it rendered at all) we couldn't add the event listener to it, nor set the disabled state when the dropdown is disabled.

Tooltips listen for bubbled up events on the element they are applied to (so we can handle when elements inside the trigger element are hovered).

We might be able to add in a filter on the events (for tooltip/popover) to see if they are triggered on children of a `dropdown-menu` container, and ignore them.

**Comment by ericuldall** [comment]
I think that would be a reasonable solution. Not sure if it's too opinionated, but I can't imagine a case where someone would want the current behavior.

**Comment by tmorehouse** [comment]
Bootstrap v2.0.0-rc.27 has been released

**Comment by nevcos** [comment]
The issue kind of persists, but instead of showing the bootstrap tooltip, shows the browser tooltip.

As a workaround, I suggest adding an empty element with the tooltip, and make it occupy the whole space:
```
// html:
<template #button-content>
  <icon name="toggle"/>
  <div class="__toggle-tooltip" v-b-tooltip title="Toggle menu"></div>
</template>

// css:
dropdown-toggle[aria-expanded="false"] > .__toggle-tooltip {
  position: absolute;
  top: 0; left: 0; bottom: 0; right: 0;
}
```
