### ISSUE TITLE
[b-form-checkbox] Add option to modify checkbox size

### ISSUE THREAD

**Issue by hoanghaithanh** [bootstrap-vue/bootstrap-vue#3745]
### Problem

There is no option to customize the checkbox size. The default size is quite small, it may hurt the user experience.

### Preferable solution

It would be great if it has property that set the size of the checkbox when init b-form-checkbox.

**Comment by tmorehouse** [comment]
This is an upstream issue with Bootstrap v4.3 SCSS (sizing for custom checkboxes/radios/file-input.

It is being addressed in Bootstrap v5.0 (by switching the SCSS sizes of the custom control indicators to `em` units rather than explicit `rem` units, so that they will scale with the base font size of the input.
