### ISSUE TITLE
Best way to sort table by formatted date field 

### ISSUE THREAD

**Issue by mayous83** [bootstrap-vue/bootstrap-vue#3755]
Is there a way to sort a table for a date field formatted (date is formatted in IT locale DD/MM/YYYY) ? I saw the Sort-compare routine but I indend that I should rewrite sort comparison for all fields, is that right? In this case what is the best way to get the table sorted with bootstrap-vue? Thanks.

**Comment by tmorehouse** [comment]
The custom sort-compare routine can be _selective_ as to what it is comparing, and if the custom sort routine doesn't want to handle sorting for a particular field it can return `false` or `null` to tell b-table to use it's internal sort-compare routine (i.e. fall back to built in sort-compare).

Note this only applies when b-table is doing the sorting (i.e. passed an array of items, rather than an items provider function).

Example.  if you have a field called `date`, which is stored as a string in the `dd/mm/yyyy` format, and have b-table handle comparing all other fields:

```html
<template>
  <b-table :items="items" :fields="fields" :sort-compare="myCompare">
  </b-table>
</template>

<script>
export default {
  data() {
    return {
      fields: [
        { key: name, label: 'Name', sortable: true },
        { key: date, label: 'Date', sortable: true }
      ],
      items: [
        { name: 'Jack', date: '29/12/2001' },
        { name: 'Jill', date: '14/04/2012' },
        { name: 'Bob', date: '07/07/2009' }
      ]
    }
  },
  methods: {
    myCompare(itemA, itemB, key) {
      if (key !== 'date') {
        // If field is not `date` we let b-table handle the sorting
        return false
      } else {
        // Convert the string formatted date to a number that can be compared
        // Get the values being compared from the items
        let a = itemA[key]
        let b = itemB[key]
        // Split hem into an array of parts (dd, mm, and yyyy)
        a = a.split('/')
        b = b.split('/')
        // convert string parts to numbers
        a = (parseInt(a[2], 10) * 10000) + (parseInt(a[1], 10) * 100) + parseInt(a[0])
        b = (parseInt(b[2], 10) * 10000) + (parseInt(b[1], 10) * 100) + parseInt(b[0])
        // Return the comparison result
        return a - b
      }
    }
  }
}
</script>
```

**Comment by miklagard** [comment]
In case of null date, we can make this control too:

            myCompare(itemA, itemB, key) {
                if (['date_joined', 'last_login'].indexOf(key) > -1) {
                    let a = (itemA[key] === null?'00.00.0000':itemA[key]).split('.');
                    let b = (itemB[key] === null?'00.00.0000':itemB[key]).split('.');
                    return parseInt(`${a[2]}${a[1]}${a[0]}`) - parseInt(`${b[2]}${b[1]}${b[0]}`);
                } else {
                    return false;
                }
            }
