### ISSUE TITLE
Allow form options to render accessibility attributes

### ISSUE THREAD

**Issue by nborko** [bootstrap-vue/bootstrap-vue#3771]
Currently, it's not possible to add attributes like `aria-label`, `aria-describedby`, `title`, etc. to form options used in a select or radio group.  You can put `aria-label` on a single radio button, for example, but not as part of an options array passed to a radio group.

Inline HTML via the `html` attribute can partially address this problem, but a class like `sr-only` won't work in an `<option>` tag, and data would always have to be manually HTML-escaped.

Trying to guess every possible accessibility use case for such elements is difficult, as there are a lot of edge cases. Instead of trying to anticipate attribute usage by supporting specific properties (e.g. `ariaLabel`), perhaps a single `attributes` object, as an optional property of an option object, could allow defining any and all possible HTML attributes one might want to use on whatever element the option renders as. For example:

```javascript
{
    text: 'A',
    value: 1,
    attributes: {
        'aria-label': 'The letter A'
    }
}
```
In the context of `<b-form-select>`, the attributes could simply be added to the `<options>` tag:
```html
<option value="1" aria-label="The letter A">A</option>
```
In the context of `<b-form-radio-group>`, the keys of `attributes` could be checked against valid properties for a `<b-form-radio>`, which includes `aria-label` and `aria-labelledby`.

I love BV for it's first class support of accessibility, and this addition could help fill a void in that support.

**Comment by tmorehouse** [comment]
Interesting idea...

I can definitely see it's use with selects.  With `b-form-checkbox/radio` (specifically when using the group components), one has to be careful with `aria-label`, as it can override the actual label associated with the input (as the components have labels in them).

Most screen readers, if they see `aria-label` and a label (associated either via the label's `for` attribute, or a wrapped label around the input), `aria-label` takes precedence, and the other labels will be ignored by screen readers. Similar for  `aria-labelledby`, it will override any label element and/or `aria-label` (`aria-labelledby` does support specifying multiple IDs that will label the element though, so it could technically point to a radio-group's label (if it has one) plus the label associated with the input).

**Comment by tmorehouse** [comment]
We could ad in support for aria-label (I'm a but timid about allowing any attribute) which would be used by select, but ignored by `b-form-radio-group` and `b-form-checkbox-group`.  However, we might be able to add in props for b-form-radio/checkbox-group for adding an extra `aria-labelledby` (or potentially `aria-describedby`) that allows the extra context for a radio group ie. associating each child input with a `legend` as well as it's label)

Another option is to render the options, radios, check using `v-for` instead of the `options` array, which does allow for more greater flexibility with how the inputs are rendered.  PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3754 ensures that any non-prop attributes on b-form-radio/check are transferred to the underlying input element (since they are wrapped in an outer div).  This PR will be available in the next release.

**Comment by nborko** [comment]
In my experience screen readers are fickle beasts. While most of the time they work as expected, their behavior varies from browser to browser, and sometimes just flat out refuse to produce the right user experience.

I understand the reluctance to allow any attribute to filter down to the option tag. A simple filter that removes any of the 4 attributes allowed on `option` seems like a good idea, but other than that, I can't off the top of my head think of any global attribute that would negatively impact the model. If someone was daring/foolish enough to try to add an `onclick` attribute or some such thing, well that's on them. It's certainly not the only way you can do something foolish, and for the other 99.99% of us, this solution is far easier than traversing DOM elements in `mounted()`.

**Comment by tmorehouse** [comment]
adding in support for `ariaLabel` in the options array wouldn't be too bad (with note that it will override the default text/label for screen reader users... so should be used with caution). `aria-describedby` doesn't make much sense on `options`, as the select itself can have an `aria-describedby`/`aria-label` attributes (which implies association with the child options).

For radio-groups and check groups, one can place child `b-form-radio` and `b-form-checkbox` inside them, rather than using the `options` array, so it is easy to add any special case attributes to the inputs as needed (basically the group, when given options array, does a `v-for` to render the children). Similar can be done for `b-form-select` (`options` prop is not required)

```html
<h4 id="some-id">Some descriptive text</h4>
<b-form-radio-group name="foo" v-model="bar">
  <b-form-radio
    v-for="(option, index) in myOptions"
    aria-describedby="some-id"
    :key="index"
    :value="option.value"
  >{{ option.text }}</b-form-radio>
</b-form-radio-group>
```

**Comment by nborko** [comment]
Also, allowing `title` would be helpful in options in `select` with `size`>1, where the width of the select box is smaller than the width of the option (a lot of cases in the work I've done). It's fairly trivial to put a `ref` on the `b-form-select` and traverse the options to put a title on them when rendered, and then put a watch on the options array, but it's fairly tedious.

**Comment by tmorehouse** [comment]
I'm not sure why you need to do the `$refs` thing when you could do it via the above example.

**Comment by nborko** [comment]
Sorry, I did miss your comment about using `v-for`. End of week rush. Somehow I totally flaked on the whole notion of using the slot.

**Comment by nborko** [comment]
It looks like PR #3754 and `v-for` do address my issue. OK to close, thanks.

**Comment by tmorehouse** [comment]
With `b-form-select` and using native `<option>` elements in the default slot, you can do what you need today (without the above mentioned PR).  For checkboxes and radios, you will need the PR.
