### ISSUE TITLE
Broken "selective import" anchor link in Docs > Getting Started

### ISSUE THREAD

**Issue by pachiraDIG** [bootstrap-vue/bootstrap-vue#3809]
### Describe the bug

In docs, anchor link for "selective import" points to a missing section in "Getting Started" > "Tree shaking with Nuxt.js".

Can anyone provide simple and straightforward instructions on how to implement either the full library or select components/directives for _specific pages only?_

Thanks

**Comment by tmorehouse** [comment]
Thanks for pointing out the broken link. The link has been fixed in the `dev` branch.

It should have been pointing at https://bootstrap-vue.js.org/docs#tree-shaking-with-module-bundlers (**Tree shaking with module bundlers**). That section shows how to import components and plugins individually.

You can see the `dev` branch docs at https://bootstrap-vue.netlify.com/docs/

If you want to use the full plugin for a specific page in your app:

```js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)
```

Note that even though it is imported for this single page, once it is loaded it will be available in other pages (once the user navigates away from the page).

You can `Vue.use(BootstrapVue)` on any page that needs BootstrapVue components/plugins.  Not that Vue will only install the plugin once (it automatically detects if the plugin has already been installed)

Similar if you are importing only a subset of component group plugins.

```js
import Vue from 'vue'
import { ModalPlugin, LayoutPlugin } from 'bootstrap-vue'

Vue.use(ModalPlugin)
Vue.use(LayoutPlugin)
```

**Comment by pachiraDIG** [comment]
This is a huge help. I didn't think it would be so easy.

Thanks much!


[image: Pachira]

Brendan Dolan
Founder | Designer | Developer
(760) 813-5693 <+1-760-813-5693>
[image: Pachira] <https://www.pachira.site/>

Send a friend to Pachira! Once we kick off our 1st project with them, you
get an Amazon gift card (up to $100).
Interested? Just ask for more details.
Only need copywriting? Say hi to Kung Fu Copy. <https://kungfucopy.com/>
