### ISSUE TITLE
BV does not follow Vue global name/function plugin convention

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [bootstrap-vue/bootstrap-vue#3849]
BV exposes itself:

1. as `window.bootstrapVue`, not as `window.BootstrapVue`

compare `global.VueRouter = factory()`
https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.js#L9

vs `global.bootstrapVue = factory()`
https://unpkg.com/browse/bootstrap-vue@2.0.0-rc.27/dist/bootstrap-vue.js

2. another inconsistency: function vs object
```
VueRouter
ƒ VueRouter (options) {
  if ( options === void 0 ) options = {};
  this.app = null;
  this.apps = [];
  this.options = options;
  this.beforeHooks = [];
  this.resolveHooks = [];
  this.afterHooks = …
```
```
bootstrapVue
{install: ƒ, setConfig: ƒ}
```
3. that brings in needless confusion :-)

**Comment by tmorehouse** [comment]
The global name being `window.bootstrapVue` is a legacy name (been htat way since before I started with the project), although we may consider adding in a PascalCase version (create both for backwards compatability).

Vue supports both object and function for plugins, and Vue's doc's actually provide examples in the object format: https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin

Object and Function as plugins are acceptable to Vue. so I don't see a need to change from passing Function vs Object as the plugin (an the former actually has benefits when creating the CommonJs bundle version)

**Comment by Andrei-Pozolotin** [comment]
#3850 looks good, thank you

**Comment by tmorehouse** [comment]
@Andrei-Pozolotin Note that `VueRouter` is also a constructor function (technically it is a `class` creator), for creating a router instance to pass to an app.  While it is a function, Vue, when one does `Vue.use(VueRouter)`, sees it an an `Object` with an `install` property (functions and classes in JavaScript are actually based on the Object prototype).  

Vue first inspects the passed plugin as an `Object` and looks for an `install` property, and if found executes it, otherwise if it sees the plugin as a `Function` without an `install` property it assumes the function is the installer (which it is not in the case of VueRouter)

The BootstrapVue plugin is not a constructor (one doesn't use `foo = new BootstrapVue()`), hence it is a plugin `Object` with an `install` property.

**Comment by Andrei-Pozolotin** [comment]
ok, clear, thank you
