### ISSUE TITLE
2.0.0 stable - Fixes, Breaking changes, Deprecated features removal Tracking

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#3885]
**Please see https://bootstrap-vue.js.org/docs/misc/changelog for a list of breaking changes (plus features and fixes) in the 2.0.0 stable release.**

Please note we have had to change the new table slot syntax introduced in 2.0.0-rc.28 due to [limitations on Vue's new `v-slot` syntax](https://github.com/vuejs/rfcs/pull/2#issuecomment-521420394) that makes slot names _less_ flexible (and not conducive to table field keys names that are beyond the control of the user). This affects users of scoped header, footer and data field slots.

**Comment by vesper8** [comment]
when will deprecations be absolute? Will it happen with the release of 2.0 ?

For example my app heavily depends on b-tabs now deprecated href attribute and replacing it with b-nav is not at all working since I am using b-tabs in combination with keyboard navigation and v-model=tabIndex, both of which do not seem to be supported by b-nav

I would like to keep using this deprecated feature and need to know if I'll be able to upgrade to 2.0 stable or not

**Comment by tmorehouse** [comment]
@vesper `<b-tabs>` was never intended to be a component that changes routes or URLs.  Using `<b-nav>`  combined with `<router-view>` (or a `<nuxt-child>`, or `<component :is="foo">`) is a better solution.

The deprecation warning in `<b-tabs>`/`<b-tab>` has been since many versions ago (you should have been getting console warnings when using the deprecated 'href' prop).

**Comment by tmorehouse** [comment]
The above changes have been implemented in the `dev` branch which 2.0.0 stable will be released. It is the next release.

**Comment by vesper8** [comment]
Regarding the custom attributes. This used to work (around RC 14)

```
  <b-modal
    :id="id"
    :data-cy="someProp + '-modal'"
    v-model="shown"
    :size="modalOptions.size"
    :lazy="true"
    scrollable
    :hide-header="true"
    :hide-footer="true"
    @show="beforeShown"
    @shown="onShown"
    @hide="beforeHidden"
    @hidden="onHidden"
  >
      <slot />
  </b-modal>
```

where data-cy is a simple string that allows me to target the element using Cypress. Sometime since RC14 this stopped working and I've looked at the element source using the Chrome inspector and I indeed to not see any data-cy attribute added on any element anymore

I've tried adding data-cy (computed or not) on b-tab elements and again it doesn't seem to add the attribute, it just ignores it

For the b-modal example above I've resorted to adding an additional div like so:

```
  <b-modal
    :id="id"
    v-model="shown"
    :size="modalOptions.size"
    :lazy="true"
    scrollable
    :hide-header="true"
    :hide-footer="true"
    @show="beforeShown"
    @shown="onShown"
    @hide="beforeHidden"
    @hidden="onHidden"
  >
    <div :data-cy="`${someProp}-modal`">
      <slot />
    </div>
  </b-modal>
```

Regarding the b-tabs.. I understand that perhaps it wasn't intended that way, but I developed a use-case personally where switching tabs did modify the hash in the url, and reloading the page did manage to remember which tab you were last on, thanks to the hash. Furthermore I enhanced this further by using tabIndex and keyboard navigation, two things that aren't supported with the b-nav "alternative"

I've come up with a workaround so I can continue using b-tabs which looks something like this:

```
    <b-tabs
      v-model="tabIndex"
      @input="tabInput"
    >
      <b-tab
        :title="`${this.$i18n.t('JSON.leaderboard')} (${currentSeason})`"
        :active="!$route.hash || $route.hash === '#leaderboard'"
        @click="$router.replace('#leaderboard')"
      >
        some more content
      </b-tab>
      <b-tab
        href="#latest-results"
        :title="`${this.$i18n.t('JSON.latest-results')} (${currentSeason})`"
        :active="$route.hash === '#latest-results'"
        @click="$router.replace('#latest-results')"
      >
        some content
      </b-tab>
    </b-tabs>
```

**Comment by tmorehouse** [comment]
@vesper8 regarding teh modal attributes.  PR https://github.com/bootstrap-vue/bootstrap-vue/pull/3921 fixes that issue by ensuring any extra non-prop attributes are transfered to the wrapper element.

This was due to the portalling of the modal (the attributes were being applied to the root element, which in the case of a non `static` modal was the portal source element (which is an HTML comment node).

**Comment by chojnicki** [comment]
What's expected release date, or at least month? More like August or September?

**Comment by tmorehouse** [comment]
Hopefully this coming week.  Just finishing up the tooltip/popover revamp.  and once ready will be released.

**Comment by chojnicki** [comment]
It's have been two weeks, any news?
