### ISSUE TITLE
B-Table selectable

### ISSUE THREAD

**Issue by XpamAmAdEuS** [bootstrap-vue/bootstrap-vue#3901]
Is it possible to use b-form-checkbox for selecting/unselecting rows?

Also selectall/unselect all in head using b-form-checkbox.

Can u plz provide example Thx.

**Comment by tmorehouse** [comment]
For select and unslect all, there are two methods available that you can tie to click handlers (or similar)

```html
<template>
  <b-table ref="myTable" .... >
    <!-- slots here -->
  </b-table>
</template>
<script>
export default {
  methods: {
    selectAll() {
      // Selet all rows
      this.$refs.myTable.selectAllRows()
    },
    unselectAll() {
      /// unselect all rows
      this.$refs.myTable.clearSelected()
    }
  }
}
</script>
```

Since row selection/deselection are click driven (it listened for row-clicked events), you can place a _disabled_ checkbox in each row, that is tied to the row's scoped property `rowSelected`. teh checkbox would need to be disabled in order to allow the click on the chekbox to fallthough the input into the row.  So basically the checkbox is presentational only (so you should probably put the attribute `aria-hidden="true"` on the checkbox
