### ISSUE TITLE
Table with side headers

### ISSUE THREAD

**Issue by ImmanuelKannan** [bootstrap-vue/bootstrap-vue#3916]
It would be cool to have a configuration for b-table where the headers are on the left or right side of the table rather than the top. It would help when trying to make a comparison table, for example.

Thanks very much!

**Comment by tmorehouse** [comment]
You can set a column (field definition) to render a `th` in the body rows instead of a `td`, via the field definition `isRowHeader: true`.

https://bootstrap-vue.js.org/docs/components/table#field-definition-reference

Alternatively, you can use the `b-table-simple` component and render the table contents as you like.

https://bootstrap-vue.js.org/docs/components/table#simple-tables

**Comment by ImmanuelKannan** [comment]
Thanks very much, @tmorehouse !
