### ISSUE TITLE
b-table v-slot:[] syntax supported?

### ISSUE THREAD

**Issue by fretfan** [bootstrap-vue/bootstrap-vue#3924]
https://bootstrap-vue.js.org/docs/components/table/#scoped-field-slots

Having issue when styling each cell in b-table via slot with new slot syntax, introduced in Vue 2.6

When using old slot syntax everything works fine:
`<template slot="[]" slot-scope="data">
        <i>{{ data.value }}</i>
</template>
`

When using new slot directive syntax - changes are not applied:
`<template v-slot:[]="data">
        <i>{{ data.value }}</i>
</template>
`

It seems to clash with Vue's Dynamic slot names
https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names

Full example in my repo:
https://github.com/fretfan/vb-vslot-bug/blob/master/src/App.vue

Or am I missing something from docs?

**Comment by Hiws** [comment]
You are correct.
The new bracket syntax does not work with v-slot.
That's why it's changing (again) in the 2.0.0 release.

`
b-table and b-table-lite: table cell field, header and footer slot naming convention has changed. Users should be using the new table square bracketed slot naming syntax. Use slot cell[field] instead of field, head[field] instead of HEAD_field, use foot[field] instead of FOOT_field. The changes were required for better compatibility with the new Vue v-slot syntax. Note that head, foot and cell must be lower case.
`
Taken from https://github.com/bootstrap-vue/bootstrap-vue/pull/3862

**Comment by tmorehouse** [comment]
There are issues/limitations with the new `v-slot` syntax in 2.6+ with names (compared to the deprecated `slot`):

- potentially the loss of name case sensitivity (when using x-template or in-browser DOM templates, the browser lower cases all attributes when Vue parses the template)
- spaces are no longer work in slot names (unless stored in a variable)
- names can no longer start with a `[` (unless stored in a variable)
- and a few other issues

**Comment by fretfan** [comment]
Thank you for quick reply. I got answers, closing this issue

**Comment by tmorehouse** [comment]
@fretfan you can take a peek at the new documentation (for the forthcoming 2.0.0 release) at https://bootstrap-vue.netlify.com/docs/components/table
