### ISSUE TITLE
b-modal immediately mounted? not lazy?

### ISSUE THREAD

**Issue by vesper8** [bootstrap-vue/bootstrap-vue#3969]
I'm using RC28 and noticing that all my modals  (14 of them on a page) are all immediately mounted even though I was setting the lazy flag to true. It says in your docs that they are lazy by default though. They are immediately mounted.. is this intended?

**Comment by tmorehouse** [comment]
Are they showing in the DOM? or are you just seeing that the content is being "accesed" by Vue?

Modals are indeed mounted, but mounted as an HTML comment node. The modal content is not mounted until the modal is opened, unless the `static` prop has been set on `b-modal`.

**Comment by tmorehouse** [comment]
Note the `lazy` prop only works when the `static` prop is also set.  When neither are set then the modal should always be lazy (and mounted appended to the body when opened)

**Comment by vesper8** [comment]
Hi @tmorehouse, yes I understood about lazy being the default and the flag only being required if also using the static flag.

They are not showing in the DOM no, however the vue lifecycle hook `mounted()` gets triggered immediately. So I'd say it's like a half-half lazy? The template is not rendered but I usually tend to put bus event listeners and things of the likes inside my component's `mounted()` but it doesn't work in this case since it gets done for all modals even those that will never be used during the current user session

unfortunately there isn't a "rendered" lifecycle hook. Maybe there's another way. Right now I've moved things into the 
```
    @show="beforeShown"
    @shown="onShown"
    @hide="beforeHidden"
    @hidden="onHidden"
```

events of the b-modal

Just though it was odd that they all get mounted right away

On a typical component if you do something like `v-if="false"` -> `v-if="true"` only then does the `mounted()` hook trigger so I thought lazy components would work the same?

**Comment by tmorehouse** [comment]
The modal instance is mounted (as it needs to be able to listen for `$root` events to trigger opening, and to emit events on itself - `show`, `shown`, etc, as well as sync the 2-way props and v-model), but renders as a placeholder node (`<!---->`).  To the `hook:mounted` event does get triggered as soon as the DOM is rendered.

The `v-if` only works for parent components mounting a child.  Modal can't do that on itself (we do use an `if` to render either the modal structure or the placeholder node, but the component still mounts on a dom node in order to instantiate itself).

Perhaps some clarification in the docs mentioning the rendered _content_ is "lazy".

The `@show` event and `@shown` events are your best bet
