### ISSUE TITLE
<b-table>: selection cleared when paginating

### ISSUE THREAD

**Issue by pibi** [bootstrap-vue/bootstrap-vue#4015]
### Describe the bug

Missing previously selected rows when navigating a paginated table

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/ae8fd0uz/
2. Click on the first row, it should be selected now
3. Go to page 2
4. Go back to page 1

### Expected behavior

The selected row should be displayed as selected

### Versions

**Libraries:**

- BootstrapVue: latest
- Bootstrap: latest
- Vue: latest

### Additional context

I read the note which describe this behavior in the documentation, while compiling this bug report.  So, if this wont be fixed, I would rather see this more "empathized" in the doc itself or in the issue tracker (which will be auto-resolved once this is submitted 😏 )

**Comment by tmorehouse** [comment]
The problem is that b-table isn't always responsible for paging.  paging can be performed servers side in external JavaScript, so b-table might only know about the items that are currently shown only, and would not be able to maintain state with server side pagination or external client side pagination.  There would be a difference in how selection works depending on how the items array is delivered to b-table, providing for inconsistent user experiences.

**Comment by pibi** [comment]
Sorry, I just found this is a duplicate of #3508 . Closing the issue.

**Comment by allaghi** [comment]
you can put checkbox in field of the table, and then insert each selected row id into array like this

```
onRowSelected (value, index, item) {
      var loadedArray = []
      if (parseInt(value) === 1) {
        if (!(value in loadedArray)) {
          loadedArray.push(item.id)
        }
        // select = parseInt(value)
      }
      if (parseInt(value) === 0) {
        loadedArray.splice(loadedArray.indexOf(item.id), 1)
      }
      console.log(loadedArray)
    },
```

**Comment by allaghi** [comment]
I did some changes in this code I will post it
