### ISSUE TITLE
‹ , ›  become â€¹, â€º  and «, » become Â«, Â» in pagination when my project is in production and deployed to my hosting

### ISSUE THREAD

**Issue by arga1234** [bootstrap-vue/bootstrap-vue#4095]
I dont know what happen with this arrow inside the pagination, it is work fine when I develop on development mode in my browser such as firefox & chrome, but when it goes to production mode and had deployed on my hosting. It works fine on Firefox but at Chrome and Safari the arrow will gonna be like what I write in the title. Thankyou for your attention 

Here it is capture that I can show you
![Capture](https://user-images.githubusercontent.com/33050211/64906426-a4739e80-d710-11e9-9638-f51d3fde6fb4.PNG)

**Comment by tmorehouse** [comment]
Which version of BootstrapVue are you using? There was a prior issue https://github.com/bootstrap-vue/bootstrap-vue/issues/3179 with the encoding of the bookend buttons, which should have been fixed in [`2.0.0-rc.20`](https://bootstrap-vue.js.org/docs/misc/changelog#v200-rc20) by switching the default values to their unicode escape sequences

Does you page include the charset meta in the head: `<meta charset="utf-8">`?

**Comment by arga1234** [comment]
Ty for your respon, the problem is  google chrome and safari cannot render that sign properly, it will render the wrong sign like what I say in the title

**Comment by tmorehouse** [comment]
I have no issues with the correct unicode symbol being rendered with the latest Chrome.

Those symbols you are seeing would be only if the browser doesn't see the page character set as being `UTF-8` (unicode), and assumes `ASCII` (which doesn't support unicode characters, which will render two symbol characters instead of a single symbol)

**Comment by bmkopp10** [comment]
I'm having this same problem.  

I'm using bootstrap: "^4.4.1" and bootstrap-vue:  "2.21.2",

The issue only occurs in production.  This was my temporary fix until the issue is resolved. 

`<b-pagination
                      :total-rows="state.totalRows"
                        :per-page="state.perPage"
                        v-model="state.currentPage"
                        class="my-0"
                        :first-text="'\u00AB'"
                        :prev-text="'\u2039'"
                        :next-text="'\u203A'"
                        :last-text="'\u00BB'"
                    />`
