### ISSUE TITLE
Bootstrap-vue compile scss for lighten it

### ISSUE THREAD

**Issue by astroVibes** [bootstrap-vue/bootstrap-vue#4102]
Hello guys,
I state that I did not seem to see similar issues, i need to lighten up the CSS file, normally I do it without commenting and compiling but with Nuxt Js I can't / don't know how to do it, someone can help me?

**Comment by tmorehouse** [comment]
Are you referring to "lightening" up the colors, or reducing the CSS file size?

**Comment by astroVibes** [comment]
yes I had not specified, to reduce the weight "removing" the unnecessary components, I tried to follow the commands in the bootstrap package but they do not work

**Comment by tmorehouse** [comment]
For reducing the CSS, it is not an easy task unfortunately, due to the way Bootstrap has their SCSS/SASS files structured.

It is possible to create your own Bootstrap SCSS file that includes only certain sub-files of their SCSS.

https://github.com/twbs/bootstrap/tree/v4-dev/scss

https://getbootstrap.com/docs/4.3/getting-started/theming/

Once you create the SCSS file, then you would need to include that file, along with BootstrapVue's source SCSS file (/src/index.scss) into your project.

**Comment by tmorehouse** [comment]
Note that when minified and GZiped, the Bootstrap CSS files are only 22.9KB (23,237 bytes)... which is not very large.  The file will be smaller if using `br` compression.  The non-gzipped file size is 152KB

**Comment by astroVibes** [comment]
ok thanks for all
