### ISSUE TITLE
2.0.0-rc28 -> 2.0.0 - Breaking Changes Feedback

### ISSUE THREAD

**Issue by danielcirket** [bootstrap-vue/bootstrap-vue#4106]
Firstly, I want to say thank you to the authors and contributors for the hard work and updates in getting 2.0 released.

I wanted to give some feedback on the versioning scheme and combination of breaking changes that were unfortunately present in the 2.0 release.

It's typically understood that an RC/Release candidate release shouldn't be introducing breaking API changes and should be considered as a stable API with the exception of bugfixes. However there were breaking changes introduced between RC28 and 2.0.0, in my case specifically the `b-table` slot changes. These changes were included in the release notes, however this is less than ideal from a consumer's point of view, consumers should be able to update from an 2.0RC to 2.0 without breaking their applications.

I also understand that projects follow their own conventions for versioning, so with that this is only a suggestion, but whilst there is the possibility of breaking changes then either alpha or beta releases would likely be preferable for consumers. This would give consumers additional safety when to adopt  or update to the next version, or simply waiting for an RC or final version.

Apologies if this comes across negatively as the work everyone does on this library is outstanding, but I did want to raise this to hopefully introduce a discussion within the community.

**Comment by tmorehouse** [comment]
Definitely understandable.

We are now going to be following semantic versioning on a go-forward basis (now that v2.0.0 stable is finally released):

- Patch releases (bug fixes, minor documentation updates)
- Minor releases (for new features, and minor breaking changes i.e. Bootstrap v4.4)
- Major release (large breaking changes, such as Vue 3.x, Bootstrap v5, etc)

**Comment by csicky** [comment]
I didn't expect breaking changes when upgrading from 2.0.0 rc to 2.0.1. Now I have to revert and will upgrade when I will have time to deal with them.

**Comment by RomeshA** [comment]
Absolutely second this, I ran into exactly the same issue with the changes to `slots`, I totally understand why it was changed, but the issue is that `npm` follows the semver convention so we configure `package.json` to pick up patches but not breaking changes. When a project doesn't follow the convention and includes a breaking change in a patch version increment, then subsequent builds stop working as soon as the new version is published to npm (and it can be a slow process to debug, first to even determine that it was due to an npm package, and then to isolate which package, even before working out what the change actually was. That's why we normally don't allow major version changes in `package.json`). It is a bit of a constraint on developers, but I do feel that if projects are published to npm then they should do their best to adhere to standard semantic versioning _because_ that's the assumption under which `npm`'s tilde and caret version specifiers operate. So definitely appreciate that you plan to follow semantic versioning going forward, thanks! 

I would just comment though, that semver defines a 'minor release' as being backwards compatible, so if you include any breaking change in a minor release, it will likely cause problems for anyone that has say `"bootstrap-vue": "^2.0.0"` in their `package.json` - users expect that they would only encounter breaking changes if they opt-in by writing something like `"bootstrap-vue": ">2.0.0"`. semver differentiates between a 'major' release and a 'minor' release not by how big the changes are, but by whether they are backwards compatible or not - and while it does lead to the major version number being incremented much more rapidly, it's a really helpful convention in terms of understanding whether something is likely to break or not
