### ISSUE TITLE
<b-tooltip>/<b-popover>: Directive shows default browser title with a long show delay

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#4114]
### Describe the bug

In version 2.0.0 a bug was introduced where if you provide a longer show delay(500ms and above), it will show the default browser tooltip based on the title.
This was not previously the case up until version 2.0.0-rc.28.

### Steps to reproduce the bug

1. Add a popover/tooltip to a element
2. Add the `directive` with a `hover` trigger and a show delay of 500ms or higher
3. See that the default browser title appears before the tooltip/popover is shown.

### Expected behavior

The tooltip or popover should override the default browser title and prevent it from being shown.

### Versions

**Libraries:**
- BootstrapVue: 2.0.0 and later
- Bootstrap: 4.3.1
- Vue: 2.6.10

### Demo link
https://codepen.io/Hiws/pen/qBWMpMg

**Comment by tmorehouse** [comment]
Yeah...  will need to figure out a way to hide the title when the trigger has entered the "enter" phase, rather than when the tooltip actually shows.

We had decided to leave the original title on the trigger element until the tip shows for accessibility reasons (when screen readers read the page or section content, it will announce the title to them).

**Comment by tmorehouse** [comment]
PR #4120 fixes the issue with the title attribute and the show delay.

**Comment by tmorehouse** [comment]
BootstrapVue v2.0.2 has just been released, which includes a fix for this.
