### ISSUE TITLE
new version of bootstrap-vue has bug with tinymce editor

### ISSUE THREAD

**Issue by designy** [bootstrap-vue/bootstrap-vue#4157]
when we update bootstrap-vue to version 2.0.2, TinyMCE works fine for the first load inside modal, 
![Capture](https://user-images.githubusercontent.com/5834795/65576228-697a3200-df7e-11e9-8047-54d7aef83c40.PNG)

but after a close and open modal, TinyMCE editor disappeared and just text area is shown.
![Capture](https://user-images.githubusercontent.com/5834795/65576290-8ca4e180-df7e-11e9-956c-229d6e080ff2.PNG)

 remove TinyMCE editor and create again whit below commands works but it has a bad experience for the user.

			global.tinymce.EditorManager.execCommand(
				'mceRemoveEditor',
				false,
				'editor-id'
			);
			global.tinymce.EditorManager.execCommand(
				'mceAddEditor',
				false,
				'editor-id'
			);

**Comment by tmorehouse** [comment]
Could you provide a bit more code, such as how you are enabling MCE on your textareas or divs?

What is the error you are seeing? could you provide a minimal reproduction CodeSanbox or Codepen?

**Comment by designy** [comment]
yes, screenshot pictures added!

**Comment by tmorehouse** [comment]
Since modal's are _lazy_ by default, you will need to re-initialize tinyMCE once it re-opens.

How are you creating the MCE editor? is it a 3rd party component, or are you calling tiny MCE to apply to a text-area?

**Comment by tmorehouse** [comment]
It would be very helpful is you could create a code sandbox or code pen that recreates the issue, so we can re-create it.  without knowing how you are including or initializing tinyMCE, if you are using a 3rd party component, etc. it is almost impossible to determine what is going on.

**Comment by designy** [comment]
I'm used official TinyMCE component for vue
https://github.com/tinymce/tinymce-vue
with a static prop to modal TinyMCE editor not working and if I reinitiate(remove and add) tinymce manually two-way binding and v-model not work!
I try to create a code pen.

**Comment by tmorehouse** [comment]
After looking at their source code a bit, it appears they may not be properly destroying the MCE Editor instance when the modal content gets destroyed (when the modal hides), depending on how you import tinymce/tinymce (if the editor component loads it from their cloud)

**Comment by asika32764** [comment]
This hack for tinymce-vue works for me. https://github.com/tinymce/tinymce-vue/issues/106#issuecomment-569530867

**Comment by SimonFc** [comment]
I think I have found what this issue originates from.

1. On this [CodeSandbox](https://codesandbox.io/s/fake-tinymce-b5zug?fontsize=14&hidenavigation=1&theme=dark), with your dev-tools opened (there's a debugger statement placed in the code), click the "Open modal" button to open the modal. Note that an iframe gets rendered with some content.
2. Resume execution and note that the content of the iframe gets removed. This is because the iframe re-renders due to it being detached/moved in the DOM (normal iframe behaviour).

I *think* it's due to portaling done by this [transporter](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/transporter.js) which re-renders the content of the modal but I know far to little about it to say anything for certain. @tmorehouse Does this sound likely, and if so, do you think this is something that bootstrap-vue can do differently?

@designy @asika32764 As for TinyMCE, I came up with this [work-around](https://codesandbox.io/s/tinymce-vue-bootstrap-vue-modal-wl5h2?fontsize=14&hidenavigation=1&theme=dark) which conditionally renders and removes tinymce-vue on the show- and hide-events emitted by the bootstrap-vue modal.

@designy I think the reason for why TinyMCE rendered initially for you is because if you're using the Cloud service TinyMCE provides there's a small delay on the initial render. That seems to be enough to circumvent the issue.

**Comment by asika32764** [comment]
> As for TinyMCE, I came up with this work-around which conditionally renders and removes tinymce-vue on the show- and hide-events emitted by the bootstrap-vue modal.

This work-around works for me, thanks.
