### ISSUE TITLE
table filter super slow

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#4211]
### Describe the bug

Filtering on a `b-table` with 800 or so rows is super slow, takes many seconds. No custom formatters or anything.

### Expected behavior

Should be near instant.

### Versions

**Libraries:**

- BootstrapVue: 2.0.3

**Environment:**

- OS: Windows 10
- Browser: Chrome

### Demo link

![superslow](https://user-images.githubusercontent.com/52204959/66315628-07bab000-e90e-11e9-8b50-b562b7bdb171.gif)

demo:
https://jsfiddle.net/unqh6axf/

**Comment by Hiws** [comment]
Adding a debounce using the `filter-debounce` prop and adding a `per-page` of 100~ should greatly improve the user experience

**Comment by tmorehouse** [comment]
Filtering will never be "instant" due to the fact that each record must be serialized into a string (serialize the object values into a searchable string) in order to test each record.

Ways to improve performance:

- Set a `primary-key` on the table (set to the name of a field that has a guaranteed unique value per row)
- Paginate your table, so that you are only displaying max 100 rows (reducing the side of the DOM that Vue has to check for re-patching)

**Comment by sprocket99** [comment]
Its a simple table, 800 rows is nothing, using a manual `Array.filter` can get it to filter almost instantly. Adding a `filter-debounce` does improve it, but not enough, when typing it seems like its not responding for a couple of seconds before it decides to display what I typed.

**Comment by tmorehouse** [comment]
B-table itself is not a simple component... there are a lot of things that get processed in order to render a table.  

If you don't apply the filter to the table (just have the input bound to a data property, but do not even pass it to your b-table, you will notice the input itself is slow... this is because Vue sees your app data changing and assumes that it needs to do a re-render, which in turn causes any child components to potentially re-render.

**Comment by sprocket99** [comment]
@tmorehouse Thanks. Any suggestions to remove or at least reduce the typing delay?

**Comment by tmorehouse** [comment]
Do not use a v-model on the search input, rather, use the `@input` event (which emits the input value) to call a debounced handler that update your criteria.

See second option in this comment: https://github.com/bootstrap-vue/bootstrap-vue/issues/4150#issuecomment-536233132

**Comment by tmorehouse** [comment]
Here is an example: https://jsfiddle.net/5crva6zf/

Something else you can do, is avoid using nested properties in data for values passed as props.  When a nested property changes, it also casues a change on the root of hte nested object.

If you need to use nested properties, access them via computedProperties (for getters at least)

**Comment by tmorehouse** [comment]
Bootstrap v2.0.4 has been released with has some table performance improvements

**Comment by sprocket99** [comment]
Yes, the performance is much improved. Thank you for following up on this!
