### ISSUE TITLE
Add arrows to collapse and accordion components

### ISSUE THREAD

**Issue by taniarascia** [bootstrap-vue/bootstrap-vue#4232]
### Is your feature request related to a problem? Please describe...

I often require arrows to indicate whether an accordion or collapse is open or closed, and Bootstrap Vue does not come with this option or an intuitive way to implement it.

### Describe the solution you'd like

Add an option to collapse/accordion that has arrows.

### Describe alternatives you've considered

[Semantic UI Vue](https://semantic-ui-vue.github.io/#/modules/accordion) has arrows in the accordion by default.

**Comment by tmorehouse** [comment]
Since you can use any content/element(s) to be a trigger for a collapse or accordion, you can place any content in that trigger element to indicate the collapsed state. (note the navbar-toggle is an example of an arbitrary element (SVG) being used to trigger a collapse).

The collapse trigger element will have the class `collapsed` on it when the target collapse element is not expanded.  this can be used to display/not-display an icon.

Controlling b-collapse is performed by a directive `v-b-toggle` which can be placed on most any element, and has no styling/component, other than placing the `collapsed` class (and a few other ARIA attributes) on the element the directive is applied to.  Collapses can also be triggered by `v-model` (instead of the directive).

BootstrapVue (and Bootstrap) do not restrict you to using pre-defined components for collapses/accordions and trigger elements.

**Comment by tmorehouse** [comment]
Example using v-model to hide/show icons:

```html
<template>
  <div>
    <b-button v-b-toggle.collapse-1 block class="d-flex">
      <span>Button Text</span>
      <!-- replace these with your preferred icons -->
      <strong v-if="isVisible" aria-hidden="true" class="ml-auto">-</strong>
      <strong v-else aria-hidden="true" class="ml-auto">+</strong>
    </b-button>
    <br>
    <b-collapse id="collapse-1" v-model="isVisible">
      <b-card title="Card">
        Card content
      </b-card>
    </b-collapse>
  </div>
</template>

<script>
export default {
  data() {
    return {
      isVisibe: true // starts un-collapsed
    }
  }
}
</script>
```

https://jsfiddle.net/Lvt3ub5x/
