### ISSUE TITLE
'v-b-modal' and 'v-b-toggle' directives not working together

### ISSUE THREAD

**Issue by akimlyubchenko** [bootstrap-vue/bootstrap-vue#4243]
With this button options working only `v-b-toggle` directive. If comment one of them(either `v-b-modal` or `v-b-toggle`) everything works well (e.g. if comment toggle directive, modal directive starts working)
```
<b-button
	v-for="button in headerButtons"
	:key="button.name"
	:variant="button.variant"
	:class="`${button.class} mr-4`"
	v-b-modal="button.modalId"
	v-b-toggle="button.collapseId"
>{{ button.name }}</b-button>
```
data:
```
headerButtons: [
	{
		name: "btn 1",
		variant: "success",
		class: "green",
		modalId: "new-exchange-modal"
	},
	{
		name: "btn 2",
		variant: "info",
		collapseId: "search-collapse",
		class: "blue"
	}
]
```

What needs to be done to make all directives work?

**Note!** After hot reload(webpack) it works well(each of directives works fine together)

**Libraries:** 
"bootstrap-vue": "^2.0.2",
		"vue": "^2.6.10"

**Comment by tmorehouse** [comment]
The problem here is that these directives conflict.  Both place aria accessibility attributes on the trigger element which override each others attributes (which would make it confusing for screen reader users especially).

Screen reader users will hear that the trigger element controls the collapse, but also hear conflicting information if the modal opens (as the modal isn't pointed to by the ARIA atributes, but it would be read out when opened, which would conflict with the reading of the opened collapse element.

I would highly recommend not using a single button to open both a collapse and a modal simultaneously.

If for some reason you need to (but note it is not good for accessibility)... switch to using `this.$bvModal.show(modalId)` in a click handler on the button and avoid using the directive.

**Comment by tmorehouse** [comment]
Also, since you are attempting to trigger only one or hte other, based on your data, and you are not using render functions, use v-if to decide how to render the button with which directive:

```html
<tempate v-for="button in headerButtons">
  <b-button
    v-if="button.modalId"
    :key="button.name"
    :variant="button.variant"
    :class="`${button.class} mr-4`"
    v-b-modal="button.modalId"
  >{{ button.name }}</b-button>
  <b-button
    v-else-if="button.collapseId"
    :key="button.name"
    :variant="button.variant"
    :class="`${button.class} mr-4`"
    v-b-toggle="button.collapseId"
  >{{ button.name }}</b-button>
</template>
```

**Comment by akimlyubchenko** [comment]
thanks, everything is clear
