### ISSUE TITLE
Prevent popover from being removed from DOM

### ISSUE THREAD

**Issue by D-Marc1** [bootstrap-vue/bootstrap-vue#4247]
### Is your feature request related to a problem? Please describe...

I'm using the table component and I have a popover that lists all the columns. I combined this popover with Vue Sortable to allow the columns to be reordered. The only problem is that as soon as the popover is closed, it removes it from the DOM, which causes the Vue Sortable plugin to no longer work.

### Describe the solution you'd like

Maybe a boolean prop for the popover called `keepInDOMOnClose` to have the option for this.

### Describe alternatives you've considered

I honestly can't think of any solution to this at the moment.

**Comment by tmorehouse** [comment]
The main  problem is that the dom is generated on the fly (via an instantiates on demand component). This is recreated after the trigger is fired and destroyed after the last trigger is cleared.

Changing this behaviour would be a bit of a pain.... as it would need to handle the special cases of route changes... the parent component being destroyed, etc.... bloating the code to handle this specific use case.

By default the popover/tooltip dom is appended to the body element... so I am unsure as to why you/vue-sortable would have an issue with this since it is not rendered within the table.

**Comment by D-Marc1** [comment]
I understand. I just meant when  you are currently on your route. Could it not just be the same behavior you have now, with no changes to it, when  the parent is destroyed?

**Comment by tmorehouse** [comment]
They are created /instantiated on demand. The insertion into DOM triggers the show transition, and the removal from DOM triggers the hide transition... so it is a bit more involved to keep the template in DOM.

**Comment by D-Marc1** [comment]
I got you. I can understand why it wouldn't make sense for you guys to add this feature. 

Thank you for the extremely fast responses and explanation.
