### ISSUE TITLE
Remove dependency on MutationObserver

### ISSUE THREAD

**Issue by djpate** [bootstrap-vue/bootstrap-vue#4333]
### Is your feature request related to a problem? Please describe...

As we were QA'ing our App in IE11 and Edge we noticed an incredible slowdown that rendered most of the app completely unusable.

### Describe the solution you'd like

After much investigation, we noticed that most of the time was spent un MutationObserver, reevaluating CSS over and over again the same elements. We started to do some digging and found that [Vue Core is not using the native IE MutationObserver due to this issue](https://github.com/vuejs/vue/issues/6466). 

We ended up fixing our issue by setting `window.MutationObserver = undefined`, which fixed all of our rendering problemes.

While our rendering issues are now fixed, We have a few warnings in our modals and carousels. We can work around them for IE but It would be great to have a fallback solution for the `domObserver` that doesn't use `MutationObserver`

### Describe alternatives you've considered

We tried switching to MutationObserver polyfill, but it ended up being even slower than IE's native solution.

**Comment by tmorehouse** [comment]
MutationObserver is needed to detect when content changes within the modal dynamically (i.e. insertions/removals, `display: none`, etc) so that the padding/scrollbar compensation can be updated if the modal starts to overflow (or stops overflowing) the viewport.  For Carousel, MutationObserver is used to detect if slides are added or removed, or have `display: none` set...

Without it you may notice certain things not working correctly (in certain situations).

We'll see if we can tweak the observer configs,

Which version of BootstrapVue are you using?  In older versions we had a fallback mode for IE11 (which was slow), but have opted to switch to users using a polyfill for IE11.

**Comment by djpate** [comment]
Thanks for the quick update.

We are using `2.0.4`, we're happy to test an older version if you want us to compare.

**Comment by tmorehouse** [comment]
The last version that had the fallback mode (which only detected some changes to the DOM in IE11) was v2.0.0-rc.18

**Comment by jaeming** [comment]
I'm noticing a slowdown on Firefox as well for big forms and complex views. The modals can take up to two seconds to appear sometimes. Setting `MutationObserver = undefined` fixes this.

**Comment by tmorehouse** [comment]
The unfortunate thing with removing MutationObserver is that the modal will not adjust it;s centering or scroll bars properly if the content in the modal changes (i.e. `display:none`), or when using native features like `<details>` elements (which would bring back the bug that originally made us add in using MutationObserver)

**Comment by djpate** [comment]
We figured it out. Someone was using a [feature](https://fontawesome.com/how-to-use/with-the-api/methods/dom-watch) from `FontAwesome` that was using MutationObserver on the entire document body and never tearing it down. Removing that fixed our issue!

Sorry for the confusion.
