### ISSUE TITLE
Rewrite old <template>-syntax in b-table

### ISSUE THREAD

**Issue by SPQRInc** [bootstrap-vue/bootstrap-vue#4343]
Hello everybody,

in former versions I was able to use this to show a cell for each field in fields:

```
<template v-for="(field, index) in fields" :slot="field.title" slot-scope="data">
    Test
</template>
```

Now I need to rewrite this, but:

```
<template v-for="(field, index) in fields" v-slot:cell(field.title)="data">
    Test
</template>
```

does not work? What do I miss?

**Comment by Hiws** [comment]
Since it's a dynamic slot name you need to use [this](https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names) syntax for your slot.

So in your case it would be

```html
<template v-for="(field, index) in fields" v-slot:[`cell(${field.title})`]="data">
    Test
</template>
```
Or refer to https://jsfiddle.net/cfwuj4tb/ for an example.

I can see that you're looping your fields. If it's because you want to apply something to all your cells you can use the following syntax, to for example make all your cells bold.
```
<template v-slot:cell()="data">
  <b>{{ data.value }}</b>
</template>
```

Codepen example of the above: https://codepen.io/Hiws/pen/YzzeWae

**Comment by SPQRInc** [comment]
That works fine, thanks a lot!
