### ISSUE TITLE
b-table cell caching?

### ISSUE THREAD

**Issue by z1m1n** [bootstrap-vue/bootstrap-vue#4423]
Is there a way to disable cell re-rendering after sorting? I have a chart inside of the cell (please see code example below) and sorting works slow due to chart re-rendering. Thanks!

![image](https://user-images.githubusercontent.com/5075434/69569087-915d3480-0fc5-11ea-9e44-57685516ed9c.png)

**Comment by tmorehouse** [comment]
To optimize re-rendering, make sure you provide a primary-key field name via the `primary-key` prop (assuming your item rows have a field that has a unique value across all rows).

This will instruct Vue to re-use the table `<tr>` elements where possible (i.e. for the same row, but moved to a different position due to sorting or filtering.

**Comment by z1m1n** [comment]
> 
> 
> To optimize re-rendering, make sure you provide a primary-key field name via the `primary-key` prop (assuming your item rows have a field that has a unique value across _all_ rows).
> 
> This will instruct Vue to re-use the table `<tr>` elements where possible (i.e. for the same row, but moved to a different position due to sorting or filtering).
> 
> Also note that the scope property `data.index` is the physical row index (as displayed). So avoid using that as a `key` in your chart, as it will change based on where the original item row is rendered (due to sorting or filtering). If your row's item data has a unique value field (unique across all rows), use it is the key.

I'm set `primary-key` with a field name that contains unique values and removed `data.index` calls in all cells. Nothing changed

**Comment by tmorehouse** [comment]
Vue should detect that the props passed to your chart component haven't changed and re-use the component's rendered vnodes.

Set the `:key` on your chart as `data.item.uniqueField` (just make sure your field is a primitive value like a number or string) where `uniqueField` is the name of your unique field in items.

**Comment by z1m1n** [comment]
> 
> 
> Vue should detect that the props passed to your chart component haven't changed and re-use the component's rendered vnodes.
> 
> Set the `:key` on your chart as `apechart-${data.item.uniqueField}` (just make sure your field is a primitive value like a number or string) where `uniqueField` is the name of your unique field in items.

Thank you, but sort still slow. 

![image](https://user-images.githubusercontent.com/5075434/69573065-14828880-0fce-11ea-948e-036cdcc999e0.png)

**Comment by tmorehouse** [comment]
Sorting speed will depend on how many rows you have in your items array (and the sorting algorithm used by the native `Array.prototype.sort()` of your client).

**Comment by z1m1n** [comment]
I'm have bootstrap vue 2.1.0 and 250 items in table (sorting is fast, when I remove column with chart)

**Comment by tmorehouse** [comment]
Then it might depend on the inner workings of the `apechart` component, since the array being passed to it is a new array reference (from the `map` function) each time the table is rendered.

Perhaps pre-massaging your data to have the `map` operation performed when the items are loaded and place the results in a new field within your items array.
