### ISSUE TITLE
Upgrading to 2.1.0 causes buttons and checkboxes in table slots to not render

### ISSUE THREAD

**Issue by AllenTullett** [bootstrap-vue/bootstrap-vue#4460]
I recently upgraded from `bootstrap-vue": "^2.0.0-rc.13"` to `"bootstrap-vue": "^2.1.0"`.

Within my interface I have tables with slots which contain checkboxes and buttons. In `2.0.0-rc.13` these render as desired in the correct cell, but in `2.1.0` the cell element is rendered blank. I have replicated this on other machines, and am not seeing a package conflict.

Example slot which works on 2.0.0:
```
<template slot="mutate" slot-scope="row">
  <b-form-checkbox :disabled="permissions.delete == 0" v-model="selected"  :value="row.item.id" :id="row.item.id+'-select-checkbox'"></b-form-checkbox>
</template>
```

Happy to provide more detail if desired.

**Comment by Hiws** [comment]
The slot names have changed since `2.0.0` which you can see [here](https://bootstrap-vue.js.org/docs/misc/changelog#v200)

You can check out the new syntax in the docs [here](https://bootstrap-vue.js.org/docs/components/table/#scoped-field-slots)

**Using v-slot**
```html
<template v-slot:cell(mutate)="row">
  <!-- Your custom markup -->
</template>
```
**Using the deprecated (since vue 2.6) slot syntax**
```html
<template slot="cell(mutate)" slot-scope="row">
  <!-- Your custom markup -->
</template>
```

**Comment by AllenTullett** [comment]
Thank you, you were spot on, and sorry to have wasted your time
