### ISSUE TITLE
Table pagination not working when using `filter-included-fields`

### ISSUE THREAD

**Issue by TheAndroidGuy** [bootstrap-vue/bootstrap-vue#4519]
When i use filtering with `filter-included-fields` the table pagination is not working.

Here is an example:
https://jsfiddle.net/7w2zyfvu/

If you enter `test` in the filter, and if you click on the second page it does not display the rows from the second page.

**Comment by Hiws** [comment]
Looks like `onFiltered` is fired when changing page. 
So your line `this.currentPage = 1` in your `onFiltered` function breaks the pagination

**Comment by tmorehouse** [comment]
You need to conditionally reset the current page:

https://jsfiddle.net/uqL8nbxg/

**Comment by TheAndroidGuy** [comment]
@tmorehouse I don't understand why i should do that. Why without `filter-included-fields` it works fine without that condition?

**Comment by tmorehouse** [comment]
What appear to be happening is that pagination (for some reason) is triggering the `filtered` event which is causing you to always set the current page to 1, which is why you can't click on page 2 (well you are clicking page 2, which then for some reason is causing the filtered event to re-emit, hence causing your event handler to reset the current page to page 1.

**Comment by TheAndroidGuy** [comment]
For some reason pagination with `filter-included-fields` is slower than without `filter-included-fields`.

**Comment by tmorehouse** [comment]
It will be possibly slower as b-table has to pluck out the included fields out of the row before it searched through them.
