### ISSUE TITLE
Jest Unit Tests: modal component

### ISSUE THREAD

**Issue by rodhoward** [bootstrap-vue/bootstrap-vue#4589]
Hi,

We have just updated to version: 2.2.0.

Since then we have had to put in a number of ugly wait next tics etc to get our Jest unit tests to work with modals. Similar to what you have in your unit tests:
https://github.com/bootstrap-vue/bootstrap-vue/blob/64bf5efc2dc532753ad174c3142946679de9ad40/src/components/modal/modal.spec.js#L189

Why are these now required?  When can we pull them back out :)? 

Cheers
Rod

**Comment by tmorehouse** [comment]
This is due to the `nextTick` required in the portalling process.  All updates to the modal content take a nextTick to update the portal target.

**Comment by tmorehouse** [comment]
PR #4604 Removes the portalling nextTick delay, but note that with the latest Vue test utils, the `await nextTick` is required since tests no longer run in synchronous mode.  nextTicks (and requestAnimationFrame) are also required when testing elements with transition hooks (if not stubbing transitions)

**Comment by rodhoward** [comment]
Thanks for the quick responses. PR has fixed it for us :).
