### ISSUE TITLE
using custom directives with b-table

### ISSUE THREAD

**Issue by kriczq** [bootstrap-vue/bootstrap-vue#4683]
### Describe the bug
I want to use twemoji package to replace unicode emojis with img elements in b-table row.

I use the following directive.
```
Vue.directive('emoji', {
  inserted(el) {
    el.innerHTML = twemoji.parse(el.innerHTML)
  }
})
```

and in b-table components I have the following code
```
<template v-slot:cell(name)="data">
  <span v-emoji>{{ data.value }}</span>
 </template>
```

see on demo

### Steps to reproduce the bug
I have the array connected with b-table by items prop. When I add element to the beginning of array with unshift function the content of rows with emojis in that column are duplicated. It seems like the content of td element which contains emojis is not updated when going to next row.

### Versions

**Libraries:**

- BootstrapVue: 2.0.4
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

any browser

### Demo link

https://codepen.io/kriczq/pen/QWwPEXE

**Comment by tmorehouse** [comment]
What is happening is that Vue is re-using the rows/cells and just updating what has changed.

A few options:

- If you have a value in each row that is guaranteed to be uinique (different value in each row item), use the `primary-key` option to specify the field that has the unique value.  this will set a unique Vue `key` on each TR element (otherwise the index of the row is used)
- update your directive to include the [`componentUpdated` hook](https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions):
  ```js
  Vue.directive('emoji', {
    inserted(el) {
      el.innerHTML = twemoji.parse(el.innerHTML)
    },
    componentUpdated(el) {
      el.innerHTML = twemoji.parse(el.innerHTML)
    },
  })
  ```
  Which will re-run your emoji swap when the containing parent component has finished updating.

**Comment by tmorehouse** [comment]
After testing your codepen, I found the first option works best for you:

https://codepen.io/tmorehouse/pen/OJPGmLm

Or by setting a unique key on the `<span>` in your slot:

https://codepen.io/tmorehouse/pen/OJPGmJg
