### ISSUE TITLE
`<b-table>` Nested property cannot be filtered

### ISSUE THREAD

**Issue by Leohige** [bootstrap-vue/bootstrap-vue#4737]
I want to filter some nested properties, but it doesn't work.

The filtered data is always empty.

```js
data() {
    return {
        fields: [
            {
                key: 'user.name',
                label: 'Nome',
                sortable: true
            },
            {
                key: 'user.email',
                label: 'Email',
                sortable: true
            },
            {
                key: 'actions',
                label: 'Ação'
            }
        ],
        routeName: 'admin',
        totalRows: 0,
        currentPage: 1,
        filter: null,
        filterOn: ['user.name'],
        sortBy: null,
        sortDesc: false,
        perPage: 10
    }
}
```
I tried using a template, but it also doesn't work

```html
<template v-slot:cell(name)="row">
    {{ row.item.user.name }}
</template>
```

**Comment by tmorehouse** [comment]
Currently the build in filtering works on the stringified record (searches teh values of all properties in the record). (Note `filter-on` is not a valid prop for `<b-table>`)

In order to filter on certain nested props only, you will need to implement a custom filter function that plucks the requested field value. https://bootstrap-vue.js.org/docs/components/table#custom-filter-function

Or use built in filter options  `filter-ignored-fields` or `filter-included-fields` to specify a subset of (top-level) fields to filter on. Note only top level keys are currently supported.
