### ISSUE TITLE
sort-by does not respect sortDirection

### ISSUE THREAD

**Issue by bragboy** [bootstrap-vue/bootstrap-vue#4751]
Demo link: https://jsfiddle.net/bragboy/gy58p2hu/13/

```html
<div id="app">
  <b-table :items="items" :fields="fields" :sort-by="sortBy" />
</div>
```

```js
new Vue({
  el: '#app',
  data() {
      return {
        sortBy: 'age',
        fields: [
          { key: 'last_name', sortable: true },
          { key: 'first_name', sortable: true, sortDirection: 'desc'},
          { key: 'age', sortable: true, sortDirection: 'desc'},
          { key: 'isActive', sortable: false }
        ],
        items: [
          { isActive: true, age: 40, first_name: 'David', last_name: 'Macdonald' },
          { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
          { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson' },
          { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney' }
        ]
      }
    }
})
```
<img width="608" alt="imagen" src="https://user-images.githubusercontent.com/1298587/74246361-af912180-4ce4-11ea-9418-ca772419e754.png">

**Expected**: Age field sorted by default in descending order.
**Actual**: Age field sorted by default in ascending order.

My expectation here is to have `sort-by` respect the `sortDirection` specified for the age field.  It default sorts the age field, but the `sortDirection` does not have any effect.

Any help/pointers in fixing my problem would be greatly appreciated!

**Comment by Hiws** [comment]
I'd guess this is a current bug.

A temporary fix would be to set the `sort-desc` in the mounted hook of your component, based on the `sortDirection` in your field.

https://jsfiddle.net/qy7efvuo/

**Comment by bragboy** [comment]
I had to use `:sort-desc="true"` and this fixed the issue for me.

Updated fiddle: https://jsfiddle.net/bragboy/pLxu7cg3/

**Comment by Hiws** [comment]
@tmorehouse 
While there's a workaround, it could be worth looking into as I'm guessing it _should_ be using the `sortDirection` from the field on initial render if `sortBy` is set.

**Comment by tmorehouse** [comment]
sortDirection is a bit of a hack that was added a while ago to set the initial sort direction when clickng the header cell for that column.  It accepts a string direction 'desc', 'asc', or 'last' (which can actually become confusing for screen reader users). To code to handle that override is actually quite cumbersome when we generate the appropriate  aria-headers and the sortDesc state.

It was originally added because someone wanted the default order of sorting changes (i.e. when a column is first clicked it sorts desc, then asc... and they wanted asc then desc.  It should have been implemented in a different manner than it is now.

**Comment by wparad** [comment]
The fact that there is a hackwork around does not make this problem fixed. Would we be willing to accept a PR that a fixes the problem so that someone does not have to magically know to set the `sort-desc: true` hack and for this to just work correctly out of the box?
