### ISSUE TITLE
[Vue warn]: Unknown custom element: <b-carousel>

### ISSUE THREAD

**Issue by mauroviniciussilva** [bootstrap-vue/bootstrap-vue#4758]
I'm trying to use the carousel component, but somehow I just can't. Tried everything and searched for similiar issues here but I didn't find. Do I need some specific import declaration for this component?

![image](https://user-images.githubusercontent.com/49000408/74396020-95903580-4def-11ea-9c67-18dff1ba8920.png)

**Comment by tmorehouse** [comment]
```js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)
```

**Comment by mauroviniciussilva** [comment]
@tmorehouse, I've faced the same issue running the same project in another machine, with the import declaration. `npm install` solved my issue.

**Comment by scil** [comment]
I use bootstrapvue umd in a traditional html page and encounter the same error  `Unknown custom element: <b-alert> - did you register the component correctly`

because on the same page, an third party app uses vuedraggable. ( MediaApp in OrchardCore.Media )

now everything work well  after I removed vuedraggable from the third party app.

days ago, I even can not use Vue one the page, because the third party app MediaApp uses vue.  so I removed vue from the App.

So,  vue can not accept double same components.
