### ISSUE TITLE
Impossible to select the child elements of the table when filled with function

### ISSUE THREAD

**Issue by lucasmsoares96** [bootstrap-vue/bootstrap-vue#4782]
### Reproduction link
[https://jsfiddle.net/lucasmsoares96/2x0mpLt7/1/](https://jsfiddle.net/lucasmsoares96/2x0mpLt7/1/)

### Steps to reproduce
open the browser console

### What is expected?
the browser console is expected to show the childre elements of the selected table.

### What is actually happening?
Child elements are not selected.

---
child elements are selected when the items attribute is defined within data(), but not when items are returned from a function

**Comment by tmorehouse** [comment]
Note each time the table renders (caused by any data updates), it is possible for the children elements to change.

Perhaps you should be using event delegation, rather than trying to bind on each table child element on mount.

Add a `click.native` listener to `<b-table>`, and then inspect the `evt.target` to see if it is a td, th, etc... Note the click will fire on child elements in the cells, so you may need to use `evt.target.closest('td')` (or `tr` or `th`, `tbody`, etc)

**Comment by tmorehouse** [comment]
Also note when `items` is a function, the function is run on mount (and on any updates) and the cells may not be avaialbel unti lafter hte function has completed.

If you check the console log, you will see this error:

![image](https://user-images.githubusercontent.com/2781561/74692788-32235080-51bf-11ea-9aef-0829fdd52786.png)

And when clicking on the line failing:

![image](https://user-images.githubusercontent.com/2781561/74692802-4a936b00-51bf-11ea-92b2-3aae3b68bc8b.png)

You will see that the row does not yet exist (it is also assuming that `tbody` is the second child of the table)

This is because during the `mounted` phase, you are assuming that the items function has completed running (the items function is run on `mounted()`).  Adding a `$nextTick` wrapper around your `this.catchCell()` in the `mounted()` handler will fix the error, But it will not handle the case where the table may get re-rendered and element references may change.

**Comment by lucasmsoares96** [comment]
> Note each time the table renders (caused by any data updates), it is possible for the children elements to change.
> 
> Perhaps you should be using event delegation, rather than trying to bind on each table child element on mount.
> 
> Add a [`click.native` listener](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components) to `<b-table>`, and then inspect the `evt.target` to see if it is a td, th, etc... Note the click will fire on child elements in the cells, so you may need to use `evt.target.closest('td')` (or `tr` or `th`, `tbody`, etc)

this works perfectly, thank you very much.
