### ISSUE TITLE
Form Tag Bug On Mobile

### ISSUE THREAD

**Issue by wave100** [bootstrap-vue/bootstrap-vue#4794]
### Describe the bug

The b-form-tags component doesn't let you add a tag when using a mobile keyboard. Additionally, the "add" button doesn't show up until you click away from the element, which closes the keyboard on mobile. I'm using the Google Keyboard.

### Steps to reproduce the bug

1. Open [this page](https://bootstrap-vue.js.org/docs/components/form-tags) on mobile (tested with Chrome on Android).
2. Try to add a tag to the tag input.

### Expected behavior

Pressing the "enter" key on the mobile keyboard should add a tag. The "add" button should show up when text is entered.

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: Unknown (Whatever is on the demo website)
- Vue: Unknown (Whatever is on the demo website)

**Environment:**

- Device: Pixel 2
- OS: Android 10
- Browser: Chrome for Android
- Version: 80.0.3987.99

**Comment by tmorehouse** [comment]
This is most likely due to how the google keyboard triggers auto-suggest/complete (if you have predictive text enabled on the keyboard settings).

Input is not triggered by GBoard until an auto suggested word is selected or a space (or punctuation) is entered.  This is similar to how IME composition works on mobile keyboards.

The `add tag` button only appears when the input event has fired and there are characters in the field...  But due to how Vue handles the composition events (which GBoard uses when auto-suggesting words) the event is suppressed until the compositionend event fires.

Disabling auto-suggest on GBoard gets around this issue (but is not the best solution).

Another option is to enable separator mode in `<b-form-tags>` (i.e. space, etc) and provide a hint to users that you can add tags by pressing space (other the separator characters of your choice)

There is a rather long discussion issue at the Vue repo on this "feature" of Vue's v-model handling on text-like inputs. https://github.com/vuejs/vue/issues/9777, https://github.com/vuejs/vue/issues/9299, https://github.com/vuejs/vue/issues/8231, etc.
