### ISSUE TITLE
Can't access table item property

### ISSUE THREAD

**Issue by Zyles** [bootstrap-vue/bootstrap-vue#491]
Hi, thanks for nice package.

I have one issue tho with the table.

I have defined scope for an item:

```
<template slot="quantity" scope="item">
        {{ item.volume_remain }} / {{ item.volume_total }}
      </template>
```

However it wont output anything.

The JSON looks like this if I use `{{ item }}` inside the slot:
```
{
	"item": {
		"order_id": 4883456515,
		"type_id": 31123,
		"region_id": 10000002,
		"location_id": 60003760,
		"price": 1754404.31,
		"volume_total": 1,
		"volume_remain": 1,
	},
	"index": 0
}
```

How can I access the values??

**Comment by Zyles** [comment]
`{{ item.item.volume_remain }} / {{ item.item.volume_total }}`

**Comment by tmorehouse** [comment]
The `scope="item"` statement sets a local "scoped" variable that receives the slots parameters:
- index (row number, of the displayed items, indexed from 0)
- value (the column value of available, or null for computed/virtual columns)
- item (the entire item record object for this row)

rather than `scope="item"`, you could use `scope="data"`, or `scope="foo":
- `foo.item.volume_total`
- `data.item.volume_total`
- etc
