### ISSUE TITLE
<b-tooltip> component unable to render template syntax

### ISSUE THREAD

**Issue by parkersprouse** [bootstrap-vue/bootstrap-vue#4942]
### Describe the bug

When using the `<b-tooltip>` component, I'm trying to use Vue's template syntax as the content, for example:
```vue
<b-tooltip target='my_id' triggers='hover'>
  {{ title || "<em>No Title</em>" }}
</b-tooltip>
```
However, the template syntax isn't parsed, and the tooltip instead has the literal value `{{ title || "<em>No Title</em>" }}` as its value.

I can't use the `v-b-tooltip.html title='My title'` directive because I'm trying to do this on a `<b-card-title>` component, which has its own `title` prop that takes precedence over the tooltip directive's `title` prop.

### Steps to reproduce the bug

1. Create a `<b-tooltip>` component and attempt to use Vue's template syntax as its value
2. Notice that the template isn't parsed and is instead rendered raw

### Expected behavior

When using Vue's template syntax in the default slot of the `<b-tooltip>` component, the template should be parsed and the output used as the tooltip content instead of the raw template syntax itself.

### Versions

**Libraries:**

- BootstrapVue: 2.6.1
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- OS: Windows 10
- Browser: Firefox
- Version: 73.0.1

### Demo link

[https://codesandbox.io/s/xj3ds](https://codesandbox.io/s/xj3ds)

**Comment by tmorehouse** [comment]
See the following sandbox: https://codesandbox.io/s/muddy-water-k2ru8

A couple of issues...

- One should never use `v-html` on a component... only native DOM elements
- `{{ value || "<em>no title</em>" }}` will not do what you expect (it is always treated as string, not HTML markup)

**Comment by parkersprouse** [comment]
I haven't heard the rule about not using `v-html` on a component. Care to elaborate on that one? And thank you for the solution, I should have realized I should be using separate elements.

**Comment by tmorehouse** [comment]
`v-html` wipes out the content of the root element and since the content, in the case of a component, is _controlled by the component_, `v-html` can potentially break a components functionality.... specifically if the component renders child elements, or the component structure changes in a future release.

That is why the concept of slots (default, and named) are provided to components so that markup can be passed to the component. 

Since a component can technically re-render when teh parent doesn't re-render, it is possible for your v-html content to get replaced by the content generated by the component.

Also consider this component:

```html
<template>
  <span v-if="someCondition">Some value</span>
  <div v-else><slot></slot></div>
</template>

<script>
export default {
  // logic for `someCondition` here
}
</script>
```

Using v-html on the above component will not always work as expected, or the component may not work as expected.
