### ISSUE TITLE
b-form-group form-control-plaintext property

### ISSUE THREAD

**Issue by m-demydiuk** [bootstrap-vue/bootstrap-vue#5012]
Hello dear team, thank you for a great framework. I am migrating our project form vuetify to bootstrap-vue and I have a suggestion, that can make code a little bit clearer.

I have a case when I need to show in form value as plain text. I do it this way:
```html
<b-form-group label-cols="12" label-cols-sm="5" label="Name">
    <p class="form-control-plaintext">{{ user.Name }}</p>
</b-form-group>
```

It would be great if ne `b-form-group` property will be added, and the code will be changed to:
```html
<b-form-group label-cols="12" label-cols-sm="5" label="Name" :plain-text="user.Name"/>
```

Thanks in advance!

**Comment by Hiws** [comment]
You could also use a `b-input` which has the property `plaintext`. It will apply the class `form-control-plaintext` and `readonly` to the input.

```html
<b-form-group label-cols="12" label-cols-sm="5" label="Name">
  <b-input v-model="user.Name" plaintext></b-input>
</b-form-group>
```

**Comment by tmorehouse** [comment]
@m-demydiuk 

The suggestion by @Hiws is probably best, as it provides better semantic markup for screen reader users, and can be properly labeled (can associate the `<label>` with the value, where as a `<p>` tag cannot have an associated `<label>`)

```html
<b-form-group label-cols="12" label-cols-sm="5" label="Name" label-for="plain-input">
  <b-input id="plain-input" v-model="user.Name" plaintext></b-input>
</b-form-group>
```

It is also better as the type of input can be specified, rather than adding that feature to `<b-form-group>`
