### ISSUE TITLE
b-table 

### ISSUE THREAD

**Issue by AhmadAmr** [bootstrap-vue/bootstrap-vue#5028]
### Describe the bug

badge applies to the whole cell not on the text

### Versions

**Libraries:**

- BootstrapVue: 2.9.0
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Browser: [e.g. Chrome]
- Version: [e.g. 70]

### Additional context
   i want to make some thing like that 
       https://ideone.com/NvtSKr

i tried td class but didnt add badge to the text 
```js
fields: [
{
          key: "status",
          label: "Status",
          formatter: (value, key, item) => {
            return value == 1 ? "Active" : "InActive";
         tdClass: (value, key, item) => {
            return value == 1 ? 'badge-success' : 'badge-danger';
          },
      },
```

**Comment by tmorehouse** [comment]
This is the expected behaviour of `tdClass` (as the name implies it applies itself to the `<td>` element)

What you are probably looking for is custom data rendering with a scoped slot:

```html
<b-table :items="items" :fields="fields" ...>
  <template v-slot:cell(status)="scope">
     <b-badge :variant="scope.item.status === 1 ? 'success' : 'danger'">
        {{ scope.value }}
        <!-- or if not using a field formatter
          {{ scope.value === 1 ? 'Active' : `Inactive' }}
        -->
      </b-badge>
  </template>
</b-table>
```

- `scope.value` is the value with any optional formatting as applied by the formatter
- `scope.item` is the entire row data object
- `scope.item.status` is the raw value of the `status` property in your row data object.

See https://bootstrap-vue.js.org/docs/components/table#custom-data-rendering
