### ISSUE TITLE
Planning Bootstrap 5 Version of Bootstrap

### ISSUE THREAD

**Issue by jfarraraains** [bootstrap-vue/bootstrap-vue#5044]
What are the plans, is that on the roadmap?

https://github.com/twbs/bootstrap/projects/11

**Comment by tmorehouse** [comment]
Yep it is on the roadmap.... Although it will drop IE11 support.

**Comment by darrinmn9** [comment]
@tmorehouse,  bootstrap dropping IE11 support in v5 was definitely a shocker since many devs still have to support IE11 for the foreseeable future. Vue3 still plans to support IE11 via compat build. What are your thoughts on the direction and future of bootstrap-vue as it relates to Vue3 and IE11? Do you plan on releasing a bootstrap-vue major version for Vue3+bootstrap4? Once bootstrap5 is stable, will bootstrap-vue drop support for IE11 entirely, or will it atleast apply security/bug fixes to a boostrap4 version for a set period of time? 

Sorry for all the questions, just curious your general thoughts on the subject.

**Comment by tmorehouse** [comment]
There will be a BootstrapVue still based on Bootstrap v4 , but will be based on Vue 2.x (and tweaked for support on Vue 3, depending on how they deal with the events being attributes changes).

BootstrapVue for Bootstrap v5 will most likely be developed for Vue 3 only, and will have a different browslistrc which should make for smaller transpiled code bundles since the majority or modern browsers support many ES6 features.

We will probably keep producing both Bootstrap V4 and V5 versions for a while.

This is just a rough idea of our plan.... which still in the early stages.

BootstrapVue for Bootstrap v4 will stay at BootstrapVue v2.x.x, while BootstrapVue for Bootstrap v5 will be released as BootstrapVue v3.x.x

And now that we have our own domain, we will be able to have multiple docs sites available for each major version.

**Comment by mariusa** [comment]
>  bootstrap dropping IE11 support in v5 was definitely a shocker since many devs still have to support IE11 for the foreseeable future

Based on what data? We're happy to drop all IE (non-Chromium) support. There's always bootstrap-vue 2.x if you need IE11.

**Comment by darrinmn9** [comment]
I dont see the point of your comment months after an answer to my question was provided, but here is some data for you.

https://twitter.com/youyuxi/status/1277605068947312641?s=19

**Comment by jfarraraains** [comment]
If you need IE, there is Bootstrap 4. If we continue to tie upgrades to legacy tech, it will limit the features of what is next. Plus, unless a corporation has enterprise paid support contracts... IE is a security risk. It no longer gets updates for non-contract users.

**Comment by jackmu95** [comment]
Closed in favor of #5507.
