### ISSUE TITLE
Table: Making selected rows consistent through pagination

### ISSUE THREAD

**Issue by JonelMercado** [bootstrap-vue/bootstrap-vue#5055]
I am trying to create a button that selects all rows in the table despite pagination. Currently, my workaround is to add all rows programmatically by passing all results to my selected array.

The problems are that:
a. Users don't have a visual way of telling that all rows are selected. If rows are selected so they can be highlighted (with selectAllRows for example) they override the other selected rows.

b. Users can't go through the table and de-select individual rows.

Is there any way to make selected rows consistent through pagination?

My code is:

`
    selectAllRowsTable() {
        this.selectedCompanies = this.searchResults
    },
`

Adding this to the beginning of the function simply overrides it and only passes the values in the current page. Plus it would need to be done on every page.
`      this.$refs.selectableTable.selectAllRows()
`

**Comment by Hiws** [comment]
You can have a look at this [CodePen](https://codepen.io/Hiws/pen/xxxqGVJ), i believe it it has the implementation you're looking for.

Basically you keep the `selected` state on the object itself, so that it's saved across pages. 
Then you simply toggle the `selected` state on the item how you want.

You can add in an event `@row-clicked` to select the item like the normal `selectable` mode.
You can also use the `tbody-tr-class` prop and pass it a function  to style all selected rows with a certian class.

**Comment by JonelMercado** [comment]
Thank you!
