### ISSUE TITLE
form-checkbox-group changes the order of options passed to it. 

### ISSUE THREAD

**Issue by craigpotter** [bootstrap-vue/bootstrap-vue#5152]
### Describe the bug

When passing a simple key/value object as the options on form-checkbox-group, it seems to be sorting the options by the key. 

### Steps to reproduce the bug

[View Demo](https://codepen.io/craig-potter/pen/PoPZpZJ?editors=1010)

It modifies the order of the data passed in the data. 

### Expected behavior

Data should be loaded in the order it is passed to the component.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Vue: 2.6.11

### Demo link

https://codepen.io/craig-potter/pen/PoPZpZJ?editors=1010

**Comment by tmorehouse** [comment]
That is because you are using the _deprecated_  `object` format for the `options` array, and your keys are numeric-like. Object key order is _not guaranteed_ across browsers or platforms (which is why that format has been deprecated, and you should be getting console warnings in dev mode)

From the Chrome console:

![image](https://user-images.githubusercontent.com/2781561/79380219-81bf9780-7f36-11ea-9cc6-26a76b14b020.png)

From the docs:

https://bootstrap-vue.js.org/docs/components/form-select#options-as-an-object

![image](https://user-images.githubusercontent.com/2781561/79380743-3bb70380-7f37-11ea-8c8a-7df7cb2bf320.png)

> Note: When using the Object format, the order of the final array is not guaranteed. For this reason, it is recommended to use either of the previously mentioned array formats.

Note that under the checkbox/radio documentation that this section has been removed many versions ago.
