### ISSUE TITLE
$bvToggle (or $vbToggle) does not exist.

### ISSUE THREAD

**Issue by websanova** [bootstrap-vue/bootstrap-vue#5170]
### Describe the bug

Bit confusing in general with how to use $bv plugins, and seems like for the toggle it's VBTogglePlugin and for modal it's BVModalPlugin. But inconsistent.

So basically just trying to get same functionality as with modals so I can call these manually with `$vbToggle.hide()` and `$vbToggle.show()`.... or whatever it is bv, vb, just need one to work.

### Steps to reproduce the bug

include the plugin

```
import {VBTogglePlugin} from 'bootstrap-vue';
Vue.use(VBTogglePlugin);
```

try to use it

```
console.log(this.$vbToggle); // undefined
console.log(this.$bvToggle); // undefined
```

### Expected behavior

Should have manual show/hide functionality as with modal.

### Versions

pretty much latest and greatest.

**Environment:**

not sure it's relevant.

### Demo link

n/a

### Additional context

n/a

**Comment by tmorehouse** [comment]
`VBTogglePlugin` => is the `v-b-toggle` directive plugin (directive only... no other components installed... just this one directive).  All directive-only plugins have this nomenclature: `VBXxxxPlugin`

`BVModalPlugin` => The plugin for instantiating `this.$bvModal` injection (note this is not a directive)

`BVToastPlugin` => The plugin for instantiating `this.$bvToast` injection (note this is not a directive)

`ModalPlugin` => Plugin for installing `<b-modal>` component, `v-b-modal` directive, and `this.$bvModal` injection

`VBModalPlugin` => is the `v-b-modal` directive plugin (directive only... no other components installed... just this one directive).

`ToastPlugin` => Plugin for installing `<b-toast>` and `<b-toaster>` components, and `this.$bvToast` injection

Naming convention:
- If it starts with a `VB`, then it is a directive plugin (think `<button v-b-xxxx >`)
- If it starts with `BV`, then it is injection related plugin (`this.$bvXxxxx`)
- Otherwise it is a component group plugin

**Comment by websanova** [comment]
ok, thx for that detailed answer, makes more sense.

I guess I was looking for a similar utility as with `this.$bvModal` for the toggle, so something like `$bvToggle` or `$bvSidebar` which is the specific case I need it for.

**Comment by tmorehouse** [comment]
There is no helper injection for the `v-b-toggle` directive (this directive is used by both `BCollapse` and `BSidebar`).

The other `$bvXxxx` injections provide more functionality than just toggling/tripgering a component. (i.e. `$bvModal` supports message box modals, and `$bvTost` supports generating dynamic toast mesages)

**Comment by websanova** [comment]
A bit more complicated I see. 

I guess I'll have to sort something else out then.

Thx!

**Comment by tmorehouse** [comment]
Sidebars and collapses are not `aria-live` regions, so they will not be announced to screen reader users when they open.  Which is why the appropriate ARIA attributes must be placed on the triggering element (so that the user knows when they click a button, that it will be opening a new context for the user and their attention will be brought to that component when it opens).

So I wouldn't recommend blindly opening a sidebar without the appropriate ARIA mechanisms in place.
