### ISSUE TITLE
Modal - Prevent focus on footer button

### ISSUE THREAD

**Issue by b-zee** [bootstrap-vue/bootstrap-vue#521]
I have a situation in which I have a modal that is longer than the page itself. BootstrapVue apparently [focuses](https://github.com/bootstrap-vue/bootstrap-vue/blob/v0.16.1/lib/components/modal.vue#L6) on the first item in the modal, causing my modal to be scrolled to the bottom on opening. This is undesired.

Example:
https://jsfiddle.net/wrbd2avj/

**Comment by tmorehouse** [comment]
Just before you open the modal, you can set focus to the desired item (by using a $ref), and modal will not auto focus the footer buttons.  We might be adding in an option where we look for the first item with the `autofocus` attribute set, and if not found, focus the first footer button element (for accessibility requirements).

**Comment by tmorehouse** [comment]
Currently modal searches for enabled focusable items in the following order:
- modal footer
- modal body
- modal header

and if none found, then defaults to focusing the modal itself.

I could alter to order to be the following:
- modal header
- modal body
- modal footer

Although ARIA best practices state that a modal's main action buttons (i.e. in the footer normally) should be the first item focused.

**Comment by b-zee** [comment]
I would indeed opt for a top to bottom order, although I understand that focusing on the header close button would not seem like a main action.

The default behaviour now causes elements out of view to be focused, which disorients the user. I'm not sure if it's feasible or realistic, but it would seem logical to test whether the focusable item is within the view, before focusing. Or, focus the item, but scrolling back to the top.

I'm not an expert with ARia, so it's up to you, but the current behaviour is undesired.

**Comment by tmorehouse** [comment]
Another intermedite workaround would be to limit the modal content to be a percentage (or CSS calc'ed value) of the viewport height (specified in `vh` units, https://web-design-weekly.com/2014/11/18/viewport-units-vw-vh-vmin-vmax/) and enable y-scrolling on the model body section.

Or remove the buttons in the footer (or disabled footer) and place the buttons in a custom header slot.

I'll have to noddle some options to see what would be the best compromise, keeping ARIA accessibility and for handling long overflowing content.

Would an option to specify which element should have initial focus be useful in your case?  The modal content container is also manually focusable (tabIndex -1) so you could specify `.modal-content` as the element to focus. (for ARIA accessibility compliance, some element in the modal *must* be focused when opened, otherwise the modal becomes inaccessible to non-sighted or keyboard only users)

**Comment by tmorehouse** [comment]
PR #539 provides a few tweaks to modal, and the new docs gives more samples, with a section on auto-focusing., and how to set focus in the modal before auto-focus runs.
