### ISSUE TITLE
<b-avatar> @click event not working anymore in 2.12.0

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [bootstrap-vue/bootstrap-vue#5218]
### Describe the bug

I was using 2.9.0 and it is working fine. After switching to 2.12.0 it is not working anymore. The workaround that I did is to change to `@click.native` and it is now working again

**Comment by tmorehouse** [comment]
I am guessing you are placing the `@click` handler on a non-actionable avatar... One that doesn't have the `button` prop set, or one that doesn't have an `href` or `to` prop set.

Avatars were originally functional components (component that has no instance), but with the updates to avatar in the releases after v2.9, the component was converted to a full instance based component (to handle the ability to emit image load error and fallback to text or icon when the image fails to load).

If the avatar is not in button mode or link mode, then the custom click event will not be emitted.

So in your case, just add the `button` prop to your avatars to make them buttons, which is the correct semantic markup (specifically for screen reader users) when clicking on the avatar should trigger somthing to happen (or if triggering a URL/Route change, use hte link avatar props `href` or `to`).

**Comment by Dean-Christian-Armada** [comment]
Will this kind of behaviour apply on many `bootstrap-vue` components. Majority of my bootstrap-vue components I am just using `@click`

**Comment by tmorehouse** [comment]
Many components are functional instead of instance components, so `@click` is automatically a native event.  And components that are  full instance components that are interactive will emit a custom `click` event

**Comment by tmorehouse** [comment]
Basically, if you want a click handler on `b-avatar`:

```html
  <b-avatar button @click="clickHandler"></b-avatar>
```

Button avatars looks exactly like a regular avatar, but they appear in the document tab sequence so that keyboard only users can trigger the click, and they use `<button>` as a root element so that screen readers know that it is an interactive element.

The following would not be considered accessible to screen reader users or keyboard-only users:

```html
  <b-avatar @click.native="clickHandler"></b-avatar>
```

Screen reader users do not know that the element has an actionable function associated with it (the non-button avatar basically has an ARIA role equivalent to an image), and keyboard-only users can not reach the avatar through the document tab sequence and will never be able to "click" it.

**Comment by Dean-Christian-Armada** [comment]
Ok thanks I will use `<b-avatar button @click="clickHandler"></b-avatar>`
