### ISSUE TITLE
Datepicker z-index conflict with navbar

### ISSUE THREAD

**Issue by digitalcortex** [bootstrap-vue/bootstrap-vue#5221]
### Describe the bug

Datepicker calendar is displaying under the b-nav header. Setting z-index of navbar didn't work. (see attached screenshot)

### Steps to reproduce the bug

1. Add b-nav header to your view.
2. Add datepicker field

### Expected behavior

Datepicker calendar should be above navbar

### Versions

**Libraries:**

- BootstrapVue: 2.12.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Brave
- Version: Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

### Screenshots

<img width="728" alt="zindexissue" src="https://user-images.githubusercontent.com/62620810/79971441-5e03d080-84a5-11ea-92a1-e4d7298a2723.png">

**Comment by tmorehouse** [comment]
This is expected behavior with fixed position navbars.  The same thing happens with dropdown menus (which datepicker is based upon)

This is controlled by Bootstrap v4.4 SASS SCSS variables:

https://getbootstrap.com/docs/4.4/layout/overview/#z-index

![image](https://user-images.githubusercontent.com/2781561/80015049-8f7d9b80-84a7-11ea-9454-a5c398bc7897.png)

You can override these z-index's via SASS variable overrides when using the SCSS source files instead of the pre-compiled CSS files.

**Comment by digitalcortex** [comment]
> This is expected behavior with fixed/sticky position navbars. The same thing happens with dropdown menus (which datepicker is based upon)
> 
> ![image](https://user-images.githubusercontent.com/2781561/80026800-1e46e400-84b9-11ea-872f-486bfbb04820.png)
> 
> This is controlled by Bootstrap v4.4 SASS SCSS variables for z-index:
> 
> https://getbootstrap.com/docs/4.4/layout/overview/#z-index
> 
> ![image](https://user-images.githubusercontent.com/2781561/80015049-8f7d9b80-84a7-11ea-9454-a5c398bc7897.png)
> 
> You can override these z-index's via SASS variable overrides when using the SCSS source files instead of the pre-compiled CSS files.

Alright. Thanks.
