### ISSUE TITLE
Sorting a b-table which has inside b-rating, emits change event on b-rating

### ISSUE THREAD

**Issue by Guito** [bootstrap-vue/bootstrap-vue#5234]
Sandbox: https://codesandbox.io/s/2ng0s

Click on a table header to sort it and check the console. You can see that 2 events with null values are emitted.

It's expected that the event is not emitted if no value has changed.

**Comment by tmorehouse** [comment]
You may need to set a `primary-key` field (if your data has a unique id column field) so that b-table can provide a unique key for each TR element, rather than using the displayed index number, or perhaps set a unique key on the rating component that associates the rating to some uniqie value in the data row.

What is happening is that Vue is re-using the component, and updating the value

**Comment by Guito** [comment]
That fixes the problem :-) thanks

**Comment by tmorehouse** [comment]
Yeah, Vue tries to be helpful by re-using instances and DOM (for speed), but it can sometimes make issues like this happen.  But usually the `key` thing helps.
