### ISSUE TITLE
b-popover click blur triggered from inside popover

### ISSUE THREAD

**Issue by ryleyb** [bootstrap-vue/bootstrap-vue#5289]
### Describe the bug

If you hide something inside the popover when in "click blur" mode, it seems to close the popover.

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/ryleyb/bdwnLhgo/
2. Click on the primary button
3. The popover closes
4. Reopen the popover
5. Click anywhere else (nothing happens)

### Expected behavior

Interactions inside the popover in "click blur" mode should not cause the popover to close.

### Versions

**Libraries:**

- BootstrapVue: 2.13.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: Mac
- OS: Mojave
- Browser: Chrome
- Version: 81

**Comment by tmorehouse** [comment]
What is happening is that when the primary button button is being removed, it initially had focus due to clicking it, then the button is removed from the DOM tab order, and is blurred.  When it is blurred, the `document.body` becomes the active DOM element, which triggers the popover to close (since focus is no longer within the popover or the trigger element).

In the fiddle https://jsfiddle.net/1zkq6d54/ I have instructed the click handler to focus the `secondary` button before hiding the primary button

**Comment by ryleyb** [comment]
Interesting... I was trying to track the events but I wasn't able to find that type of thing...  What's the trick for finding when things like blur happen?

**Comment by tmorehouse** [comment]
Whenever a "focusable" element (i.e. buttons links, things with a tabindex), is focused and then visually hidden it will be blurred. and since the blur was not caused by moving focus to a new element (ie. <kbd>tab</kbd>, or clicking another element), the browser focuses the document body.
