### ISSUE TITLE
b-form-file drop with required not working

### ISSUE THREAD

**Issue by ddzobov** [bootstrap-vue/bootstrap-vue#5328]
### Describe the bug

When «required» is set and i'm dropping file into field it shows me error

### Steps to reproduce the bug

1. Set «required» to b-form-file
2. Drop file into dropzone
3. Submit form

### Expected behavior

Form submits

### Versions

**Libraries:**

- BootstrapVue: 2.13.0

**Environment:**

- Device: Mac
- OS: macOS 10.15.4
- Browser: Safari
- Version: 13.1

**Comment by tmorehouse** [comment]
Duplicate: #3673

This is due to the fact that one cannot set the `files` array (value) on native `<input type="file">`.  Standard click to brows is handled by a native file input, while drag and drop is handled via an opaque dropzone `<div>` (which is not tied to the native browser file input).  It is almost impossible to trigger a native browser required on a dropzone as we cannot assign the dropped filed to the file input value (as many browsers prevent the value of a file input from being changed programatically due to security reasons).
