### ISSUE TITLE
b-form-file assigning v-model value programmatically won't show the file name in input field

### ISSUE THREAD

**Issue by shidcordero** [bootstrap-vue/bootstrap-vue#5409]
### Describe the bug

When supplying the model value of b-form-file programmatically, it won't show the file name but the model value has the file object.

### Steps to reproduce the bug

I am using the code below to download the file from a url
```
const createFile = async (url, fileName, type) => {
  const response = await fetch(url)
  const data = await response.blob()
  return new File([data], fileName, { type })
}
```

this returns a file object and that return is I assign to my this.$v.image.$model which is the model assigned in my b-form-file. I also verified the code above by assigning the return value into a model of an image field to show as a thumbnail.

### Expected behavior

It should show the file name.

### Versions

**Libraries:**

- nuxt 2.0.0
- Bootstrap-Vue: 2.4.0

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome

**Comment by shidcordero** [comment]
Finally found the solution, and the solution is there's an undocumented property in b-form-file that is filled in order to really assign that the field has input value which is the selectedFile property. I added ref on the b-form-file component and assign the file value on it.

**Comment by tmorehouse** [comment]
Note `<b-form-file>` is a native `<input type="file">` input, which does not support setting the `value` of it (it will fail or cause an exception in many browsers), which is why the `v-model` on this control is technically only one-way (except for clearing the input). See https://bootstrap-vue.org/docs/components/form-file#clearing-the-file-selection.

I would recommend to **not rely on undocumented properties/methods** (they are undocumented for a reason, as the underlying code may change in a future release and break your app).

**Comment by shidcordero** [comment]
@tmorehouse so what would be your recommendation for this? Is it I will do reset then assign new value to v-model?

**Comment by tmorehouse** [comment]
The thing is you _can not_ set `v-model` on an `<input type="file">` to anything other than setting it to `null` or an empty array (`[]`). It is a limitation of the native browser file input.

The best option is to show a pre-set list of selected files below the input, and only use the input for allowing the user to select new files to add to your list.
