### ISSUE TITLE
<b-img-lazy> does not work with <picture>

### ISSUE THREAD

**Issue by amoralesdesign** [bootstrap-vue/bootstrap-vue#5442]
I'm trying to put new generation formats on my website. I use webp for all browsers except Safari.
That's why I have to use picture to load jpegs when a fallback occurs.

The problem is that <b-img-lazy> loads all the webp images, it doesn't do the lazy load function.

```html
<picture>
    <source
      srcset="{{ $image_url_webp }} 1x, {{ $image_retina_url_webp }} 2x"
      type="image/webp"
    >
    <b-img-lazy
      class="img-fluid"
      v-bind="{throttle: 10}"
      src="{{ $image_url }}"
      srcset="{{ $image_retina_url}} 2x"
      alt="{{ $name }}"
    />
</picture>
```

**Comment by tmorehouse** [comment]
Note the browser will immediately choose the source URL from the `<source>` tag if it supports `<picture>` and one of the images within the `srcset` is preferred.

**Comment by amoralesdesign** [comment]
And there's no way to get lazyload on the <source> defined within <picture>?

**Comment by tmorehouse** [comment]
Rather than using the `<picture>` element, you can specify `srcset` and `sizes` via props on `<b-img-lazy>`:  https://bootstrap-vue.org/docs/components/image#lazy-loaded-srcset-support

And place all your possible sources in the `srcset` prop. Unfortunately  one cannot specify the `type`s of image sources.

`<b-img-lazy>` has no knowledge of the `<picture>` element, nor the`<source>` element, as it is purely just a child (or sibling) of those elements.
