### ISSUE TITLE
Scoping bootstrap vue css does not work

### ISSUE THREAD

**Issue by adholland** [bootstrap-vue/bootstrap-vue#5552]
### Describe the bug

I need to scope the bootstrap  vue css as it is currently 'polluting' the parent page, which is something we need to avoid.

Any attempt to scope the css causes the vue components to no longer display correctly.

### Steps to reproduce the bug

My main template is as follows: -
```
<template>
    <div class="filemanager-app-main">
        <div class="app-main">
            <div v-show="!i18nLoaded" class="loader">
                <b-spinner variant="primary" />
            </div>
            <div v-show="i18nLoaded" class="filemanager-ui">
                <div id="app-main-components">
                    <FileManager :uer="uer" :groupsUrl="groupsurl" />
                </div>
            </div>
        </div>
    </div>
</template>
```

setting the style non scoped everything works fine: -
```
<style lang="scss" >
    @import '~bootstrap/scss/bootstrap.scss';
    @import '~bootstrap-vue/src/index.scss';
   ...
```

however the only solution i've found to scope the bootstrap vue css is as follows: -
```
<style lang="scss" scoped>

::v-deep .app-main {
    @import '~bootstrap/scss/bootstrap.scss';
    @import '~bootstrap-vue/src/index.scss';
    ...
```

This no longer pollutes (it is scoped) but the fonts, button variant colours, the popover etc no longer look correct.

Could someone please help me understand what I'm doing wrong? Is there a way to scope bootstrap vue, that will work without issue for all the child components?

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Vue: 2.6.11

**Comment by adholland** [comment]
@tmorehouse I'm hoping you could possibly help me.

**Comment by Hiws** [comment]
I tested this in a Vue-CLI app, and it looks to work correctly.
The reason the font is looking wrong, is because by default Bootstrap applies some basis font size, style and family to `body`.
But `body` doesn't exist in your scope, so you need to reapply them within your scope, if you want them to be used.

The issue with your popover, is because by default, popovers, tooltips and modals (and maybe a few other components), are appended to `body` when rendered. But since your styles are scoped, they aren't available there.

That's why I've added `container: 'scoped-styles'` to the popover, so that it gets rendered where our popover styles are available.
For modals you will need to use the `static` prop, to render them in the document they're placed at.

![W9y8Y70 1](https://user-images.githubusercontent.com/7057431/86480698-cd702900-bd4e-11ea-85f2-14b69d7cd21b.png)

### App.vue
```html
<template>
  <div id="app">
    <b-btn to="/home">Home</b-btn>
    <hr />

    <div id="scoped-styles">
      <b-btn
        to="/home"
        v-b-popover="{ container: 'scoped-styles', content: 'FooBar' }"
        title="Hello World"
        variant="primary"
      >
        Home
      </b-btn>
      <hr />
      <Test />
    </div>
  </div>
</template>

<script>
import Test from "@/components/Test.vue";
export default {
  components: {
    Test
  }
};
</script>

<style lang="scss" scoped>
#scoped-styles::v-deep {
  @import "~bootstrap";

  /* Default body styles */
  margin: 0;
  font-family: $font-family-base;
  @include font-size($font-size-base);
  font-weight: $font-weight-base;
  line-height: $line-height-base;
  color: $body-color;
  text-align: left;
  background-color: $body-bg;

  @import "~bootstrap-vue";
}
</style>
```

### Test.vue
```html
<template>
  <b-btn variant="success">
    Child Button
  </b-btn>
</template>
```

**Comment by adholland** [comment]
@Hiws Thank you so much for the help, and so quickly.

Let me see if I can make all the relevant changes and get back to you. 

Cheers.

**Comment by adholland** [comment]
@Hiws OMG just tried it all out and it works! I've spent ages going through this and so many deadends on this one, so I'm really pleased you could help. Much appreciated.

TBH from googling this is something that has come up a lot and there hasn't been any clear set of instructions of how to add the bootstrap vue css scoped (or I missed it). What you have provided is perfect and I'm sure would be helpful to others - so would be worth adding to the docs in my opinion.

Anyway thanks again. So happy!
