### ISSUE TITLE
retro-compatibility broken

### ISSUE THREAD

**Issue by andrelec1** [bootstrap-vue/bootstrap-vue#5587]
b-table slot seem changed ...

my code ( 02-07-19 ) 
` <template slot="unit" slot-scope="ctxUnit">`

need to be replaced by
` <template slot="cell(unit)" slot-scope="ctxUnit">`

packtage.json:

    "bootstrap": "4.0.0",
    "bootstrap-vue": "2.0.0-rc.1"
    "vue": 2.6.11

**Comment by Hiws** [comment]
The slot naming was changed in `v2.0.0-rc.28`, and then again in the next release `v2.0.0`.
`v.2.0.0.` also introduced a few other breaking changes which you can see in the [changelog](https://bootstrap-vue.org/docs/reference/changelog#v200)

However, based on your `package.json`, it looks like you've locked your versions. So you should be able to stick with the old naming syntax.
I would advice you run the docs for version `v2.0.0-rc.1` (or upgrade) to avoid confusion since a lot of changed since the older version you're using.
You can download the repo for version `2.0.0-rc.1` (https://github.com/bootstrap-vue/bootstrap-vue/tree/v2.0.0-rc.1) and generate the docs locally.

**Comment by andrelec1** [comment]
Ho god, its a dependency of dependency in my project that use the wrong version ...

fork and force use `"bootstrap-vue": "2.0.0-rc.26"`  and the project re-work ;)
