### ISSUE TITLE
b-sidebar using v-slot:default cause sidebar to become lazy

### ISSUE THREAD

**Issue by rizen** [bootstrap-vue/bootstrap-vue#5662]
### Describe the bug

If you override the default header and then use v-slot:default to bring in the hide function the sidebar becomes :lazy="true" even though it wasn't originally. 

### Steps to reproduce the bug

I've created a fiddle for this: https://jsfiddle.net/gsmwj97r/2/

1. Go to the fiddle
2. Note that there are 2045 results.
3. Click "Additional Filters" button to open the sidebar.
4. Click "blue".
5. Note that there are 227 results.
6. Click the "x" button or the "Additional Filters" button to close the sidebar
7. Note that there are 2045 results. That's because the search refinement has been removed from the DOM and thus gone out of scope.

### Expected behavior

If you remove the v-slot:default and the button click that references hide() then repeat the steps outlined above you will notice that the 227 results remain after clicking on blue and closing the sidebar. This is the expected behavior, I'd just like to get the expected behavior while also being able to create my own close button.

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.2
- Vue: 2.6.7 

**Environment:**

- Device: Mac
- OS: 10.15.5
- Browser: Safari or Chrome or Firefox
- Version: 13.1.1

### Demo link

https://jsfiddle.net/gsmwj97r/2/

### Additional context

I'm sure there's a way to replicate this without algolia, it's just my use case and thus it was the easiest way for me to create the bug report.

**Comment by rizen** [comment]
Note that this does not occur when using v-slot:footer.

**Comment by Hiws** [comment]
It looks like the sidebar isn't becoming lazy.
If you inspect the DOM you can see the elements are still there instead of a comment, like there is if you add `lazy` to the sidebar.

What looks to be happening however, is that it's causing a re-render when close which causes your search component to reset, and give you the behavior you're seeing.
I'm not sure why that's happening, when it doesn't when utilizing no `<template>` for the default slot. 

You can work around it in two ways from what I found. Either as you mentioned, is to remove the `<template v-slot:default>`, and then instead use `v-b-toggle.sidebar-id` on your button instead of the `hide` function.

The other option is to add `v-once` to your `ais-refinement-list` component, which forced it to only render once, meaning it wont re-render when the component closes.

**Comment by rizen** [comment]
Thank you. I really appreciate the work around. Not sure why I didn't think of that.

**Comment by jackmu95** [comment]
@rizen @Hiws I've looked into this and the re-render when using the slot scope is caused by the `visible` property which changes when the `<b-sidebar>` is hidden. The is nothing we could do about this.

**Comment by rizen** [comment]
The work around that @Hiws gave me works for my case.   You may want to document this quirk for others.
