### ISSUE TITLE
Problems when adding via 'vue add bootstrap-vue'

### ISSUE THREAD

**Issue by CuteNickychan** [bootstrap-vue/bootstrap-vue#5706]
So i tried installing bootstrap-vue via vue/cli and it worked fine until it asked me: 
`Use babel/polyfill? Yes`
after wich it threw `TypeError: range.split is not a function` i did have some problems before with package.json but i thought i fixed them by renaming package-lock.json (Ithought i might have shut down my pc at the wrong time)

**Comment by Hiws** [comment]
The Booststrap-Vue plugin isn't maintained by Bootstrap-Vue.
You can try asking at the plugin repo <https://github.com/GregYankovoy/vue-cli-plugin-bootstrap-vue>

Instead of using the Plugin you can follow [these steps](https://bootstrap-vue.org/docs#using-module-bundlers) on the getting started page, to set it up yourself.
