### ISSUE TITLE
b-icon title support

### ISSUE THREAD

**Issue by mariusa** [bootstrap-vue/bootstrap-vue#5711]
### Is your feature request related to a problem? Please describe...

I'd like to set a title on <b-icon> / <b-icon-specific-icon> elements

### Describe the solution you'd like

`<b-icon-envelope :title="user_email"></b-icon-envelope>`

### Describe alternatives you've considered

wrapping in a parent element having a title set

### Additional context

https://stackoverflow.com/questions/10643426/how-to-add-a-tooltip-to-an-svg-graphic

the SVG <title> element and the default browser rendering it conveys? (Note: this is not the same as the title attribute you can use on div/img/spans in html, it needs to be a child element named title)

It does work:
```
<svg viewBox="0 0 16 16" width="1em" height="1em" focusable="false" role="img" aria-label="envelope" xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi-envelope b-icon bi">
    <title>Aaaa</title>
    <g><path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383l-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"></path></g>
</svg>
```

**Comment by ineshbose** [comment]
This creates a problem.

```html
<b-icon icon="info-circle" v-b-tooltip.hover title="Hello world!"></b-icon>
```

Here, `title` prop is for `b-icon` and not for `b-tooltip`. One solution is wrapping the icons in `b-button`, but not a very good solution in my opinion since the icons are simpler and buttons also have the sizing/padding factor; for example, in my case, I would need to change the code everywhere and also ensure that the `b-button` (even with `link` variant) does not stick out.
