### ISSUE TITLE
b-form-tags add line on mobile view

### ISSUE THREAD

**Issue by ochiers** [bootstrap-vue/bootstrap-vue#5798]
### Describe the bug

When you use b-form-tags on mobile and you have at least one tag, then the input is on multiple line.

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/5451658/93485187-19208080-f903-11ea-8a0e-94a13936ac44.png)

1. Go on https://bootstrap-vue.org/docs/components/form-tags#b-form-tag-helper-component in Tag validation section with your mobile
2. Add a tag
3. See the new line

### Expected behavior

I want to click next to the last tag and have focus on input without new line like on PC (large view).
![image](https://user-images.githubusercontent.com/5451658/93486284-4e799e00-f904-11ea-81db-75f57bfeb29c.png)

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- Device: PC, mobile
- OS: Windows, Android, iOS
- Browser: Chrome, Firefox, Safari

### Demo link

 https://bootstrap-vue.org/docs/components/form-tags#b-form-tag-helper-component

**Comment by jackmu95** [comment]
@ochiers By default, BootstrapVue adds the `w-100` utility class to the `b-form-tags-input` and sets it's `min-width` to `5rem`. This is why the `b-from-tags-field` gets moved to the next line on smaller/mobile devices after a certain amount of tags.

We could remove the `w-100` utility class since `flex-grow-1` is set anyway.
But even with that you have to give the `b-form-tags-input` a certain `max-width` or `width` to stay longer in the same line.
