### ISSUE TITLE
Input group don't work with vue-class-component

### ISSUE THREAD

**Issue by yoshiyes** [bootstrap-vue/bootstrap-vue#5985]
### Describe the bug

The input tag isn't rendered if the project uses "vue-class-component".

### Steps to reproduce the bug

1. Add Boostrap Vue and Vue-class-component
2. Add input group 
3. Transform class to Vue component.
```
<template>
    <b-input-group prepend="Name">
        <b-form-input></b-form-input>
    </b-input-group>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";

@Component({})
export default class Test extends Vue {}
</script>
```
### Exemple

With vue-class-component :
![image](https://user-images.githubusercontent.com/20050570/97693869-112b3300-1aa2-11eb-86c0-283cca712d49.png)

Without :
![image](https://user-images.githubusercontent.com/20050570/97693956-35870f80-1aa2-11eb-9c88-4914cfecfc3c.png)

### Versions

**Libraries:**

- BootstrapVue: 2.18.1
- Bootstrap: 4.5.3
- Vue: 2.16.12

**Environment:**

- OS: Windows 10
- Browser: Edge, Firefox, Chrome

**Comment by jackmu95** [comment]
I've created CodeSandbox and it works as expected:
https://codesandbox.io/s/gifted-water-ys5q5?file=/App.vue

**Comment by tiagoroldao** [comment]
@yoshiyes ran into this issue myself and haven't been able to fully parse **why** it happens, but a couple of findings that may be useful to you:

- I had by mistake a component using a Class (`class MyComponent extends Vue`) **without** the `@Component` annotation. Because the component was basically dumb markup it never threw an error, but it messed up slot handling on functional components (`b-input-group` being one)
- It has to do with an internal `isCompiled` flag that gets set, and because of that, slot arrays do not get normalized
- Adding this `@Component` annotation fixed my issue (it is a bad bug, as it fails silently, or rather it works until it doesn't)

**Comment by tiagoroldao** [comment]
PS this is definitely not a `bootstrap-vue` bug, it is either weirdness of vue-class-component that needs documenting, or a edge case in the vue compiler

**Comment by harrylu99** [comment]
Having this problem as well, I already have` @Component` annotation but it still showing undefined
