### ISSUE TITLE
Documentation: Providing incorrect advice about limitations

### ISSUE THREAD

**Issue by MechJosh0** [bootstrap-vue/bootstrap-vue#5998]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/components/form-group#feedback-limitations
> Feedback limitations
> Note: When using `<b-input-group>`, `<b-form-file>`, `<b-form-radio-group>`, `<b-form-radio>`, `<b-form-checkbox-group>` or `<b-form-checkbox>` inside a `<b-form-group>`, setting an invalid (or valid) `state` on the `input` alone will not trigger the invalid (or valid) feedback to show (due to limitations with the new Bootstrap v4 validation CSS). To get around this, you must also set the invalid/valid `state` on `<b-form-group>`. Native browser validation will not trigger the invalid feedback to show when using one of the above mentioned form controls.

### Additional context or description

Unless I'm reading the documentation wrong, I believe the above section is incorrect. My codesandbox example shows that you **can** use `state` on the `input` alone and it'll trigger the feedback to show.

https://codesandbox.io/s/brave-butterfly-ooq5b

**Comment by Hiws** [comment]
That's because you're using `<b-form-input>`, which isn't mentioned in the note, and you're also not using the invalid/valid feedback in your example.

You can see the difference here: <https://codesandbox.io/s/goofy-breeze-iwyi1?file=/App.vue>

Notice how the `Thank you!` and `Please select something!` doesn't show up when only setting `state` on the `<b-form-radio>`, but it does show up when you set it on both `<b-form-radio>` and `<b-form-group>`.

You can see underneath that this isn't the case on `<b-form-input>`, which is why this component is not mentioned in the note.

**Comment by MechJosh0** [comment]
@Hiws Ah I see, I'm using `b-form-input` to handle the `state`, but the documentation is referring to using `b-form-group` state and feedback attributes. Thanks for clarifying.
