### ISSUE TITLE
Button Remains Greyed Out after executing document.getElementById('button').removeAttribute('disabled')

### ISSUE THREAD

**Issue by JF0001** [bootstrap-vue/bootstrap-vue#6031]
### Describe the bug

I initially set the disabled attribute of a button in the html code upon loading the page as follows:
`<b-button id="button" type="button" disabled="disabled" v-on:click="function()">Button</b-button>`

Afterwards, upon clicking on another button, the following code is triggered in Javascript.
`document.getElementById('button').removeAttribute('disabled')`

The button does become clickable and is thus disabled. However, it remains greyed out, even if it actually is enabled. Shouldn't its colour also be changed automatically upon enabling it?

### Steps to reproduce the bug

Please see code above.

### Expected behavior

Button shouldn't be greyed out (at least this is what I would expect) after removing the disabled attribute on button via JavaScript.

### Versions

**Libraries:**

bootstrap-vue@2.16.0

**Environment:**

Ubuntu Linux Version 16

**Comment by Hiws** [comment]
`<b-button>` does not use the `disabled` attribute, it instead has a `disabled` property which takes a boolean value.
This property adds the `disabled="disabled"` attribute and `disabled` class to the button.

The reason your button remains greyed out is because of the `disabled` class.

You're doing things the "javascript" way by using `document.getElementById('button')`, which isn't recommended, as manipulates the DOM directly and can cause side-effects such as this.
You should instead do things the Vue way and bind a Boolean data property to the `disabled` prop, which you can toggle in your method.

https://codepen.io/Hiws/pen/oNLQNzm

**Comment by JF0001** [comment]
Thank you Hiws for your answer and detailed explanation. JF
