### ISSUE TITLE
Templated b-list-group-item not rendering properly

### ISSUE THREAD

**Issue by Tannz0rz** [bootstrap-vue/bootstrap-vue#6061]
### Describe the bug

Templated "b-list-group-item" element containing "b-form-input" does not render text until text is modified.
EDIT: Additionally, the '-' "b-button" of the templated element does not trigger the "click" event, nor are the specified properties assigned.

### Steps to reproduce the bug

1. Enter any value in "Variable name" input field
2. Enter any value in "Variable value" input field
3. Click the "+" button
4. A new list group item will be instantiated with the text values set but not being rendered.

### Expected behavior

The text should be immediately visible, but is not unless you begin to enter values into either "Variable name" or "Variable value".

To circumvent this problem, I manually force an update in an async fashion after a set amount of time. This portion of the code is commented out and you may uncomment it to see the issue rectified.

### Versions

**Libraries:**

- BootstrapVue: 2.19.0
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Dell Inspiron 13 7373
- OS: Ubuntu 20.04.1 LTS
- Browser: Firefox
- Version: 82.0.3

### Demo link

https://codepen.io/Tannz0rz/pen/vYKwZxm

**Comment by Hiws** [comment]
<b-list-group> is not the issue in this case.
The issue is you're using `domProps` on `<b-form-input>` instead of `props`. This will cause issues since `<b-form-input>` wont know what the value is before a recompute. That's why you should pass values to the component props, and not the dom on custom elements.
You should also use the `staticClass` property when using a render function instead of passing it to the dom.

There was various other issues in the codepen, I think I've corrected most of them in this example
<https://codepen.io/Hiws/pen/zYBQPJr>

**Comment by Tannz0rz** [comment]
I see, thank you kindly for the assistance @Hiws. Hopefully others will find this should they make similar mistakes as I had.

**Comment by Tannz0rz** [comment]
I see, thank you kindly for the assistance @Hiws. Hopefully others will find this should they make similar mistakes as I had.
