### ISSUE TITLE
b-table re-renders on row-details toggle

### ISSUE THREAD

**Issue by rphes** [bootstrap-vue/bootstrap-vue#6064]
### Describe the bug

When table row details are shown or hidden by setting `_showDetails` on the applicable data item, the entire table (or at least all other detail views) is re-rendered, causing issues when their contents are rendered from side-effects. It's also sub-optimal in terms of performance.

### Steps to reproduce the bug

See demo. 

```html
<div id="app">
  <div>
    Click a row to open details
  </div>
  <b-table @row-clicked="toggleDetails" :items="items">
    <template #row-details>
      {{ rowDetails() }}
    </template>
  </b-table>
</div>
```

```js
new Vue({ 
  el: "#app",
  data() {
    return {
      items: [
        { age: 40, first_name: "Dickerson", last_name: "Macdonald" },
        { age: 21, first_name: "Larsen", last_name: "Shaw" },
        { age: 89, first_name: "Geneva", last_name: "Wilson" },
        { age: 38, first_name: "Jami", last_name: "Carney" }
      ]
    };
  },
  methods: {
    toggleDetails(item) {
      if (item["_showDetails"]) item["_showDetails"] = false;
      else this.$set(item, "_showDetails", true);
    },
    rowDetails() {
      console.log("recompute");
      return new Date().toString();
    }
  }
});




```

Observe how details for every open row change whenever a single one is opened or closed. Console messages further prove contents are recomputed upon each click.

### Expected behavior

Currently open row details should not be re-rendered when an additional row details is toggled.

### Versions

**Libraries:**

- BootstrapVue: 2.19.0
- Bootstrap: 4.5.3
- Vue: 2.16.12

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Safari, Chromium, Firefox

### Demo link

https://jsfiddle.net/3nrhg2u4/

### Additional context

May be related to https://github.com/bootstrap-vue/bootstrap-vue/issues/6062

**Comment by serge-kilimoff** [comment]
Hello, I am having the same problem with the "selectable" property. The table is fully recalculated with each selection.
One assumption would be the "tbody-tr-class" property which forces the entire DOM of the table to be recomputed.

For example, here with 2,000 lines: https://jsfiddle.net/fnhcsL61/
When we click on a row to choose it, we have a significant latency time because of the recalculation of the entire table.

In my code, I have much more complex calculations on the lines and this untimely rendering causes delays starting from a hundred lines.
