### ISSUE TITLE
how to get data with async in one column

### ISSUE THREAD

**Issue by lifeblood** [bootstrap-vue/bootstrap-vue#6068]
![image](https://user-images.githubusercontent.com/3621748/99827502-ad71c280-2b94-11eb-8491-b032929733fe.png)

how to get data with async in one column when the table content rendered.

**Comment by funkyfisch** [comment]
Can you provide more details?
Is the entire column data loaded by a single request?
Is each cell data of this column loaded independently?

In the case of the latter, I would make the column a custom template, making it stateful, and hook events to each cell so that when one of the column cells is loading, you display a spinner, and when you get a result back, you update its state and display a value instead of a spinner.

Can write a sample later on if you are struggling with it.

**Comment by lifeblood** [comment]
have you telegram account?

**Comment by funkyfisch** [comment]
No, but I guess you can always email me.
If my idea solved your problem, it would also be nice to post it here so it others in the future can refer to it!
