### ISSUE TITLE
Three big problems found

### ISSUE THREAD

**Issue by lucapu88** [bootstrap-vue/bootstrap-vue#6132]
It is incredible that a library of this size, well known and used, has a lot of limitations ...

- date picker component that does not give the possibility of multiple selection of dates.
- timepicker component does not give the possibility to write timetables by hand instead of having to click every time.
- component card does not give the possibility to insert an image with src path of my local, but only web link! and to be able to insert an image from my local folders you need to use another b-img component which in practice cancels the usefulness of b-card.

And that's just the beginning of what I found in a few weeks of work! I had to change the library in the middle of the project, and I noticed the low quality of the responses on your discord channel ..... answers like: I don't know, maybe, who knows ... people are not banned, you have banned me because I did not write in English, but in my language ... it's absurd! you have an almost totally inactive community and I get banned for asking questions!
I will discourage anyone from using this library, unless you put me back on the discord channel.

**Comment by Hiws** [comment]
I didn't ban you because you spoke in another language.
The reason i banned you from the discord server was because of what you said in that language.

Telling someone to go kill themselves because they don't know the answer to your question isn't the right way to go about things, and that's why you were banned.
If you don't like the library or community, there's plenty of others for you to chose from.
