### ISSUE TITLE
[form-file] "Choose File" does not trigger a file selector

### ISSUE THREAD

**Issue by yhosun** [bootstrap-vue/bootstrap-vue#644]
From #628

version: 1.8.0

https://jsfiddle.net/wbx7hcy8/2/

In the JSFiddle, clicking "Choose File" button does not trigger a file selector while it does when the input "No File Chosen" is clicked.  Please, note that I added `width:100%` to `b-form-file` and it looks like the `input` starts mis-aligning with the component root element.

**Comment by tmorehouse** [comment]
custom-file input unfortunately doesn't really support 100% width (even when using native bootstrap).

This is due to how the control is created.  the original file input element is set to an opacity of 0 (transparent), and placed *over* top of the custom "input" spans.

The browser native file input, depending on browser, doesn't always support setting a width.  So the custom spans are set to fill the width of the space the native ifile input takes.

When you set the custom control wids, you are only affecting the width of the spans that make up the custom control interface.  The native browser input (which is sitting over the spans isn't being resized.

You can try targeting the custom interface plus the native file input via CSS:
```css
.custom-file, 
.custom-file input[type="file"] {
  width: 100%;
}
```
But note that this may not work on all browsers and some browsers wont let the setting a width of the input, or have limited CSS support. So you will run into the same situation where you can only lick the left portion of the input.

And note this is a limitation of the Bootstrap V4 CSS (V4.alpha.6).  This may change in V4.beta.1 when they release it.

You could open an issue at the bootstrap repo at https://github.com/twbs/bootstrap/issues

**Comment by yhosun** [comment]
Thanks @tmorehouse .  For now, I removed the width attributes from my CSS.
