### ISSUE TITLE
Bootstrap-vue dynamic toast isn't working

### ISSUE THREAD

**Issue by Osman-Rafi** [bootstrap-vue/bootstrap-vue#6454]
I am trying to use dynamic toast from bootstrap-vue. Here what I am trying to do:

`` 
<template>
       <b-button @click="handleClick(education)"></b-button>
</template>
``

```<script>
import { notificationToast } from "@/components/NotificationToast";

export default{
 methods:{
  handleClick(){
   notificationToast(true);
 }
}
</script>
```
**NotificationToast.js**

```import Vue from "vue";
import { BVToastPlugin } from "bootstrap-vue";

Vue.use(BVToastPlugin);

let notificationToast = (append = false) => {
  this.$bvToast.toast(`This is toast`, {
    title: "BootstrapVue Toast",
    autoHideDelay: 5000,
    appendToast: append,
  });
};

export { notificationToast }; 
```

Whenever I click on the button it show the error :

TypeError: Cannot read property '$bvToast' of undefined

As it is mentioned in the [doc](https://bootstrap-vue.org/docs/components/toast#toasts-on-demand), I imported BVToastPlugin, still the problem is occurring. What to do? 
****
### Versions

**Libraries:**

- BootstrapVue: ^2.16.0
- Bootstrap: ^4.5.2
- Vue: ^2.6.12

**Comment by Hiws** [comment]
That's because `this` in your external method doesn't reference your component instance which has the `$bvToast` property.
That's why the error is telling you that `this` is undefined.

You can get around this by registering your imported function as a method, and then using the method in your component.
However, you will need to use a Function and not an arrow function.
```js
export function notificationToast(append = false) {
  this.$bvToast.toast(`This is toast`, {
    title: "BootstrapVue Toast",
    autoHideDelay: 5000,
    appendToast: append
  });
}
```
Then in your component
```js
import { notificationToast } from "@/components/NotificationToast";

export default{
 methods:{
  notificationToast,
  handleClick(){
    this.notificationToast(true);
  }
}
```

Alternatively you can use `Function.prototype.bind()`.

```js
import { notificationToast } from "@/components/NotificationToast";

export default{
 methods: {
  handleClick(){
    notificationToast.bind(this)(true);
  }
}
```
