### ISSUE TITLE
Input type="number" Mozilla Firefox

### ISSUE THREAD

**Issue by iarturovich** [bootstrap-vue/bootstrap-vue#6530]
When hovering over the increment/decrement buttons that are in the input, it is not possible to click on these buttons. Only 1px on the right. I tried to remove the padding class .form-control now you can click these buttons

### Versions

**Libraries:**

- BootstrapVue: 2.#.#
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: PC
- OS: Windows 10, Ubuntu
- Browser: Mozilla Firefox, Developer Edition

**Comment by Hiws** [comment]
This seems to only be an issue on the "Developer Edition", and not the latest stable release of FireFox.
This issue is also present without using `<b-form-input type="number>` and instead a native `<input type="number>` with the class `form-control` applied.

I'd say this is a bug in the Firefox Dev version, and even if it's not. It will have to be fixed upstream in Bootstrap, as it's CSS related.
