### ISSUE TITLE
Programmatic row selection

### ISSUE THREAD

**Issue by FiniteRealityTech** [bootstrap-vue/bootstrap-vue#6537]
Steps to reproduce:

I created a basic method to select all the rows on the page. It was simple and works great.

I have a second method, this is a "select all rows in table" button click event. My first step is to set the perPage to "all" or total row count. All rows are displayed on one page, however, no rows are selected. If I select the button again, all the rows will be selected.

  selectAllRows() {
    this.perPage = this.totalRows;
    this.selectAllRowsOnPage();
  },
  selectAllRowsOnPage() {
    this.$refs.selectableTable.selectAllRows();
    },
    
What I expect to happen is click the button one time to update the number of entries displayed and select all the entries. I have tried refresh and update but neither seemed to work. It also does not work if I try to call the method twice.

I tried this.$refs.selectableTable.refresh(), update, refreshed, updated.

Only refresh() seemed to not throw an exception but did not change the outcome of the method. I hope it's not anything simple but I have been trying for too long. Thanks in advance!

**Comment by rahulmotwani1996** [comment]
@FiniteRealityTech Hello, 
if you want to display all the rows first you need to disable paginations by setting per page value to 0.
async selectAllRows() {
this.perPage = 0;
await this.$nextTick();     
this.$refs.selectableTable.selectAllRows();
}

under the hood when ever we change the per page it changes some data in the table due to which the next call has no effect. so waiting for the next tick it will wait for the per page to get reflected.

then using the selectAllRows the data will be selected.

Hope this helps. :)

**Comment by FiniteRealityTech** [comment]
At least I was close in stating what I needed, the right syntax I did not know though, thank you! I used perPage with some other things, so turning it to zero wasn't quite the effect I wanted but setting it to totalRows works for me just great. It's good to know I can set it to zero though because that's how I will set it up next time. Thank you so much!
