### ISSUE TITLE
Why not shown b-alert when assign a string(not nullish) to b-alert.show?

### ISSUE THREAD

**Issue by ssehoony** [bootstrap-vue/bootstrap-vue#6599]
### Describe the bug

If assign a string(not nullish) to b-alert.show, displayed b-alert in Bootstrap-vue v2.9.0.
But Bootstrap-vue v2.10.0 doesn't show b-alert.
So, my old codes are not working.
Is this the intended behavior?

### Steps to reproduce the bug

```html
const alertMsg = 'test message';
...
<b-alert :show="alertMsg">
    {{ alertMsg }}
</b-alert>
```

### Expected behavior

Shown alert when assign not nullish string to b-alert.show like Bootstrap-vue v2.9.0

### Demo link

1. bootstrap-vue v2.9.0 : alert shown when assign a string to b-alert.show
    https://jsfiddle.net/7jh4rsLp/
1. bootstrap-vue v2.10.0 : alert not shown when assign a string to b-alert.show
    https://jsfiddle.net/vjfagpkz/
1. bootstrap-vue v2.10.0 : alert shown when assign Boolean(string) to b-alert.show
    https://jsfiddle.net/azfp68cj/

**Comment by Hiws** [comment]
Looks to be these changes in the version `2.10.0` commit, that might've caused the change in behavior.
However, since the docs state that the `show` prop should be able to take a string, I'll mark it down as a bug.

![chrome_Yi2KNomu3J](https://user-images.githubusercontent.com/7057431/117258835-b0642500-ae4d-11eb-8c66-2370eaaa3c9e.png)


For now you'll have to convert your value to a Boolean it seems.
Either with `:show="Boolean(string)"` or `:show="!!string"` should work.

**Comment by Hiws** [comment]
Did a bit more digging and found an older comment which states:

https://github.com/bootstrap-vue/bootstrap-vue/issues/4719#issuecomment-581548658
> Type String is supported for when passing numbers as strings instead of a native Number primitive (i.e. '5' instead of 5).
 
 So it looks like the behavior you previously had wasn't intended, and the commit i previously screenshot fixed it.
 You'll have to convert your string to a boolean with the previously mentioned methods in the newer versions.

**Comment by ssehoony** [comment]
Thank you. I understand.
