### ISSUE TITLE
BTable: sort direction icons are not set properly when using no-local-sorting and sortKey

### ISSUE THREAD

**Issue by paulgv** [bootstrap-vue/bootstrap-vue#6602]
### Describe the bug

When rendering a `BTable` with `no-local-sorting` and custom sort keys defined as `sortKey` in the `fields` array, the sorting direction icons are not set properly in the table header.

### Steps to reproduce the bug

1. Create a basic `BTable` which receives sorted `items`. At least one field should have a custom `sortKey`, and `no-local-sorting` should be set.
2. Try sorting by one of the fields that have a custom `sortKey`.
4. Notice how sorting direction icons are not updated in the header.

### Expected behavior

The sorting direction icons should be properly updated, regardless of whether the field defined a custom `sortKey` or not.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

### Demo link

Here's a small repro: https://jsfiddle.net/paulgv/4u19v80o/
When sorting by first name or age, everything seems to be working properly because those fields are not using a custom `sortKey`. However, notice how sorting by last name does result in the items sorting being updated properly, but the icon in the **Last name** header is not updated.

### Additional context

| Custom `sortKey` | Default sort key |
| --- | --- |
| <img width="621" alt="Screen Shot 2021-05-06 at 9 59 16 AM" src="https://user-images.githubusercontent.com/4895885/117311191-f9b67380-ae51-11eb-8156-2f79bc07dbbd.png"> | <img width="618" alt="Screen Shot 2021-05-06 at 9 59 36 AM" src="https://user-images.githubusercontent.com/4895885/117311202-fb803700-ae51-11eb-9612-072bce4a32d7.png"> |

**Comment by aleksandertabor** [comment]
The problem is that when sorting attribute `aria-sort` of column header is not changing to `ascending` or `descending`. It's still `none`. Sorting icons change bases on this attribute.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/22729643/117367942-248ce000-aec3-11eb-85d1-c1b16636171f.gif)

This error also occurred for me. I have temporarily changed to not use `sortKey` but dynamically change key before calling to API or you can do it on the backend.

## Versions
### Libraries:

BootstrapVue: 2.21.2
Bootstrap: 4.5.3
Vue: 2.6.12

**Comment by Hiws** [comment]
Hello, could you confirm that it's working correctly in the following codesandbox?
https://codesandbox.io/s/bootstrapvue-starter-project-forked-3b7pt?file=/App.vue

**Comment by aleksandertabor** [comment]
> Hello, could you confirm that it's working correctly in the following codesandbox?
> https://codesandbox.io/s/bootstrapvue-starter-project-forked-3b7pt?file=/App.vue

Confirmed. It's working.
