### ISSUE TITLE
b-input plaintext :readonly="false" ignored.

### ISSUE THREAD

**Issue by dan-whitehouse** [bootstrap-vue/bootstrap-vue#6604]
### Describe the bug

The readonly attribute is ignored when plaintext is set.

### Steps to reproduce the bug

`<b-input value="Example Text" plaintext :readonly="false"></b-input>`

### Expected behavior

I expected that I should be able to override the readonly state of plaintext by setting the readonly attribute.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.3.1
- Vue: 2.6.12

**Comment by Hiws** [comment]
> Set the form control as readonly and renders the control to look like plain text (no borders)

Based on description of the `plaintext` prop, i would say that's intended.
But I'm not sure I see why users wouldn't be allowed to overwrite it if they wanted to, except for the UX.

A slight workaround (though not 100% the same), is to add the `form-control-plaintext` yourself, instead of relying on the prop.
```html
<b-input  class="form-control-plaintext"></b-input>
````

**Comment by Hiws** [comment]
I'm not seeing that behavior on the docs. Can you create a reproduction?
Here's what I get, the only difference being that the input using the prop is slightly taller because of the `height` that `form-control` sets,
![chrome_jdPTb5ZdHt](https://user-images.githubusercontent.com/7057431/117467661-2d79c200-af54-11eb-8409-78829d2d3315.png)
