### ISSUE TITLE
Accessibility for Dropdowns

### ISSUE THREAD

**Issue by ednelson89** [bootstrap-vue/bootstrap-vue#6687]
Description:

The tag can have aria-labels applied to it, but the aria-labels get applied to the surrounding divs. The screen-readers don't read that off, because basic tab behavior causes it to focus the button, not the parent div with the aria-label.

example of dropdown used in a filter, only including the relevant attributes:
```
 <b-dropdown
    id="test1"
    :text="pointToFilterItemInList()"  // just a function to populate the selected items text, returns a string
    aria-label="Dropdown List for Search Filter Options"
    >
```
This example will produce a wrapper div that contains a button tag:

`<div id="test1" aria-label="Dropdown List for Search Filter Options"><button id="test1__BV_toggle_" aria-haspopup="true" aria-expanded="true" type="button" class="btn dropdown-toggle btn-outline-primary btn-block">{{text String returned by function}}</button>`

What we should expect is that the element that will take the screen-reader's focus, in this case, the rendered button, should take to aria-label props (or a pairing with a label from an aria-described by.) I was able to manually add for="test1__BV_toggle_" to a paired label, but the screen reader would then not read out the current selected value of the dropdown, instead just reading the label and 'button collapsed submenu' status. 
### Versions

**Libraries:**

- BootstrapVue: 2.18.1
- Vue: 2.6.12
- NVDA 2020.4

**Comment by jakedolan** [comment]
**As a workaround:**

You can add additional context to the accessible name via the button text.
```{{ selectedValue }} <span class="hidden_accessibly">selected in list of search filter options</span>```

For reference, see [WCAG 2.1 - Including the text of the visible label as part of the accessible name](https://www.w3.org/WAI/WCAG21/Techniques/general/G208). 

**To add to the reported issue:**

I would like to see more control over how aria-* attributes are applied to the wrapped elements in general. BootstrapVue does a great job of handling a lot of these attributes nicely (so that components are more accessible out of the box), but in the case of more niche uses there are a few limitations. I've run into it recently when wanting to use [aria-disabled instead of disabled](https://github.com/bootstrap-vue/bootstrap-vue/discussions/6678) on some components. 

But my guess is that attribute passthroughs like this will need to wait for the Vue3 rewrite.
