### ISSUE TITLE
<b-form-radio-group> only works with v-model and not @input & :value binding 

### ISSUE THREAD

**Issue by jetacpp** [bootstrap-vue/bootstrap-vue#6705]
### Describe the bug

According to documentation, <b-form-radio-group> works correctly with v-model binding, the radio is checked upon initialization and emit event to update. But I want to use `@input and :value` to avoid having to use another local variable. This radio group will be used in a component. Setting it up this way, upon initialization, the radio is not checked.

### Steps to reproduce the bug

https://codesandbox.io/s/suspicious-lovelace-m1om3

### Versions

**Libraries:**

    "vue": "^2.6.14",
    "bootstrap": "^4.5.3",
    "bootstrap-vue": "^2.21.2"

**Environment:**

- Chrome 71

**Comment by Hiws** [comment]
`<b-form-radio>` and `<b-form-radio-group>` doesn't use the `value` prop for the `v-model`, it uses the `checked` prop instead. So that's what you need to bind to. Your codesandbox is also missing a `v-bind`.

Here's a working solution based on your example.
<https://codesandbox.io/s/ecstatic-hill-dxzdt?file=/src/App.vue>

The reproduction was helpful, but a recommendation next time would be to reduce the amount of clutter, as there seemed to be a lot of unnecessary stuff in there.

**Comment by jetacpp** [comment]
Thank you very much! Your comment is really helpful :)
