### ISSUE TITLE
(intermediate value).map is not a function at b-table with compat-build

### ISSUE THREAD

**Issue by derweise** [bootstrap-vue/bootstrap-vue#7059]
Hi @xanf 

I am using vue3-compat-build.

I am using b-table:

```
        <b-table
          class="d-none d-md-table"
          v-if="!isFetching"
          small
          striped
          :fields="zeitnachweiseHeader"
          :items="zeitnachweise"
          :filter="filter"
        >
          <template v-slot:cell(aktion)="data">
               ...
          </template>
        </b-table>
```

When I go with the mouse over the table, I see following error in the console:
```

Uncaught TypeError: (intermediate value).map is not a function
    getTbodyTrs mixin-tbody.js:62
    getTbodyTrIndex mixin-tbody.js:75
    emitTbodyRowEvent mixin-tbody.js:80
    rowUnhovered mixin-tbody-row.js:104
    callWithErrorHandling vue.runtime.esm-bundler.js:1668
    callWithAsyncErrorHandling vue.runtime.esm-bundler.js:1677
    invoker vue.runtime.esm-bundler.js:11614
    addEventListener vue.runtime.esm-bundler.js:11564
```

**Comment by xanf** [comment]
Thank you, taking look at that!

**Comment by xanf** [comment]
@derweise This was fixed in https://github.com/bootstrap-vue/bootstrap-vue/pull/6905/commits/89d76fd2708bd5204400e4588e875e3ea9434813 a while ago

If you're pointing your code to `https://github.com/bootstrap-vue/bootstrap-vue.git#vue3-compat-build` please take a note that node package managers are extremely agressive around caching, so you might need to play with dropping your **global** cache to pull newest updates to this branch 

Or go directly to your lock file and point it to new commit instead :)

Feel free to reopen issue if you will be able to reproduce it again
