### ISSUE TITLE
on 'b-form-select' how to add title to an option

### ISSUE THREAD

**Issue by ylahav** [bootstrap-vue/bootstrap-vue#708]
I want to add a title (or a tooltip) to a specific option in a 'b-form-select'.

Is it possible?
If yes, HOW?

If 'no' - is this in your road map?

**Comment by tmorehouse** [comment]
Currently it is not possible to add a tooltip to individual options (due to how tooltips are implemented).

Adding a `title` attribute to each option will also be a bit of work, but possible.  It is not currently on our roadmap.

You can however place a title on the select element by adding `title="some title"` attribute to `<b-form-select>`
