### ISSUE TITLE
Emit event upon reaching bottom of a table

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#756]
I would like to implement infinite scrolling, but as far as I could see there is no way to implement that. It would be awesome if we could get an event or something that we can use to implement more functionality into our webpages.

Edit: the infinite scrolling package I want to use: https://github.com/PeachScript/vue-infinite-loading

**Comment by alexsasharegan** [comment]
The way to implement that would be to wrap the table component in your own custom component that binds to the window scroll event. 

Since you have to do good ol' fashioned `window.addEventListener("scroll", callback)`, don't forget to use the component lifecycle hooks to unbind your listener. Also, since throttling these events is best practice, be sure you have a solid reference to the throttled function so you can properly unbind the listener _(lodash throttle and others return new function instances that wrap the original function)_.

Chances are you will need to build a custom table as you will want to perform some kind of `tbody` row cleanup as you scroll and insert new rows, lest you build up infinite nodes as well.
