### ISSUE TITLE
Why use `form-fieldset` for `form-group`?

### ISSUE THREAD

**Issue by odahcam** [bootstrap-vue/bootstrap-vue#763]
Since this component already has a name, calling it another thing is a bit strange. 🤔 

I think when implementing existing features with new tools, a best practice is to keep the original names.

**Comment by tmorehouse** [comment]
Not sure why it was initially called `b-form-fieldset`.  Although we are introducing an alias of `b-form-group`

**Comment by odahcam** [comment]
Nice to hear that. Bootstrap already has custom fieldset styles, so this component should receive a little more attention. :)

**Comment by tmorehouse** [comment]
`b-form-fieldset` & `b-form-group` are the same component (one is just an alias of the other)

**Comment by odahcam** [comment]
I understood, let me clearify: the component in my last sentence was the BS's `<fieldset>`.

**Comment by tmorehouse** [comment]
Plain old `<fieldset>` is standard HTML, with some reboot styling applied to normalize it across browsers.

Maybe making `<b-form-group>` to "primary" version of this (and `<b-form-fieldset>` as the alias) might clear up any confusion.

**Comment by odahcam** [comment]
That would be great!

**Comment by Doogiemuc** [comment]
A form group and a fieldset are *NOT* the same!
A form-group  groups a label with an input.
A fieldset groups several inputs together.

This can for example be seen in older browsers and also in current iOS safari: It draws a frame around the fieldset. 

So you need to distinguish this. The javascript automation for the validation errors of <b-form-group> are great. But they cannot be used if you want to hide that frame on mobile phones.

**Comment by tmorehouse** [comment]
`<b-form-group>`  renders a `<div>` with role group if a input ID is provided to prop `label-for`, and it renders the label as a `<label for="...">`. Otherwise it renders a `<fieldset>` with `<legend>`.  The styles defined by Bootstrap v4.x remove the border on the `<fieldset>` when it has class `'form-group'`. This is explained in the BootstrapVue documentation, and also mentioned in the `forms` documentation on the Bootsttrap v4.x docs.

There shouldn't be a border shown when `<b-form-group>` renders as a fieldset.
