### ISSUE TITLE
Popovers insert div elements into the HTML

### ISSUE THREAD

**Issue by robcresswell** [bootstrap-vue/bootstrap-vue#770]
The popover component inserts a div element; this can be problematic for styling because div is usually has display:block in most browsers, causing it to take up the available space. Since popovers are used to wrap the element, it would make more sense to use a span instead.

**Comment by tmorehouse** [comment]
Similar to your other issue, Popovers and Tooltips are currently going through a complete overhaul due to Bootstrap V4 replacing the tether.js library with popper.js library.

**Comment by robcresswell** [comment]
This is sort-of similar, but I think the issue remains about the element choice. For now it makes sense for me to close it - at least until the rewrite occurs - but it's general good to avoid divs when wrapping elements in this way.

**Comment by tmorehouse** [comment]
Yeah... `span` isn't a good either, as block elements are not allowed inside spans.  The wrapper really should be an inline-block.

And ideally their shouldn't be  wrapper at all (since it can screw up layout).

We are hoping to re-write in more of a `directive` manner, where one would place a popover component somewhere in the document, assign it an ID, and use a directive similar to `v-b-toggle` or `v-b-modal` to trigger the popover.

**Comment by robcresswell** [comment]
Oh, that's a good point. Directive would seem to make more sense; I'll follow along with the development anyway and help / provide feedback if I can. Thanks!
