### ISSUE TITLE
b-form-input formatter and caret position

### ISSUE THREAD

**Issue by FragsterAt** [bootstrap-vue/bootstrap-vue#772]
Try to quickly enter 123 (from the first position) on this fiddle in native input and b-form-input control
https://jsfiddle.net/vo58f9ph/11/

Also there would be nice to have new value, old value and native event as parameters in formatter function, or some more complex event for validate input with mask

**Comment by tmorehouse** [comment]
I think we could add an extra argument that is a reference to the input element to the formatter calling signature.

**Comment by tmorehouse** [comment]
PR #773 adds a second argument (reference to input element) to the `formatter` calling signature

**Comment by FragsterAt** [comment]
Previous value also needed, to make "overwrite" with "mask" behaviour in formatter function

**Comment by tmorehouse** [comment]
Since formatter gets called before the v-model is updated, you would have access to the previous value via the data object you have bound to the `b-form-input` `v-model`.  

Note for `lazy-formatter` mode, the `v-model` will be updated with the raw input value until the `change` event triggers (usually on blur), at which point the `formatter` will be called prior to the update.
