### ISSUE TITLE
Edit page button goes to 404 page

### ISSUE THREAD

**Issue by Tedderouni** [bootstrap-vue/bootstrap-vue#88]
The 'Edit page' button leads to a 404 page.

https://bootstrap-vue.github.io/docs/components/alerts/

**Comment by Tedderouni** [comment]
This did not fix it, I'm still getting the 404.

**Comment by SirLamer** [comment]
I understand the docs renderer is misbehaving, so it's likely the source code has been fixed but documentation has not been re-compiled yet.

**Comment by paranoicsan** [comment]
It works now.

**Comment by pi0** [comment]
@paranoicsan It works buggy! The problem is that if you change pages client side then it works but if you open any page for first time (the ssr generated docs by Nuxt.js) it just fails with an incorrect URL like this `/alerts/.vue` isntead of `/alerts.vue`. I'm trying to figure out this strange problem.
