### ISSUE TITLE
The nav connot togglable automatically, but always toggled.

### ISSUE THREAD

**Issue by JohnNiang** [bootstrap-vue/bootstrap-vue#883]
The nav connot togglable automatically, always toggled.

Latest version: 
> bootstrap-vue@^1.0.0-beta.4

**Comment by tmorehouse** [comment]
This has been fixed in the 1.x branch, and should be available soon.

**Comment by vitorvr** [comment]
@tmorehouse Hi! That fix has been released? Already download the versrion "bootstrap-vue": "^1.0.0-beta.4" and got this problem. 
I'm getting this error as well: 
> "12:480 [Vue warn]: Invalid prop: type check failed for prop "toggleable". Expected Boolean, got String."

And for some reason I can't use variant "inverse".
Have these issues mapped already?

Thanks!

**Comment by tmorehouse** [comment]
Not released yet, but will be soon.  Its in the dev branch which is now just being build for deployment.

**Comment by vitorvr** [comment]
Thanks!

**Comment by tmorehouse** [comment]
`inverse` prop has been replaced with a new prop `type` which can be set to `dark` (meaning background is dark), or `light` (which means background is light).  the type controls which type of text coloring to apply.  (new BootstrapV4.beta classes `.navbar-light` and` .navbar-dark`)

Check the latest Bootstrap V4 docs to see the changes to navbar

**Comment by vitorvr** [comment]
Got it!
I checked in BootstrapVue docs, because this I was using inverse:

`<b-navbar>` supports the standard Bootstrap V4 available background color variants. Set the variant prop to one of the following values to change the background `color: primary, success, info, warning, danger, inverse, or faded.`
Control the text type by setting type prop to `light `for use with light background color variants, or `inverse `for dark background color variants.

Thanks for your help! :)

**Comment by tmorehouse** [comment]
Docs are slightly outdated.  no inverse or faded variants anymore (I think), but there is a dark and light now

**Comment by tmorehouse** [comment]
Also, type accepts 'light' or 'dark' (not inverse)
