### ISSUE TITLE
How can I handle enter event in b-form-input component?

### ISSUE THREAD

**Issue by greenfrog82** [bootstrap-vue/bootstrap-vue#936]
Hi all ~
I'm new to vue.js and using bootstrap-vue in my project.
What I want to do is to handle enter event in b-form-input component. But that is not work well. 
The following code is the sample what I want to do.

```html
<b-form-input id="input-otp-code" v-model="otpCode"
                  type="text"
                  placeholder="Please enter your name."
                  v-on:click="test_event_handler"></b-form-input>
```
```javascript
methods: {
    test_event_handler() {
      console.log('test click event handler.');
    }
}
```

But when I use the above code pure html something like input tag, That is work well.
please see the following code.

```html
<input type="text" placeholder="Pleae enter your name." v-on:keydown.enter="test_event_handler"/>
```
```javascript
methods: {
    test_event_handler() {
      console.log('test click event handler.');
    }
}
```

How can I handle enter event in b-form-input component? 
Thank you.

**Comment by tmorehouse** [comment]
The `click` event is not the same as the `keydown` (or `keyup`) event (which you can use to trap the enter key)

Since this is a custom vue component, it doesn't natively emit native browser events (like a native input would).

To trap native evnets, you need to use the `.native` event modifier.

To handle click you would do:
```html
<b-form-input @click.native="test_event_handler" ...></b-form-input>
```

And for enter key:
```html
<b-form-input @keydown.native="test_keydown_handler" ...></b-form-input>
```
```js
methods: {
  test_keydown_handler(event) {
     if (event.which === 13) {
        // The key pressed was the enter key
     }
  }
}
```

Or let Vue do the event type filtering for you:
```html
<b-form-input @keydown.enter.native="test_enter_handler" ...></b-form-input>
```

When using the `.native` modifier, Vue will pass the native event object as the first argument to your handler.

See https://vuejs.org/v2/api/#v-on

**Comment by greenfrog82** [comment]
Thank you for your comment.
I've resolved this problem with your help.
