### ISSUE TITLE
Need Support for Icons in Tabs

### ISSUE THREAD

**Issue by nrobates** [bootstrap-vue/bootstrap-vue#979]
When using the tabs component and defining a tab, being able to use a slot to allow a custom designed tab or at least an icon prop to set the icon class that you would like and have it put the icon in the tab along with the title.

The lack of this ability currently is having me look at other possible alternatives and I would prefer to use this library instead.

**Comment by tmorehouse** [comment]
Slots can be a bit picky, when transferring the content to another location in the DOM, although copying the inner HTML of the slot might be possible.

Would supporting basic static HTML in the `<b-tab>` `title` prop suffice?

**Comment by tmorehouse** [comment]
Actually, looking at the `b-tabs` code https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/tabs.vue#L22-L38 I can see that we already support HTML in the tab navigation tabs.  Just supply an HTML string (which includes your icon markup) as the `title` prop to `b-tab`.

Currently since the title is defined in `b-tab` for each tab shown in `b-tabs`, it is basically impossible to use a a slot to provide that markup, as the slot needs to be rendered with in the `b-tab` context, not in `b-tabs`. And then doing a DOM move of that slot into `b-tabs` would be problematic as tabs are added and removed and vue.js would spew console errors.

**Comment by tmorehouse** [comment]
Example support for HTML:
![image](https://user-images.githubusercontent.com/2781561/29953410-5d42b9ce-8ea6-11e7-9e1f-d7a8385e6312.png)

**Comment by clytras** [comment]
This isn't working any more. Is there a way to use custom HTML for `<b-tab` titles to insert icons using the latest version?
