### ISSUE TITLE
Table - computed values not triggered in versions 1.0.0-beta.6 and 1.0.0-beta.7

### ISSUE THREAD

**Issue by egomolka** [bootstrap-vue/bootstrap-vue#987]
Hi.
I have a lot of derived values in the rows and columns of my tables. I used the Vue.js "computed" feature to update these derived values interactively as the user updates the table. This was working fine in bootstrap-vue 1.0.0-beta.5. It is not working in 1.0.0-beta.6 and 1.0.0-beta.7. I can achieve something similar with the Vue.js "filters" feature, but it's not ideal.
I don't see an option in the b-table documentation to adjust for this change in behavior. I am not using the items provider feature, which has a table refresh option, so I'm not sure how to get around this.

**Comment by tmorehouse** [comment]
B-table makes a full copy (deep clone) of the data (before it made a shallow copy of the items array, which inadvertently could mutate the original provided items array).

The cloning method JSON encodes and JSON decodes the items array, in order to not affect the original items array.  This might be why the behavior is different.

**Comment by tmorehouse** [comment]
We may need to adjust the items prop watcher to see if the source table has changes in content.

Would you be able to provide a short example fiddle?

**Comment by egomolka** [comment]
I have placed a code snippet here:
https://jsfiddle.net/edge2017/opdn29rw/3/
I started out trying to create runn-able code, but it was taking too long, so I just wrote this and placed it all in the Fiddle html window.
This is a very simple example, where the client wanted to enter some values by month and also wanted to see the most recent entry in a separate virtual column. The actual tables also have various other calculations, which mimic the client's Excel spreadsheets.

**Comment by tmorehouse** [comment]
are these function within your items data?  IF so, they will not get copied over, as only primitive objects/data will be copied when we make a copy of the items table before manipulating it.

**Comment by egomolka** [comment]
I'm not sure what you mean by "function within your items data". The functions are triggered by changes to the original source data. I have a dataset that I receive from a Rails backend. I populate the table with this source dataset. I have computed/derived column values that can change based upon table edits. This works in a normal html table, and was working up through beta.5. I had assumed that the b-table was still referencing the original dataset object, which would mean that the computed values should be triggered. If b-table is just using a copy of the dataset, which it may need to do for filtering or pagination reasons, then I can see why the computed values aren't being updated. I guess I need to understand the intended plan for b-table. Is there still a way to dynamically derive values with b-table? If not, I will need to investigate other table options.

**Comment by tmorehouse** [comment]
The items array that b-table uses is a _deep clone_ of the data, and any changes it it will not alter the original items array provided.  Before beta.5 we only made a shallow copy of the data (basically items.slice() which makes a new array reference, but the elements in the array point back to the original table).  But with the advent of formatter functions, which do alter the contents of the local copy of the table, w have to do a deep clone of the table, rather than a shallow clone.  The inner table data **was always** intended to be read only. **copy** of the data (as the data can come from various methods).

Your best bet, is to alter your original table data (which will then trigger b-table to refresh). Place a unique ID (or original row number) in your items array.  This will be copied into the B-Table local copy of your data.  When making "edits" in b-table, use this index to alter the contents of your source items array. B-table will detect a change in the items prop and re-render the b-table content to reflect the updated values.

**Comment by tmorehouse** [comment]
PR #991 may address your issue.

**Comment by egomolka** [comment]
Definitely looks like it. Thanks so much for the heads-up. I am heading out on vacation this week, and will pick this up when I get back.
